---
name: "Kotlin"

"on":
  workflow_dispatch:
  push:
    branches: [main]
  label:
    types: [created]
  pull_request:
  release:
    types: [published]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
  GITHUB_USER: cricut-builduser
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  JAVA_VERSION: 11
  FISHYJOES: 1

jobs:
  build-test-kotlin-mac:
    name: "macOS: Build and test kotlin bindings"
    runs-on: [macOS, self-hosted, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CRICUT_GPR_TOKEN }}

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}

      - name: Pre-build hook
        shell: bash
        run: |
          # Build customization can be added here with the `CIPreBuildHook` key in fishy-joes.yaml

      - name: Build library
        shell: zsh {0}
        run: |
          set -euxo pipefail

          swift run -- fishy-joes --kotlin-fast --fat generate build

      - name: Test from gradle
        shell: zsh {0}
        run: |
          set -euxo pipefail

          swift run -- fishy-joes --kotlin-fast --fat test

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: mac_libs
          path: bindings/kotlin/generated/src/main/resources

  build-test-kotlin-linux:
    name: "Ubuntu: Build and test kotlin bindings"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cricut/android-swift-runtime:3.0.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CRICUT_GPR_TOKEN }}

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}

      - name: Pre-build hook
        shell: bash
        run: |
          # Build customization can be added here with the `CIPreBuildHook` key in fishy-joes.yaml

      - name: Build library
        shell: zsh {0}
        run: |
          set -euxo pipefail

          swift run -- fishy-joes --kotlin build --no-use-docker

      - name: Test from gradle
        shell: zsh {0}
        run: |
          set -euxo pipefail

          swift run -- fishy-joes --kotlin test --no-use-docker

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_libs
          path: bindings/kotlin/generated/src/main/resources

  build-test-kotlin-windows:
    name: "Windows: Build and test kotlin bindings"
    runs-on: windows-latest
    steps:
      - name: Enable git longpaths
        run: "git config --system core.longpaths true"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CRICUT_GPR_TOKEN }}

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Install winget
        uses: Cyberboss/install-winget@v1

      - name: Install specific MSVC build tools and Win SDK version
        shell: pwsh
        run: |
          winget install --id Microsoft.VisualStudio.2022.Professional --exact --force --custom "--add Microsoft.VisualStudio.Component.Windows11SDK.22000 --add Microsoft.VisualStudio.Component.VC.14.36.17.6.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.Tools.ARM64" --accept-source-agreements --accept-package-agreements

      - name: vsdevcmd
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          host_arch: x64
          winsdk: 10.0.22000.0
          toolset_version: 14.36.32532

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.10.1-release
          tag: 5.10.1-RELEASE

      - name: Copy module maps
        continue-on-error: true
        shell: cmd
        run: |
          copy "%SDKROOT%\usr\share\ucrt.modulemap" "%UniversalCRTSdkDir%\Include\10.0.22000.0\ucrt\module.modulemap"
          copy "%SDKROOT%\usr\share\vcruntime.modulemap" "%VCToolsInstallDir%\include\module.modulemap"
          copy "%SDKROOT%\usr\share\vcruntime.apinotes" "%VCToolsInstallDir%\include\vcruntime.apinotes"
          copy "%SDKROOT%\usr\share\winsdk.modulemap" "%UniversalCRTSdkDir%\Include\10.0.22000.0\um\module.modulemap"

      - name: Pre-resolve Required SwiftPM Packages & Fetch FishyJoes Scripts
        continue-on-error: true
        shell: pwsh
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          swift package resolve
          swift package resolve
          swift package resolve
          echo SWIFT_WINDOWS_BASH=".build/checkouts/FishyJoes/scripts/swift-shim.ps1" >> $env:GITHUB_ENV

      - name: Pre-build hook
        shell: bash
        run: |
          # Build customization can be added here with the `CIPreBuildHook` key in fishy-joes.yaml

      - name: Build library
        shell: bash
        run: |
          set -euxo pipefail

          "$SWIFT_WINDOWS_BASH" run -- fishy-joes --kotlin-fast build

      # NOTE: Performing this step earlier seems to cause the build to fail, likely due to the Swift install step & path issues
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}

      - name: Test library from gradle
        shell: bash
        run: |
          set -euxo pipefail

          "$SWIFT_WINDOWS_BASH" run -- fishy-joes --kotlin-fast test

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: windows_libs
          path: bindings/kotlin/generated/src/main/resources

  kotlin-publish:
    name: Publish kotlin package
    runs-on: ubuntu-latest
    needs:
      - build-test-kotlin-mac
      - build-test-kotlin-linux
      - build-test-kotlin-windows
    if: success()
    env:
      GITHUB_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CRICUT_GPR_TOKEN }}

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ env.JAVA_VERSION }}

      - name: Configure build environment
        run: |
          set -euxo pipefail

          sudo apt-get install zsh

      - name: Retrieve Artifacts
        uses: actions/download-artifact@v4

      - name: Install Artifacts
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ls *

          mkdir -p bindings/kotlin/generated/src/main/resources/

          mv mac_libs/mac bindings/kotlin/generated/src/main/resources/
          mv windows_libs/windows bindings/kotlin/generated/src/main/resources/ || true
          mv ubuntu_libs/linux bindings/kotlin/generated/src/main/resources/
          mv ubuntu_libs/lib bindings/kotlin/generated/src/main/resources/

      - name: Test publish
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd bindings/kotlin/generated
          ./gradlew publishToMavenLocal

      - name: Publish
        shell: zsh {0}
        if: github.event_name == 'release'
        run: |
          set -euxo pipefail

          VERSION=${GITHUB_REF#refs/*/}
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)*$ ]]; then
              VERSION="0.0.1-$(git rev-parse --short HEAD)"
          fi

          cd bindings/kotlin/generated

          echo "Detected Version is '$VERSION'"
          export VERSION
          ./gradlew updateVersion
          ./gradlew assemble publish
