import Foundation
import SourceryRuntime

struct NodeTranslate {
    func translateGetter(for variable: Variable, context: CDeclareContext) -> [SourceFragment] {
        guard let cName = variable.annotations["cdecl.get"] as? String else { return [] }
        let nodeName = variable.annotations["nodedecl.get"] as? String ?? variable.annotations["nodedecl"] as? String ?? cName

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).globalName

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "env.this(as: \(containingNamespace).self)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        debug("generating getter for \(containingNamespace).\(variable.name)`")
        let fragment = context.swiftFragment(
            "NodeInterface/\(containingNamespace)+nodedecl.swift",
            additionalImports: ["CDeclareRuntime"]
        )
        fragment.output("// Generated by sourcery:cdecl.get for `\(containingNamespace).\(variable.name)`")
        fragment.outputBlock("let node_\(cName): napi_callback = { env, info in", closeWith: "}") {
            fragment.outputBlock("CDeclareRuntime.callbackBody(env, info, name: \"\(nodeName)\", expectedArgumentCount: 0) { env in", closeWith: "}") {
                fragment.output("try \(selfExpression).\(variable.name).toNode(env: env.env)")
            }
        }

        return [fragment]
    }

    func translate(method: SourceryMethod, context: CDeclareContext) -> [SourceFragment] {
        guard method.annotations["cdecl.get"] == nil,
              method.annotations["cdecl.set"] == nil else {
            let context = method.definedInTypeName?.description ?? context.module
            fatalErr("""
                found annotation `sourcery: cdecl.{get,set} = ...` on method \(method.name) in \(context)
                use `sourcery: cdecl = ...` for methods instead.
                """)
        }
        guard let cName = method.annotations["cdecl"] as? String else { return [] }
        let nodeName = method.annotations["nodedecl"] as? String ?? cName

        let selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).globalName
            // Method.isMutating seems to be a bit buggy...
            let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })

            if isMutating {
                // TODO: do
                return []
            }

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "env.this(as: \(containingNamespace).self)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        debug("generating \(containingNamespace).\(method.name)`")
        var omitParameters = Set((method.annotations["cdecl.omitParameters"] as? String).asArray.flatMap { $0.components(separatedBy: " ") })
        var parameters: [SwiftFormal] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            parameters.append(
                SwiftFormal(
                    label: parameter.argumentLabel,
                    name: parameter.name,
                    type: context.resolve(type: parameter.typeName.better)
                )
            )
        }
        precondition(omitParameters.isEmpty, "Can't find parameters \(omitParameters) to omit")

        // let translatedReturn = resolveNode(type: method.returnTypeName.better)
        // formals.append(contentsOf: translatedReturn.outFormals)

        let formals = parameters.flatMap(\.asSwiftFormals)
        let nodeBridgeFragment = context.swiftFragment(
            "NodeInterface/\(containingNamespace)+nodedecl.swift",
            additionalImports: ["CDeclareRuntime"]
        )
        nodeBridgeFragment.output("// Generated by sourcery:cdecl for `\(containingNamespace).\(method.name)`")
        nodeBridgeFragment.outputBlock("let node_\(cName): napi_callback = { env, info in", closeWith: "}") {
            nodeBridgeFragment.outputBlock("CDeclareRuntime.callbackBody(env, info, name: \"\(nodeName)\", expectedArgumentCount: \(formals.count)) { env in", closeWith: "}") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"
                nodeBridgeFragment.outputBlock("try \(selfExpression)\(callName)(", newLineTerminated: false) {
                    nodeBridgeFragment.outputMap(parameters.enumerated(), separator: ",") {
                        let (index, formal) = $0
                        return (formal.label.map { "\($0): " } ?? "") + "try env.argument(at: \(index), as: \(formal.type.globalName).self)"
                    }
                }
                nodeBridgeFragment.output(".toNode(env: env.env)")
            }
        }

        return [nodeBridgeFragment]
    }

}
