sonar.organization=cricutsonarcloud
sonar.projectKey=cricut_FishyJoes
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/Tests/**,**/Generated/**,**/Package.swift
sonar.exclusions=**/Tests/**,**/Generated/**,**/Package.swift
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-