sonar.organization=cricutsonarcloud
sonar.projectKey=cricut_FishyJoes
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/Tests/**,**/Package.swift,.build/**,**/test/**
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
