---
# __AUTOGEN_WARNING__

name: "regenerate-check"

"on":
  workflow_dispatch:
  pull_request:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  __CI_SHARED_ENV_YAML__

jobs:
  regenerate-check:
    name: "macOS: regenerate check"
    runs-on: __CI_RUNNER_MACOS__
    steps:
      - __CI_GIT_STEPS__

      - name: Install generation tools
        shell: zsh {0}
        run: |
          yq --version || brew install yq
          mint --version || brew install mint

      - name: Ensure re-generating does not change committed generated code
        shell: zsh {0}
        run: |
          set -euo pipefail

          swift run -- fishy-joes generate

          if [ ! -z "$(git status --porcelain .)" ]; then
            git diff | tee regenerated.patch
            git status
            echo '::error:: generation modified sources'
            echo '::error::   run `FISHYJOES=1 swift run fishy-joes generate` from root of repository and re-commit'
            echo '::error::   (alternatively, download patch attached to this workflow and run `git apply regenerated.patch`)'
            exit 1
          fi

      - name: Upload patch if needed
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: regenerated.patch
          path: regenerated.patch
          if-no-files-found: ignore
