name: cricut_test_api
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.8.0
  fishyjoes_dart:
    path: ../../../dart-runtime
  tuple: ^2.0.2
  collection: ^1.18.0
  ffi: ^2.1.0
    # git:
    #   url: https://github.com/cricut/FishyJoes
    #   ref: 3.0.3-alpha7
    #   path: dart-runtime


dev_dependencies:
  ffigen: ^7.2.0
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
