import { TestAPI } from 'TestAPI';

// Needed to compare maps, because jest was treating the ones generated by NAPI differently somehow
function sortedEntries<K, V>(map: Map<K, V>): [K, V][] {
    return [...map.entries()].sort()
}

test('PrimitiveValues', () => {
    expect(TestAPI.Primitives.falseBool).toEqual(false);
    expect(TestAPI.Primitives.trueBool).toEqual(true);
    expect(TestAPI.Primitives.zeroUInt8).toEqual(0);
    expect(TestAPI.Primitives.minUInt8).toEqual(0x00);
    expect(TestAPI.Primitives.maxUInt8).toEqual(0xFF);
    expect(TestAPI.Primitives.zeroUInt16).toEqual(0);
    expect(TestAPI.Primitives.minUInt16).toEqual(0x0000);
    expect(TestAPI.Primitives.maxUInt16).toEqual(0xFFFF);
    expect(TestAPI.Primitives.zeroUInt32).toEqual(0);
    expect(TestAPI.Primitives.minUInt32).toEqual(0x00000000);
    expect(TestAPI.Primitives.maxUInt32).toEqual(0xFFFFFFFF);
    expect(TestAPI.Primitives.zeroUInt64).toEqual(BigInt("0"));
    expect(TestAPI.Primitives.minUInt64).toEqual(BigInt("0x0000000000000000"));
    expect(TestAPI.Primitives.maxUInt64).toEqual(BigInt("0xFFFFFFFFFFFFFFFF"));
    expect(TestAPI.Primitives.zeroInt8).toEqual(0);
    expect(TestAPI.Primitives.minInt8).toEqual(-0x80);
    expect(TestAPI.Primitives.maxInt8).toEqual(0x7F);
    expect(TestAPI.Primitives.zeroInt16).toEqual(0);
    expect(TestAPI.Primitives.minInt16).toEqual(-0x8000);
    expect(TestAPI.Primitives.maxInt16).toEqual(0x7FFF);
    expect(TestAPI.Primitives.zeroInt32).toEqual(0);
    expect(TestAPI.Primitives.minInt32).toEqual(-0x80000000);
    expect(TestAPI.Primitives.maxInt32).toEqual(0x7FFFFFFF);
    expect(TestAPI.Primitives.zeroInt64).toEqual(BigInt("0"));
    expect(TestAPI.Primitives.minInt64).toEqual(-BigInt("0x8000000000000000"));
    expect(TestAPI.Primitives.maxInt64).toEqual(BigInt("0x7FFFFFFFFFFFFFFF"));
    expect(TestAPI.Primitives.zeroFloat).toEqual(0.0);
    expect(TestAPI.Primitives.minFloat).toEqual(-3.4028234663852886e+38);
    expect(TestAPI.Primitives.maxFloat).toEqual(3.4028234663852886e+38);
    expect(TestAPI.Primitives.zeroDouble).toEqual(0.0);
    expect(TestAPI.Primitives.minDouble).toEqual(-Number.MAX_VALUE);
    expect(TestAPI.Primitives.maxDouble).toEqual(Number.MAX_VALUE);
});

test('ArraysOfPrimitiveValues', () => {
    expect(TestAPI.Primitives.manyBool).toEqual([false, true])
    expect(TestAPI.Primitives.manyUInt8).toEqual([0, 0x00, 0xFF]);
    expect(TestAPI.Primitives.manyUInt16).toEqual([0, 0x0000, 0xFFFF]);
    expect(TestAPI.Primitives.manyUInt32).toEqual([0, 0x00000000, 0xFFFFFFFF]);
    expect(TestAPI.Primitives.manyUInt64).toEqual([BigInt("0"), BigInt("0x0000000000000000"), BigInt("0xFFFFFFFFFFFFFFFF")]);
    expect(TestAPI.Primitives.manyInt8).toEqual([0, -0x80, 0x7F]);
    expect(TestAPI.Primitives.manyInt16).toEqual([0, -0x8000, 0x7FFF]);
    expect(TestAPI.Primitives.manyInt32).toEqual([0, -0x80000000, 0x7FFFFFFF]);
    expect(TestAPI.Primitives.manyInt64).toEqual([BigInt("0"), -BigInt("0x8000000000000000"), BigInt("0x7FFFFFFFFFFFFFFF")]);
    expect(TestAPI.Primitives.manyFloat).toEqual([0, -3.4028234663852886e+38, 3.4028234663852886e+38]);
    expect(TestAPI.Primitives.manyDouble).toEqual([0, -Number.MAX_VALUE, Number.MAX_VALUE]);
});

test('ArraysOfOptionalPrimitiveValues', () => {
    expect(TestAPI.Primitives.manyMaybeBool).toEqual([undefined, false, true]);
    expect(TestAPI.Primitives.manyMaybeUInt8).toEqual([undefined, 0, 0x00, 0xFF]);
    expect(TestAPI.Primitives.manyMaybeUInt16).toEqual([undefined, 0, 0x0000, 0xFFFF]);
    expect(TestAPI.Primitives.manyMaybeUInt32).toEqual([undefined, 0, 0x00000000, 0xFFFFFFFF]);
    expect(TestAPI.Primitives.manyMaybeUInt64).toEqual([undefined, BigInt("0"), BigInt("0x0000000000000000"), BigInt("0xFFFFFFFFFFFFFFFF")]);
    expect(TestAPI.Primitives.manyMaybeInt8).toEqual([undefined, 0, -0x80, 0x7F]);
    expect(TestAPI.Primitives.manyMaybeInt16).toEqual([undefined, 0, -0x8000, 0x7FFF]);
    expect(TestAPI.Primitives.manyMaybeInt32).toEqual([undefined, 0, -0x80000000, 0x7FFFFFFF]);
    expect(TestAPI.Primitives.manyMaybeInt64).toEqual([undefined, BigInt("0"), -BigInt("0x8000000000000000"), BigInt("0x7FFFFFFFFFFFFFFF")]);
    expect(TestAPI.Primitives.manyMaybeFloat).toEqual([undefined, 0, -3.4028234663852886e+38, 3.4028234663852886e+38]);
    expect(TestAPI.Primitives.manyMaybeDouble).toEqual([undefined, 0, -Number.MAX_VALUE, Number.MAX_VALUE]);
});

test('FunctionsTakingAndReturningPrimitiveTypes', () => {
    expect(TestAPI.Primitives.echoBool(false)).toEqual(false);
    expect(TestAPI.Primitives.echoBool(true)).toEqual(true);
    expect(TestAPI.Primitives.echoUInt8(0)).toEqual(0);
    expect(TestAPI.Primitives.echoUInt8(0x00)).toEqual(0x00);
    expect(TestAPI.Primitives.echoUInt8(0xFF)).toEqual(0xFF);
    expect(TestAPI.Primitives.echoUInt16(0)).toEqual(0);
    expect(TestAPI.Primitives.echoUInt16(0x0000)).toEqual(0x0000);
    expect(TestAPI.Primitives.echoUInt16(0xFFFF)).toEqual(0xFFFF);
    expect(TestAPI.Primitives.echoUInt32(0)).toEqual(0);
    expect(TestAPI.Primitives.echoUInt32(0x00000000)).toEqual(0x00000000);
    expect(TestAPI.Primitives.echoUInt32(0xFFFFFFFF)).toEqual(0xFFFFFFFF);
    expect(TestAPI.Primitives.echoUInt64(BigInt(0))).toEqual(BigInt(0));
    expect(TestAPI.Primitives.echoUInt64(BigInt("0x0000000000000000"))).toEqual(BigInt("0x0000000000000000"));
    expect(TestAPI.Primitives.echoUInt64(BigInt("0xFFFFFFFFFFFFFFFF"))).toEqual(BigInt("0xFFFFFFFFFFFFFFFF"));
    expect(TestAPI.Primitives.echoInt8(0)).toEqual(0);
    expect(TestAPI.Primitives.echoInt8(-0x80)).toEqual(-0x80);
    expect(TestAPI.Primitives.echoInt8(0x7F)).toEqual(0x7F);
    expect(TestAPI.Primitives.echoInt16(0)).toEqual(0);
    expect(TestAPI.Primitives.echoInt16(-0x8000)).toEqual(-0x8000);
    expect(TestAPI.Primitives.echoInt16(0x7FFF)).toEqual(0x7FFF);
    expect(TestAPI.Primitives.echoInt32(0)).toEqual(0);
    expect(TestAPI.Primitives.echoInt32(-0x80000000)).toEqual(-0x80000000);
    expect(TestAPI.Primitives.echoInt32(0x7FFFFFFF)).toEqual(0x7FFFFFFF);
    expect(TestAPI.Primitives.echoInt64(BigInt(0))).toEqual(BigInt(0));
    expect(TestAPI.Primitives.echoInt64(-BigInt("0x8000000000000000"))).toEqual(-BigInt("0x8000000000000000"));
    expect(TestAPI.Primitives.echoInt64(BigInt("0x7FFFFFFFFFFFFFFF"))).toEqual(BigInt("0x7FFFFFFFFFFFFFFF"));
    expect(TestAPI.Primitives.echoFloat(0.0)).toEqual(0.0);
    expect(TestAPI.Primitives.echoFloat(-3.4028234663852886e+38)).toEqual(-3.4028234663852886e+38);
    expect(TestAPI.Primitives.echoFloat(3.4028234663852886e+38)).toEqual(3.4028234663852886e+38);
    expect(TestAPI.Primitives.echoDouble(0.0)).toEqual(0.0);
    expect(TestAPI.Primitives.echoDouble(-Number.MAX_VALUE)).toEqual(-Number.MAX_VALUE);
    expect(TestAPI.Primitives.echoDouble(Number.MAX_VALUE)).toEqual(Number.MAX_VALUE);
});

test('FunctionsTakingReturningOptionalPrimitiveTypes', () => {
    expect(TestAPI.Primitives.maybeEchoBool(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoBool(false)).toEqual(false);
    expect(TestAPI.Primitives.maybeEchoBool(true)).toEqual(true);
    expect(TestAPI.Primitives.maybeEchoUInt8(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoUInt8(0)).toEqual(0);
    expect(TestAPI.Primitives.maybeEchoUInt8(0x00)).toEqual(0x00);
    expect(TestAPI.Primitives.maybeEchoUInt8(0xFF)).toEqual(0xFF);
    expect(TestAPI.Primitives.maybeEchoUInt16(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoUInt16(0)).toEqual(0);
    expect(TestAPI.Primitives.maybeEchoUInt16(0x0000)).toEqual(0x0000);
    expect(TestAPI.Primitives.maybeEchoUInt16(0xFFFF)).toEqual(0xFFFF);
    expect(TestAPI.Primitives.maybeEchoUInt32(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoUInt32(0)).toEqual(0);
    expect(TestAPI.Primitives.maybeEchoUInt32(0x00000000)).toEqual(0x00000000);
    expect(TestAPI.Primitives.maybeEchoUInt32(0xFFFFFFFF)).toEqual(0xFFFFFFFF);
    expect(TestAPI.Primitives.maybeEchoUInt64(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoUInt64(BigInt(0))).toEqual(BigInt(0));
    expect(TestAPI.Primitives.maybeEchoUInt64(BigInt("0x0000000000000000"))).toEqual(BigInt("0x0000000000000000"));
    expect(TestAPI.Primitives.maybeEchoUInt64(BigInt("0xFFFFFFFFFFFFFFFF"))).toEqual(BigInt("0xFFFFFFFFFFFFFFFF"));
    expect(TestAPI.Primitives.maybeEchoInt8(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoInt8(0)).toEqual(0);
    expect(TestAPI.Primitives.maybeEchoInt8(-0x80)).toEqual(-0x80);
    expect(TestAPI.Primitives.maybeEchoInt8(0x7F)).toEqual(0x7F);
    expect(TestAPI.Primitives.maybeEchoInt16(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoInt16(0)).toEqual(0);
    expect(TestAPI.Primitives.maybeEchoInt16(-0x8000)).toEqual(-0x8000);
    expect(TestAPI.Primitives.maybeEchoInt16(0x7FFF)).toEqual(0x7FFF);
    expect(TestAPI.Primitives.maybeEchoInt32(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoInt32(0)).toEqual(0);
    expect(TestAPI.Primitives.maybeEchoInt32(-0x80000000)).toEqual(-0x80000000);
    expect(TestAPI.Primitives.maybeEchoInt32(0x7FFFFFFF)).toEqual(0x7FFFFFFF);
    expect(TestAPI.Primitives.maybeEchoInt64(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoInt64(BigInt(0))).toEqual(BigInt(0));
    expect(TestAPI.Primitives.maybeEchoInt64(-BigInt("0x8000000000000000"))).toEqual(-BigInt("0x8000000000000000"));
    expect(TestAPI.Primitives.maybeEchoInt64(BigInt("0x7FFFFFFFFFFFFFFF"))).toEqual(BigInt("0x7FFFFFFFFFFFFFFF"));
    expect(TestAPI.Primitives.maybeEchoFloat(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoFloat(0.0)).toEqual(0.0);
    expect(TestAPI.Primitives.maybeEchoFloat(-3.4028234663852886e+38)).toEqual(-3.4028234663852886e+38);
    expect(TestAPI.Primitives.maybeEchoFloat(3.4028234663852886e+38)).toEqual(3.4028234663852886e+38);
    expect(TestAPI.Primitives.maybeEchoDouble(undefined)).toEqual(undefined);
    expect(TestAPI.Primitives.maybeEchoDouble(0.0)).toEqual(0.0);
    expect(TestAPI.Primitives.maybeEchoDouble(-Number.MAX_VALUE)).toEqual(-Number.MAX_VALUE);
    expect(TestAPI.Primitives.maybeEchoDouble(Number.MAX_VALUE)).toEqual(Number.MAX_VALUE);
});

test('FunctionsTakingClosuresWithPrimitiveTypes', () => {
    // TODO: Fix breakage
    // expect(TestAPI.Primitives.valueMapper(10) { (it ?: 0) * 2 }).toEqual(20);
});

test('ObjectsWithPrimitiveMembers', () => {
    expect(TestAPI.Primitives.PrimitiveHolder.staticPropery).toEqual([undefined, 0, 0x00, 0xFF]);
    expect(TestAPI.Primitives.PrimitiveHolder.staticMutablePropery).toEqual([undefined, 0, 0x00, 0xFF]);
    TestAPI.Primitives.PrimitiveHolder.staticMutablePropery = [100, 200];
    expect(TestAPI.Primitives.PrimitiveHolder.staticMutablePropery).toEqual([100, 200]);
    let s = TestAPI.Primitives.defaultPrimitiveHolder;
    expect(s).toEqual(TestAPI.Primitives.defaultPrimitiveHolder);
    s.b = !s.b
    expect(s).not.toEqual(TestAPI.Primitives.defaultPrimitiveHolder);
});


// Struct Tests

test('StructConstruction', () => {
    let memberwise = TestAPI.Structs.MemberwiseStruct.create()
    expect(memberwise.immutable).toEqual("Eternal")
    expect(memberwise.mutable).toEqual("Fickle")

    let reference = TestAPI.Structs.ReferenceStruct.create()
    expect(reference.immutable).toEqual("Eternal")
    expect(reference.mutable).toEqual("Fickle")
});

test('StructMutablility', () => {
    let memberwise = TestAPI.Structs.MemberwiseStruct.create()
    expect(memberwise.immutable).toEqual("Eternal")
    // memberwise.immutable = "Should generate a compile error!"
    expect(memberwise.mutable).toEqual("Fickle")
    memberwise.mutable = "Fickle as the wind"
    expect(memberwise.mutable).not.toEqual("Fickle")

    let reference = TestAPI.Structs.ReferenceStruct.create()
    expect(reference.immutable).toEqual("Eternal")
    // reference.immutable = "Should generate a compile error!"
    expect(reference.mutable).toEqual("Fickle")
    memberwise.mutable = "Fickle as the wind"
    expect(memberwise.mutable).not.toEqual("Fickle")
});

test('StructEquality', () => {
    expect(TestAPI.Structs.MemberwiseStruct.create()).toEqual(TestAPI.Structs.MemberwiseStruct.create())
    expect(TestAPI.Structs.ReferenceStruct.create()).toEqual(TestAPI.Structs.ReferenceStruct.create())
    expect(TestAPI.Structs.MemberwiseStruct.create()).not.toEqual(TestAPI.Structs.ReferenceStruct.create())
});

// String Tests

test('StringValues', () => {
    expect(TestAPI.Strings.simple).toEqual("Hello")
    expect(TestAPI.Strings.accent).toEqual("Olá")
    expect(TestAPI.Strings.script).toEqual("こんにちは")
    expect(TestAPI.Strings.chinese).toEqual("你好")
    expect(TestAPI.Strings.chineseBMP).toEqual("豈更車賈滑")
    expect(TestAPI.Strings.chineseSIP).toEqual("\u{20001}\u{20002}\u{20003}\u{20004}")
    expect(TestAPI.Strings.emoji).toEqual("🤯🐶🍓")
    expect(TestAPI.Strings.emojiMulti).toEqual("👨‍👩‍👧‍👦👍🏿🇺🇸")
});

test('StringEcho', () => {
    expect(TestAPI.Strings.echo(TestAPI.Strings.simple)).toEqual(TestAPI.Strings.simple)
    expect(TestAPI.Strings.echo(TestAPI.Strings.accent)).toEqual(TestAPI.Strings.accent)
    expect(TestAPI.Strings.echo(TestAPI.Strings.chinese)).toEqual(TestAPI.Strings.chinese)
    expect(TestAPI.Strings.echo(TestAPI.Strings.chineseBMP)).toEqual(TestAPI.Strings.chineseBMP)
    expect(TestAPI.Strings.echo(TestAPI.Strings.chineseSIP)).toEqual(TestAPI.Strings.chineseSIP)
    expect(TestAPI.Strings.echo(TestAPI.Strings.emoji)).toEqual(TestAPI.Strings.emoji)
    expect(TestAPI.Strings.echo(TestAPI.Strings.emojiMulti)).toEqual(TestAPI.Strings.emojiMulti)
});

// Bytes Tests

test('BytesValues', () => {
    expect(TestAPI.Bytes.bytes).toEqual([0xDE, 0xAD, 0xBE, 0xEF])
    var buffer = new ArrayBuffer(4)
    var int8View = new Int8Array(buffer)
    int8View[0] = 0x0B
    int8View[1] = 0xAD
    int8View[2] = 0xF0
    int8View[3] = 0x0D
    expect(TestAPI.Bytes.data).toEqual(buffer)
});

test('BytesEcho', () => {
    expect(TestAPI.Bytes.echoBytes(TestAPI.Bytes.bytes)).toEqual(TestAPI.Bytes.bytes)
    expect(TestAPI.Bytes.echoData(TestAPI.Bytes.data)).toEqual(TestAPI.Bytes.data)
});

// Collection Tests

test('CollectionValues', () => {
    expect(TestAPI.Collections.arrayOfInt).toEqual([2,7,3,5,8])
    for (let x of [5, 9, 2, 4, 3]) {
        expect(TestAPI.Collections.setOfInt.has(x)).toBe(true)
    }
    let map = new Map([[1,10],[2,20],[3,30],[4,40],[5,50]])
    expect(sortedEntries(TestAPI.Collections.dictionaryOfIntToInt)).toEqual(sortedEntries(map))
});

test('OptionalCollectionValues', () => {
    expect(TestAPI.Collections.maybeArrayOfInt).toEqual([2,7,3,5,8])
    for (let x of [5, 9, 2, 4, 3]) {
        expect(TestAPI.Collections.maybeSetOfInt!.has(x)).toBe(true)
    }
    let map = new Map([[1,10],[2,20],[3,30],[4,40],[5,50]])
    expect(sortedEntries(TestAPI.Collections.maybeDictionaryOfIntToInt!)).toEqual(sortedEntries(map))
});

test('OptionalCollectionOfOptionalValues', () => {
    expect(TestAPI.Collections.maybeArrayOfMaybeInt).toEqual([undefined, 2,7,3,5,8])
    // TODO: What happened to the nil value on the Swift side?!?
    for (let x of [5, 9, 2, 4, 3]) {
        expect(TestAPI.Collections.maybeSetOfMaybeInt!.has(x)).toBe(true)
    }
    let map = new Map([[undefined,100],[1,10],[2,20],[3,30],[4,40],[5,50]])
    expect(sortedEntries(TestAPI.Collections.maybeDictionaryOfMaybeIntToMaybeInt!)).toEqual(sortedEntries(map))
});

test('FunctionsTakingAndReturningCollectionTypes', () => {
    expect(TestAPI.Collections.echoArrayOfInt(TestAPI.Collections.arrayOfInt)).toEqual(TestAPI.Collections.arrayOfInt)
    // TODO: Dies with: TODO: implement Swift.Set.static func fromNode(_:env:)
    // expect(TestAPI.Collections.echoSetOfInt(TestAPI.Collections.setOfInt)).toEqual(TestAPI.Collections.setOfInt)
    // TODO: Dies with: TODO: implement Swift.Dictionary.static func fromNode(_:env:)
    // expect(TestAPI.Collections.echoDictionaryOfIntToInt(TestAPI.Collections.dictionaryOfIntToInt)).toEqual(TestAPI.Collections.dictionaryOfIntToInt)
});

test('FunctionsTakingAndReturningOptionalCollectionTypes', () => {
    expect(TestAPI.Collections.echoMaybeArrayOfMaybeInt(TestAPI.Collections.maybeArrayOfMaybeInt)).toEqual(TestAPI.Collections.maybeArrayOfMaybeInt!)
    // TODO: Dies with: TODO: implement Swift.Set.static func fromNode(_:env:)
    // expect(TestAPI.Collections.echoMaybeSetOfMaybeInt(TestAPI.Collections.maybeSetOfMaybeInt)).toEqual(TestAPI.Collections.maybeSetOfMaybeInt)
    // TODO: Dies with: TODO: implement Swift.Dictionary.static func fromNode(_:env:)
    // expect(TestAPI.Collections.echoMaybeDictionaryOfMaybeIntToMaybeInt(TestAPI.Collections.maybeDictionaryOfMaybeIntToMaybeInt)).toEqual(TestAPI.Collections.maybeDictionaryOfMaybeIntToMaybeInt)
});

test('FunctionsTakingClosuresWithCollectionTypes', () => {
    // TODO: Fix breakage
    // expect(TestAPI.Collections.collectionMapper(arrayOf(10,20,30)) { (it ?: arrayOf()).map { it * 2 } }).toEqual(arrayListOf(20,40,60))
});

test('ObjectsWithCollectionMembers', () => {
    expect(TestAPI.Collections.CollectionHolder.staticPropery).toEqual([undefined, 2, 7, 3, 5, 8]);
    expect(TestAPI.Collections.CollectionHolder.staticMutablePropery).toEqual([undefined, 2, 7, 3, 5, 8]);
    // TODO: type annotation is buggy
    TestAPI.Collections.CollectionHolder.staticMutablePropery = [100, undefined as any, 200];
    expect(TestAPI.Collections.CollectionHolder.staticMutablePropery).toEqual([100, undefined, 200]);
    let s = TestAPI.Collections.defaultCollectionHolder;
    expect(s).toEqual(TestAPI.Collections.defaultCollectionHolder);
    var map = new Map<boolean, boolean>()
    s.boolDictionary.forEach((value: boolean, key: boolean) => {
        map.set(key, !value);
    });
    s.boolDictionary = map
    expect(s).not.toEqual(TestAPI.Collections.defaultCollectionHolder);
});

// MARK: Function tests
test('GettingSwiftFunctions', () => {
    expect(42).toEqual(TestAPI.Functions.const42())
    expect(3).toEqual(TestAPI.Functions.abs(-3))

    const composed = TestAPI.Functions.intCompose(x => x + 1, x => x * 3)
    expect(10).toEqual(composed(3))
    expect(7).toEqual(composed(2))

    expect(8.5).toEqual(TestAPI.Functions.add3Things(3, 4.5, 1))
    expect(["a", "b", "c", "d"]).toEqual(TestAPI.Functions.makeList("a", "b", "c", "d"))
    expect(84).toEqual(TestAPI.Functions.fifthThing("hi", 1, 1, "...", () => 84)())
    expect(17).toEqual(TestAPI.Functions.sixthThing("hi", 1, 1, "...", () => 84, 17))
});

test('PassingFunctionsToSwift', () => {
    expect("8").toEqual(TestAPI.Functions.exercise0(() => 8))
    expect("3").toEqual(TestAPI.Functions.exercise1((x: number) => Math.abs(x)))
    expect("25").toEqual(TestAPI.Functions.exercise2((f: (_: number) => number, g: (_: number) => number) => (x: number) => f(g(x))))
    expect("7.4").toEqual(TestAPI.Functions.exercise3((a: number, b: number, c: number) => a + b + c))
    expect('["a", "b", "c", "d"]').toEqual(TestAPI.Functions.exercise4((a: string, b: string, c: string, d: string) => [a, b, c, d]))
    expect("83").toEqual(TestAPI.Functions.exercise5((a: any, b: any, c: any, d: any, f: any) => f))
    expect("42").toEqual(TestAPI.Functions.exercise6((a: any, b: any, c: any, d: any, e: any, i: any) => i))
});

test('Exceptions', () => {
    expect(() => TestAPI.Functions.willThrow()).toThrowError(/TheError/)

    const composed = TestAPI.Functions.intCompose((a: number) => a, (_: number) => { throw "ComposeError" })
    expect(() => composed(3)).toThrowError("ComposeError")
});

// MARK: Enum tests

// Currently not supported in TS
// test('testEmptyEnum', () => {
//     expect(() => TestAPI.EmptyEnum.notGoingToHappen()).toThrow()
// });
// function testSimpleEnum() {
//     expect(0xff0000).toEqual(TestAPI.SimpleEnum.red.hex)
//     expect(0x00ff00).toEqual(TestAPI.SimpleEnum.green.hex)
//     expect(0x0000ff).toEqual(TestAPI.SimpleEnum.blue.hex)
//     expect(TestAPI.SimpleEnum.red).toEqual(TestAPI.SimpleEnum.pickAColor(0))
//     expect(TestAPI.SimpleEnum.green).toEqual(TestAPI.SimpleEnum.pickAColor(1))
//     expect(TestAPI.SimpleEnum.blue).toEqual(TestAPI.SimpleEnum.pickAColor(2))
// }
// testSimpleEnum()

test('AssociatedDataEnum', () => {
    const shape1 = (x: number) => new TestAPI.AssociatedDataEnum.Thing(x)
    const shape2 = (x: string, y: string, z: number) => new TestAPI.AssociatedDataEnum.Bar(x, new TestAPI.AssociatedDataEnum.Other(y, z))

    expect(4).toEqual(shape1(4).intValue)
    expect(11).toEqual(shape2("hello", "world", 8).intValue)
    expect(shape1(9)).toEqual(shape1(2).plus(shape2("x", "y", 4)))
    expect(shape2("y", "z", 7)).toEqual(shape2("y", "z", 2).plus(shape1(5)))
});