// Needed to compare maps, because jest was treating the ones generated by NAPI differently somehow
export function sortedEntries<K, V>(map: Map<K, V>): [K, V][] {
    return [...map.entries()].sort()
}
