using System;
using System.Runtime.InteropServices;
using System.Collections.Generic;

namespace Cricut.FishyJoesRuntime {
    public delegate nint EnumDiscriminator(Utilities.UnownedRef obj, out Utilities.CreatedRef exn);

    public class Utilities {
        /// <summary> If true, keep track of every handle allocated by FishyJoes for debugging/testing. Quite slow. </summary>
        public static bool TrackAllocationsDebug = false;
        // LinkedList is inefficient, but it's for debugging anyway
        private static LinkedList<IntPtr> TrackedHandles = new LinkedList<IntPtr>();

        public static int OutstandingHandleCount() {
            return TrackedHandles.Count;
        }

        /// <summary> Prints out every handle allocated by FishyJoes that hasn't been freed. Requires `TrackAllocationsDebug` to be true </summary>
        public static void PrintOutstandingHandles() {
            for (int i = 0; i < 5; i++) {
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }

            Console.WriteLine($"=== Begin live GC handles {TrackedHandles.Count} ===");
            foreach (var ptr in TrackedHandles) {
                var handle = GCHandle.FromIntPtr(ptr);
                Console.WriteLine($"{ptr}: {handle.Target?.GetType().ToString() ?? "<null>"} => {handle.Target?.ToString() ?? "<null>"}");
            }
            Console.WriteLine($"=== End live GC handles {TrackedHandles.Count} ===");
        }

        private static GCHandle Alloc(object? obj) {
            if (obj is not null) {
                var handle = GCHandle.Alloc(obj);
                #if DEBUG
                if (TrackAllocationsDebug) {
                    TrackedHandles.AddLast((IntPtr)handle);
                }
                #endif
                return handle;
            } else {
                return default;
            }
        }

        private static void Free(GCHandle handle) {
            if (handle.IsAllocated) {
                #if DEBUG
                if (TrackAllocationsDebug) {
                    TrackedHandles.Remove((IntPtr)handle);
                }
                #endif
                handle.Free();
            }
        }

        /// <summary> Holds onto a GC Handle for the lifetime of the object </summary>
        public class GCRef : IDisposable {
            public GCRef(object? obj) {
                handle = Alloc(obj);
            }
            private GCHandle handle;

            public UnownedRef ptr {
                get => new UnownedRef((IntPtr)handle);
            }

            ~GCRef() {
                Dispose();
            }

            public void Dispose() {
                Free(handle);
                GC.SuppressFinalize(this);
            }
        }

        /// <summary> Returns the target of a handle, but doesn't affect ownership </summary>
        private static R PeekHandle<R>(IntPtr ptr) {
            if (ptr == IntPtr.Zero) {
                return default(R)!;
            }
            return (R)GCHandle.FromIntPtr(ptr).Target!;
        }

        /// <summary> Returns the target of a handle, and frees the handle. </summary>
        private static R ConsumeHandle<R>(IntPtr ptr) {
            if (ptr == IntPtr.Zero) {
                return default(R)!;
            }
            var handle = GCHandle.FromIntPtr(ptr);
            var ret = (R)handle.Target!;
            Free(handle);
            return ret;
        }

        /// <summary> A reference that is generated by the callee, and owned by the caller </summary>
        [StructLayout(LayoutKind.Sequential)]
        public readonly record struct CreatedRef(IntPtr ptr) {
            public CreatedRef(object? obj): this(PassOwnership(obj)) {}
            public R Consume<R>() => ConsumeHandle<R>(ptr);
            public readonly static CreatedRef Null = new CreatedRef(IntPtr.Zero);
        }

        /// <summary> A reference that is owned by the caller, available for the lifetime of the call </summary>
        [StructLayout(LayoutKind.Sequential)]
        public readonly record struct UnownedRef(IntPtr ptr) {
            public R Peek<R>() => PeekHandle<R>(ptr);
            public readonly static UnownedRef Null = new UnownedRef(IntPtr.Zero);
        }

        /// <summary> A reference that becomes owned by the callee </summary>
        [StructLayout(LayoutKind.Sequential)]
        public readonly record struct ConsumedRef {
            internal readonly IntPtr __ptr;

            public ConsumedRef(IntPtr ptr) {
                __ptr = ptr;
            }
            public R Consume<R>() => ConsumeHandle<R>(__ptr);
        }

        private static IntPtr PassOwnership(object? obj) {
            if (obj == null) {
                return IntPtr.Zero ;
             } else {
                var ptr = (IntPtr)Alloc(obj);
                return ptr;
            }
        }

        public delegate R CheckBody<R>(out CreatedRef exn);
        public delegate void CheckVoidBody(out CreatedRef exn);

        /// <summary> Passes an exception out-parameter for body to report any errors, If set to non-null, it will then throw the exception.
        /// `body` passes ownership of `exn` to `Check` </summary>
        public static R Check<R>(CheckBody<R> body) {
            var exn = CreatedRef.Null;
            var result = body(out exn);
            if (exn.ptr != IntPtr.Zero) {
                throw exn.Consume<Exception>();
            }
            return result;
        }

        /// Passes an exception out-parameter for body to report any errors, If set to non-null, it will then throw the exception.
        /// `body` passes ownership of `exn` to `Check`
        public static void Check(CheckVoidBody body) {
            var exn = CreatedRef.Null;
            body(out exn);
            if (exn.ptr != IntPtr.Zero) {
                throw exn.Consume<Exception>();
            }
        }

        /// Converts any thrown exceptions in `body` into setting of out parameter `exn`. Caller is responsible for ownership of `exn`
        public static R? Catching<R>(out CreatedRef exn, Func<R> body) {
            try {
                var ret = body();
                exn = CreatedRef.Null;
                return ret;
            } catch (Exception e) {
                exn = new CreatedRef(e);
                return default(R);
            }
        }

        /// Converts any thrown exceptions in `body` into setting of out parameter `exn`. Caller is responsible for ownership of `exn`
        public static void Catching(out CreatedRef exn, Action body) {
            try {
                body();
                exn = CreatedRef.Null;
            } catch (Exception e) {
                exn = new CreatedRef(e);
            }
        }

        private static HashSet<string> oncedIdentifiers = new HashSet<string>();
        public static void Once(string identifier, Action action) {
            if (oncedIdentifiers.Contains(identifier)) { return; }
            oncedIdentifiers.Add(identifier);
            action();
        }

        public static int Hash<T>(IEnumerable<T> components) {
            var hash = 0;
            foreach (var obj in components) {
                hash = Tuple.Create(hash, obj).GetHashCode();
            }
            return hash;
        }
    }
}
