import 'dart:ffi' as ffi;
import 'package:ffi/ffi.dart' as ffi;
import './dart_api_dl.dart';

final class _PersistentHandleStruct extends ffi.Opaque {}

typedef GCHandle = ffi.Pointer<_PersistentHandleStruct>;

final class _CreatedRef extends ffi.Opaque {}

final class _UnownedRef extends ffi.Opaque {}

final class _ConsumedRef extends ffi.Opaque {}

/// <summary> A reference that is generated by the callee, and owned by the caller </summary>
typedef CreatedRef = ffi.Pointer<_CreatedRef>;

/// <summary> A reference that is owned by the caller, available for the lifetime of the call </summary>
typedef UnownedRef = ffi.Pointer<_UnownedRef>;

/// <summary> A reference that becomes owned by the callee </summary>
typedef ConsumedRef = ffi.Pointer<_ConsumedRef>;

typedef OutCreatedRef = ffi.Pointer<CreatedRef>;

final class _Env extends ffi.Opaque {}

typedef Env = ffi.Pointer<_Env>;

class _GCWhisperer {
  static final _handleFromPersistent = DartApiDL.shared.handleFromPersistentPtr
      .cast<ffi.NativeFunction<ffi.Handle Function(GCHandle)>>()
      .asFunction<Object Function(GCHandle)>();
  static final _newPersistentHandle = DartApiDL.shared.newPersistentHandlePtr
      .cast<ffi.NativeFunction<GCHandle Function(ffi.Handle)>>()
      .asFunction<GCHandle Function(Object)>();
  static final _deletePersistentHandle = DartApiDL.shared.deletePersistentHandlePtr
      .cast<ffi.NativeFunction<ffi.Void Function(GCHandle)>>()
      .asFunction<void Function(GCHandle)>();

  static Object? handleFromPersistent(GCHandle handle) {
    return handle.address == 0 ? null : _handleFromPersistent(handle);
  }

  static GCHandle newPersistentHandle<T extends Object>(T object) {
    return _newPersistentHandle(object);
  }

  static void deletePersistentHandle(GCHandle handle) {
    if (handle.address != 0) {
      _deletePersistentHandle(handle);
    }
  }
}

GCHandle _alloc(Object? obj) {
  if (obj == null) {
    return GCHandle.fromAddress(0);
  } else {
    return _GCWhisperer.newPersistentHandle(obj);
  }
}

R _peekHandle<R>(GCHandle ptr) {
  return _GCWhisperer.handleFromPersistent(ptr) as R;
}

Object? _consumeHandle(GCHandle ptr) {
  final ret = _peekHandle<Object?>(ptr);
  _GCWhisperer.deletePersistentHandle(ptr);
  return ret;
}

CreatedRef createRef(Object? obj) {
  return _alloc(obj).cast();
}

ConsumedRef createConsumedRef(Object? obj) {
  return _alloc(obj).cast();
}

R peekRef<R>(UnownedRef ref) => _peekHandle<R>(ref.cast());
R consumeRef<R>(ConsumedRef ref) => _consumeHandle(ref.cast()) as R;
R consumeCreatedRef<R>(CreatedRef ref) {
  final z = _consumeHandle(ref.cast());
  // print("$z: ${z.runtimeType} is $R: ${z is R}");
  return z as R;
}

R? catching<R>(OutCreatedRef intoExn, R Function() body) {
  try {
    return body();
  } catch (e) {
    intoExn.value = createRef(e);
    return null;
  }
}

ffi.Pointer<R> catchingRef<R extends ffi.NativeType>(OutCreatedRef intoExn, ffi.Pointer<R> Function() body) {
  return catching(intoExn, body) ?? ffi.Pointer<R>.fromAddress(0);
}

R check<R>(R Function(OutCreatedRef) body) {
  final exnPtr = ffi.calloc<CreatedRef>();
  final result = body(exnPtr);
  final exn = consumeCreatedRef<Object?>(exnPtr.value);
  ffi.calloc.free(exnPtr);
  if (exn != null) {
    throw exn;
  }
  return result;
}

/// Holds onto a GC Handle for the lifetime of the object
class GCRef implements ffi.Finalizable {
  static final _finalizer = ffi.NativeFinalizer(DartApiDL.shared.deletePersistentHandlePtr.cast());

  GCHandle _handle;

  GCRef(Object? obj) : _handle = _alloc(obj) {
    final handle = _handle;
    if (handle.address != 0) {
      _finalizer.attach(this, handle.cast(), detach: this);
    }
  }

  UnownedRef get ptr {
    return _handle.cast();
  }

  void dispose() {
    final handle = _handle;
    if (handle.address != 0) {
      _finalizer.detach(this);
      _GCWhisperer.deletePersistentHandle(handle);
      _handle = GCHandle.fromAddress(0);
    }
  }

  static R using<R>(Object? obj, R Function(GCRef) body) {
    final ref = GCRef(obj);
    try {
      return body(ref);
    } finally {
      ref.dispose();
    }
  }
}

typedef EnumDiscriminator = int Function(UnownedRef obj, OutCreatedRef exn);
typedef EnumDiscriminatorTag = ffi.Int Function(UnownedRef obj, OutCreatedRef exn);
