import Foundation

// Generated by FishyJoes for `AttributedSubstring.init()`
let java_AttributedSubstring_createEmpty: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedSubstring.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedSubstring.toJava(
            AttributedSubstring(
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedSubstring.substring(for range: Range<Index>)`
let java_AttributedSubstring_substringForRange: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    RangeConverter<AttributedString.Index>.CType
) -> AttributedSubstring.CType = { _javaEnv, _javaThis, range in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedSubstring.toJava(
            AttributedSubstring.fromJava(_javaThis, env: _javaEnv)[
                try RangeConverter<AttributedString.Index>.fromJava(range, env: _javaEnv)
            ],
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedSubstring.setAttributes(_ attributes: AttributeContainer)`
let java_AttributedSubstring_setAttributes: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributeContainer.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, attributes in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedSubstring.fromJava(_javaThis, env: _javaEnv)
        return try AttributedSubstring.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.setAttributes(
                    try AttributeContainer.fromJava(attributes, env: _javaEnv)
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedSubstring.mergeAttributes(_ attributes: AttributeContainer, mergePolicy: AttributedString.AttributeMergePolicy? = nil)`
let java_AttributedSubstring_mergeAttributes: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributeContainer.CType,
    OptionalConverter<AttributedString.AttributeMergePolicy>.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, attributes, mergePolicy in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedSubstring.fromJava(_javaThis, env: _javaEnv)
        return try AttributedSubstring.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.mergeAttributes(
                    try AttributeContainer.fromJava(attributes, env: _javaEnv),
                    mergePolicy: try OptionalConverter<AttributedString.AttributeMergePolicy>.fromJava(mergePolicy, env: _javaEnv) ?? .keepNew
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedSubstring.replaceAttributes(_ attributes: AttributeContainer, with others: AttributeContainer)`
let java_AttributedSubstring_replaceAttributes: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributeContainer.CType,
    AttributeContainer.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, attributes, others in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedSubstring.fromJava(_javaThis, env: _javaEnv)
        return try AttributedSubstring.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.replaceAttributes(
                    try AttributeContainer.fromJava(attributes, env: _javaEnv),
                    with: try AttributeContainer.fromJava(others, env: _javaEnv)
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedSubstring.base`
let java_get_AttributedSubstring_base: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.toJava(AttributedSubstring.fromJava(_javaThis, env: _javaEnv).base, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedSubstring.startIndex`
let java_get_AttributedSubstring_startIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Index.toJava(AttributedSubstring.fromJava(_javaThis, env: _javaEnv).startIndex, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedSubstring.endIndex`
let java_get_AttributedSubstring_endIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Index.toJava(AttributedSubstring.fromJava(_javaThis, env: _javaEnv).endIndex, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedSubstring.unicodeScalars`
let java_get_AttributedSubstring_unicodeScalars: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.UnicodeScalarView.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.UnicodeScalarView.toJava(AttributedSubstring.fromJava(_javaThis, env: _javaEnv).unicodeScalars, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedSubstring.characters`
let java_get_AttributedSubstring_characters: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.CharacterView.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.CharacterView.toJava(AttributedSubstring.fromJava(_javaThis, env: _javaEnv).characters, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedSubstring.runs`
let java_get_AttributedSubstring_runs: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Runs.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Runs.toJava(AttributedSubstring.fromJava(_javaThis, env: _javaEnv).runs, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedSubstring.substring`
let java_get_AttributedSubstring_substring: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedSubstring.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        let s = try AttributedSubstring.fromJava(_javaThis, env: _javaEnv)
        return try AttributedSubstring.toJava(s[s.startIndex..<s.endIndex], env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedSubstring.string`
let java_get_AttributedSubstring_string: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> String.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        let s = try AttributedSubstring.fromJava(_javaThis, env: _javaEnv)
        return try String.toJava(String(s.characters), env: _javaEnv)
    }
}
