import Foundation

// Generated by FishyJoes for `AttributedString.CharacterView.index(before i: Index)`
let java_AttributedString_CharacterView_indexBefore: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Index.CType
) -> AttributedString.Index.CType = { _javaEnv, _javaThis, i in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Index.toJava(
            AttributedString.CharacterView.fromJava(_javaThis, env: _javaEnv).index(
                before: try AttributedString.Index.fromJava(i, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.CharacterView.index(after i: Index)`
let java_AttributedString_CharacterView_indexAfter: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Index.CType
) -> AttributedString.Index.CType = { _javaEnv, _javaThis, i in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Index.toJava(
            AttributedString.CharacterView.fromJava(_javaThis, env: _javaEnv).index(
                after: try AttributedString.Index.fromJava(i, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.CharacterView.element(at index: Index)`
let java_AttributedString_CharacterView_elementAt: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Index.CType
) -> Swift.String.CType = { _javaEnv, _javaThis, index in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try Swift.String.toJava(
            String(
                AttributedString.CharacterView.fromJava(_javaThis, env: _javaEnv)[
                    try AttributedString.Index.fromJava(index, env: _javaEnv)
                ]
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.CharacterView.replaceSubrange<C>(_ subrange: Range<Index>, with newElements: C)`
let java_AttributedString_CharacterView_replaceSubrange: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    RangeConverter<AttributedString.Index>.CType,
    ArrayConverter<Swift.String>.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, subrange, newElements in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.CharacterView.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.CharacterView.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.replaceSubrange(
                    try RangeConverter<AttributedString.Index>.fromJava(subrange, env: _javaEnv),
                    with: try ArrayConverter<Swift.String>.fromJava(newElements, env: _javaEnv).compactMap { Character($0) }
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.CharacterView.startIndex`
let java_get_AttributedString_CharacterView_startIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Index.toJava(AttributedString.CharacterView.fromJava(_javaThis, env: _javaEnv).startIndex, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.CharacterView.endIndex`
let java_get_AttributedString_CharacterView_endIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Index.toJava(AttributedString.CharacterView.fromJava(_javaThis, env: _javaEnv).endIndex, env: _javaEnv)
    }
}
