import Foundation

// Generated by FishyJoes for `AttributeContainer.init()`
let java_AttributeContainer_createEmpty: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributeContainer.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributeContainer.toJava(
            AttributeContainer(
            ),
            env: _javaEnv
        )
    }
}
