import Foundation

// Generated by FishyJoes for `AttributedString.Runs.index(before i: Index)`
let java_AttributedString_Runs_indexBefore: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Runs.Index.CType
) -> AttributedString.Runs.Index.CType = { _javaEnv, _javaThis, i in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Runs.Index.toJava(
            AttributedString.Runs.fromJava(_javaThis, env: _javaEnv).index(
                before: try AttributedString.Runs.Index.fromJava(i, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.Runs.index(after i: Index)`
let java_AttributedString_Runs_indexAfter: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Runs.Index.CType
) -> AttributedString.Runs.Index.CType = { _javaEnv, _javaThis, i in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Runs.Index.toJava(
            AttributedString.Runs.fromJava(_javaThis, env: _javaEnv).index(
                after: try AttributedString.Runs.Index.fromJava(i, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.Runs.element(at index: Index)`
let java_AttributedString_Runs_elementAt: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Runs.Index.CType
) -> AttributedString.Runs.Run.CType = { _javaEnv, _javaThis, index in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Runs.Run.toJava(
            AttributedString.Runs.fromJava(_javaThis, env: _javaEnv)[
                try AttributedString.Runs.Index.fromJava(index, env: _javaEnv)
            ],
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.Runs.element(at index: AttributedString.Index)`
let java_AttributedString_Runs_elementAtPosition: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Index.CType
) -> AttributedString.Runs.Run.CType = { _javaEnv, _javaThis, index in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Runs.Run.toJava(
            AttributedString.Runs.fromJava(_javaThis, env: _javaEnv)[
                try AttributedString.Index.fromJava(index, env: _javaEnv)
            ],
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.Runs.startIndex`
let java_get_AttributedString_Runs_startIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Runs.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Runs.Index.toJava(AttributedString.Runs.fromJava(_javaThis, env: _javaEnv).startIndex, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.Runs.endIndex`
let java_get_AttributedString_Runs_endIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Runs.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Runs.Index.toJava(AttributedString.Runs.fromJava(_javaThis, env: _javaEnv).endIndex, env: _javaEnv)
    }
}
