import Foundation

// Generated by FishyJoes for `AttributedString.UnicodeScalarView.index(before i: Index)`
let java_AttributedString_UnicodeScalarView_indexBefore: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Index.CType
) -> AttributedString.Index.CType = { _javaEnv, _javaThis, i in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Index.toJava(
            AttributedString.UnicodeScalarView.fromJava(_javaThis, env: _javaEnv).index(
                before: try AttributedString.Index.fromJava(i, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.UnicodeScalarView.index(after i: Index)`
let java_AttributedString_UnicodeScalarView_indexAfter: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Index.CType
) -> AttributedString.Index.CType = { _javaEnv, _javaThis, i in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Index.toJava(
            AttributedString.UnicodeScalarView.fromJava(_javaThis, env: _javaEnv).index(
                after: try AttributedString.Index.fromJava(i, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.UnicodeScalarView.index(_ i: Index, offsetBy distance: Int)`
let java_AttributedString_UnicodeScalarView_indexOffsetByDistance: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Index.CType,
    Int.CType
) -> AttributedString.Index.CType = { _javaEnv, _javaThis, i, distance in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.Index.toJava(
            AttributedString.UnicodeScalarView.fromJava(_javaThis, env: _javaEnv).index(
                try AttributedString.Index.fromJava(i, env: _javaEnv),
                offsetBy: try Int.fromJava(distance, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.UnicodeScalarView.element(at index: Index)`
let java_AttributedString_UnicodeScalarView_elementAt: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.Index.CType
) -> UInt32.CType = { _javaEnv, _javaThis, index in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try UInt32.toJava(
            AttributedString.UnicodeScalarView.fromJava(_javaThis, env: _javaEnv)[
                try AttributedString.Index.fromJava(index, env: _javaEnv)
            ].value,
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.UnicodeScalarView.replaceSubrange<C>(_ subrange: Range<Index>, with newElements: C)`
let java_AttributedString_UnicodeScalarView_replaceSubrange: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    RangeConverter<AttributedString.Index>.CType,
    ArrayConverter<UInt32>.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, subrange, newElements in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.UnicodeScalarView.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.UnicodeScalarView.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.replaceSubrange(
                    try RangeConverter<AttributedString.Index>.fromJava(subrange, env: _javaEnv),
                    with: try ArrayConverter<UInt32>.fromJava(newElements, env: _javaEnv).compactMap { UnicodeScalar(Int($0)) }
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.UnicodeScalarView.startIndex`
let java_get_AttributedString_UnicodeScalarView_startIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Index.toJava(AttributedString.UnicodeScalarView.fromJava(_javaThis, env: _javaEnv).startIndex, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.UnicodeScalarView.endIndex`
let java_get_AttributedString_UnicodeScalarView_endIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Index.toJava(AttributedString.UnicodeScalarView.fromJava(_javaThis, env: _javaEnv).endIndex, env: _javaEnv)
    }
}
