import Foundation

// Generated by FishyJoes for `AttributedString.init()`
let java_AttributedString_createEmpty: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.toJava(
            AttributedString(
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.init(_ string: String, attributes: AttributeContainer? = nil)`
let java_AttributedString_create: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    Swift.String.CType,
    OptionalConverter<AttributeContainer>.CType
) -> AttributedString.CType = { _javaEnv, _javaThis, string, attributes in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.toJava(
            AttributedString(
                try Swift.String.fromJava(string, env: _javaEnv),
                attributes: try OptionalConverter<AttributeContainer>.fromJava(attributes, env: _javaEnv) ?? .init()
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.init(_ substring: AttributedSubstring)`
let java_AttributedString_createFromSubstring: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedSubstring.CType
) -> AttributedString.CType = { _javaEnv, _javaThis, substring in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedString.toJava(
            AttributedString(
                try AttributedSubstring.fromJava(substring, env: _javaEnv)
            ),
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.substring(for range: Range<Index>)`
let java_AttributedString_substringForRange: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    RangeConverter<AttributedString.Index>.CType
) -> AttributedSubstring.CType = { _javaEnv, _javaThis, range in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        return try AttributedSubstring.toJava(
            AttributedString.fromJava(_javaThis, env: _javaEnv)[
                try RangeConverter<AttributedString.Index>.fromJava(range, env: _javaEnv)
            ],
            env: _javaEnv
        )
    }
}

// Generated by FishyJoes for `AttributedString.append(_ s: Self)`
let java_AttributedString_append: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, s in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.append(
                    try AttributedString.fromJava(s, env: _javaEnv)
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.insert(_ s: Self, at index: Index)`
let java_AttributedString_insert: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributedString.CType,
    AttributedString.Index.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, s, index in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.insert(
                    try AttributedString.fromJava(s, env: _javaEnv),
                    at: try AttributedString.Index.fromJava(index, env: _javaEnv)
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.removeSubrange(_ range: Range<Index>)`
let java_AttributedString_removeSubrange: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    RangeConverter<AttributedString.Index>.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, range in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.removeSubrange(
                    try RangeConverter<AttributedString.Index>.fromJava(range, env: _javaEnv)
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.replaceSubrange(_ range: Range<Index>, with s: Self)`
let java_AttributedString_replaceSubrange: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    RangeConverter<AttributedString.Index>.CType,
    AttributedString.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, range, s in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.replaceSubrange(
                    try RangeConverter<AttributedString.Index>.fromJava(range, env: _javaEnv),
                    with: try AttributedString.fromJava(s, env: _javaEnv)
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.setAttributes(_ attributes: AttributeContainer)`
let java_AttributedString_setAttributes: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributeContainer.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, attributes in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.setAttributes(
                    try AttributeContainer.fromJava(attributes, env: _javaEnv)
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.mergeAttributes(_ attributes: AttributeContainer, mergePolicy: AttributedString.AttributeMergePolicy? = nil)`
let java_AttributedString_mergeAttributes: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributeContainer.CType,
    OptionalConverter<AttributedString.AttributeMergePolicy>.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, attributes, mergePolicy in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.mergeAttributes(
                    try AttributeContainer.fromJava(attributes, env: _javaEnv),
                    mergePolicy: try OptionalConverter<AttributedString.AttributeMergePolicy>.fromJava(mergePolicy, env: _javaEnv) ?? .keepNew
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.replaceAttributes(_ attributes: AttributeContainer, with others: AttributeContainer)`
let java_AttributedString_replaceAttributes: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject,
    AttributeContainer.CType,
    AttributeContainer.CType
) -> VoidConverter.CType = { _javaEnv, _javaThis, attributes, others in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        var mutatingSelf = try AttributedString.fromJava(_javaThis, env: _javaEnv)
        return try AttributedString.mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in
            return try VoidConverter.toJava(
                mutatingSelf.replaceAttributes(
                    try AttributeContainer.fromJava(attributes, env: _javaEnv),
                    with: try AttributeContainer.fromJava(others, env: _javaEnv)
                ),
                env: _javaEnv
            )
        }
    }
}

// Generated by FishyJoes for `AttributedString.startIndex`
let java_get_AttributedString_startIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Index.toJava(AttributedString.fromJava(_javaThis, env: _javaEnv).startIndex, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.endIndex`
let java_get_AttributedString_endIndex: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Index.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Index.toJava(AttributedString.fromJava(_javaThis, env: _javaEnv).endIndex, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.unicodeScalars`
let java_get_AttributedString_unicodeScalars: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.UnicodeScalarView.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.UnicodeScalarView.toJava(AttributedString.fromJava(_javaThis, env: _javaEnv).unicodeScalars, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.characters`
let java_get_AttributedString_characters: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.CharacterView.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.CharacterView.toJava(AttributedString.fromJava(_javaThis, env: _javaEnv).characters, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.runs`
let java_get_AttributedString_runs: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedString.Runs.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributedString.Runs.toJava(AttributedString.fromJava(_javaThis, env: _javaEnv).runs, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.substring`
let java_get_AttributedString_substring: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributedSubstring.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        let s = try AttributedString.fromJava(_javaThis, env: _javaEnv)
        return try AttributedSubstring.toJava(s[s.startIndex..<s.endIndex], env: _javaEnv)
    }
}
