import Foundation

// Generated by FishyJoes for `AttributedString.Runs.Run.range`
let java_get_AttributedString_Runs_Run_range: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> RangeConverter<AttributedString.Index>.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try RangeConverter<AttributedString.Index>.toJava(AttributedString.Runs.Run.fromJava(_javaThis, env: _javaEnv).range, env: _javaEnv)
    }
}

// Generated by FishyJoes for `AttributedString.Runs.Run.attributes`
let java_get_AttributedString_Runs_Run_attributes: @convention(c) (
    UnsafeMutablePointer<JNIEnv?>,
    jobject
) -> AttributeContainer.CType = { _javaEnv, _javaThis in
    FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in
        try AttributeContainer.toJava(AttributedString.Runs.Run.fromJava(_javaThis, env: _javaEnv).attributes, env: _javaEnv)
    }
}
