import Foundation
import SourceryRuntime

final class CSharpTranslator: Translator {
    required init() {}

    func translate(method: Method, context: FishyJoesContext) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            let resolved = context.resolve(type: selfType)
            containingNamespace = resolved.sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(resolved.converterType.name).fromCSharp(_cSharpThis)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        var formals: [(name: String, type: String)] = []
        if !method.isStatic {
            formals.append((name: "_cSharpThis", type: "csObject"))
        }
        formals.append(
            contentsOf: method.parameters.map { parameter in
                let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                return (name: parameter.name, type: resolved.converterType.name + ".CType")
            }
        )
        formals.append((name: "_exn", type: "csOutExn"))

        let fragment = context.swiftFragment(
            "CSharpInterface/\(containingNamespace)+cSharpMethods.swift",
            additionalImports: ["Foundation", "FishyJoesCSharpRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        let returnType = context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides)
        let returnSignature = "\(returnType.converterType.name).CType"

        let cMethod = "__cs_\(containingNamespace)_\(exportAnnotation.name)".mangled
        fragment.output("@_cdecl(\"\(cMethod)\")")
        fragment.outputBlock("private func \(cMethod)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(returnSignature) {") {
            fragment.outputBlock("FishyJoesCSharpRuntime.Env.catching(to: _exn) {") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"

                // let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })
                var mutateBlock: (() -> Void) -> Void = { $0() }
                if method.isMutating {
                    fragment.output("var mutatingSelf = try \(selfExpression)")
                    mutateBlock = { body in
                        fragment.outputBlock("return try \(containingNamespace).mutateCSharp(_cSharpThis) { mutatingSelf in", closeWith: "}") {
                            body()
                        }
                    }
                    selfExpression = "mutatingSelf"
                }

                mutateBlock {
                    fragment.outputBlock("return try \(returnType.converterType.name).toCSharp(") {
                        fragment.outputBlock("\(selfExpression)\(callName)(") {
                            fragment.outputMap(method.parameters, separator: ",") { formal in
                                let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                return (formal.label.map { "\($0): " } ?? "") +
                                    "try \(resolved.converterType.name).fromCSharp(\(formal.name))"
                            }
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func translate(variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {
            return []
        }
        let cSharpName = exportAnnotation.name
        let cSharpGetName = "__cs_\(exportAnnotation.kind == .asMethod ? "" : "get_")\(cSharpName)"
        let cSharpSetName = "__cs_set_\(cSharpName)"

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace).fromCSharp(_cSharpThis)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        let fragment = context.swiftFragment(
            "CSharpInterface/\(containingNamespace)+cSharpdecl.swift",
            additionalImports: ["Foundation", "FishyJoesCSharpRuntime"]
        )

        let resolved = context.resolve(type: variable.typeName.better)
        let converterName = resolved.converterType.name
        let cType = "\(converterName).CType"

        // Getter
        let formals = (variable.isStatic ? [] : [(name: "_cSharpThis", type: "csObject")]) + [
            (name: "_exn", type: "csOutExn"),
        ]

        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        fragment.output("@_cdecl(\"\(cSharpGetName)\")")
        fragment.outputBlock("func \(cSharpGetName)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(cType) = {") {
            fragment.outputBlock("FishyJoesCSharpRuntime.Env.catching(to: _exn) {") {
                fragment.output("try \(converterName).toCSharp(\(selfExpression).\(variable.name))")
            }
        }

        // Setter
        if variable.isMutable, variable.accessLevel.write == .public {
            let formals = (variable.isStatic ? [] : [(name: "_cSharpThis", type: "csObject")]) + [
                (name: "newValue", type: cType),
                (name: "_exn", type: "csOutExn"),
            ]

            fragment.output("@_cdecl(\"\(cSharpSetName)\")")
            fragment.outputBlock("func \(cSharpSetName)(", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",", \.type)
            }
            fragment.outputBlock(" -> Void = {") {
                fragment.outputBlock("FishyJoesCSharpRuntime.Env.catching(to: _exn) {") {
                    if variable.isStatic {
                        fragment.output("\(selfExpression).\(variable.name) = try \(converterName).fromCSharp(newValue)")
                    } else {
                        fragment.outputBlock("try \(containingNamespace).mutateCSharp(_cSharpThis) { value in", closeWith: "}") {
                            fragment.output("value.\(variable.name) = try \(converterName).fromCSharp(newValue)")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func setupFragments(context: FishyJoesContext, generatedTypes: Set<BetterType>) -> [SourceFragment] {
        let fragment = context.cSharpFragment("TypeSetup.cs")
        let uniqueBaseTypes = Dictionary<String, [TranslatedType]>(
            generatedTypes.map { type in
                let resolved = context.resolve(type: type)
                return (resolved.converterType.genericBaseName.mangledName, [resolved])
            },
            uniquingKeysWith: (+)
        )
            .mapValues { types in types.sorted { "\($0)" < "\($1)" } }
            .sorted { $0.key < $1.key }

        fragment.outputBlock("namespace Cricut.\(context.module.name) {") {
            fragment.outputBlock("public class _TypeSetup {") {
                var initializerWriters: [() -> Void] = []
                for (baseName, resolveds) in uniqueBaseTypes {
                    fragment.output("[DllImport(\"\(context.module.name)-c-sharp.dylib\")]")
                    let setupName = "\(baseName)Setup"
                    fragment.outputBlock("static extern void \(setupName)(", closeWith: ");") {
                        guard let setupParams = resolveds.first?.cSharpSetupParameters,
                              Set(resolveds.map(\.cSharpSetupParameters)).count == 1
                        else {
                            fatalErr("setup parameters must exist and be unique for \(baseName)")
                        }

                        for param in setupParams {
                            fragment.output("\(param.type) \(param.name),")
                        }
                        fragment.output("out IntPtr _exn")

                        initializerWriters.append {
                            fragment.output("Console.WriteLine(\"setting up \(baseName)...\");")
                            fragment.outputBlock("Utilities.Check((out IntPtr exn) => \(setupName)(", closeWith: "));") {
                                for param in setupParams {
                                    fragment.output("\(param.value),")
                                }
                                fragment.output("out exn")
                            }
                        }
                    }
                    fragment.blankLine()
                }

                fragment.output("public static void _ensureLoaded() {}")
                fragment.blankLine()

                fragment.outputBlock("static _TypeSetup() {") {
                    for dependency in context.module.dependencies {
                        fragment.output("// There's no explicit way to call the static constructor, so do this instead")
                        fragment.output("\(dependency)._ensureLoaded()")
                    }
                    for writer in initializerWriters {
                        writer()
                    }
                }
            }
        }

        let exportFragment = SourceFragment(sourceryDestination: "file:CSharpInterface/@_exported.swift")
        exportFragment.output("@_exported import \(context.module.name)")
        for dependency in context.module.dependencies {
            exportFragment.output("@_exported import \(dependency)_CSharpInterface")
        }

        return [fragment, exportFragment]
    }

    func cSharp(method: Method, of type: TranslatedType, context: FishyJoesContext) -> CSharpClass.MethodOrVariable? {
        let exportAnnotation = method.exportAnnotation
        var omitParameters = Set(exportAnnotation.omitParameters)
        var parameters: [(labelComment: String?, name: String, CSharpClass.CSType)] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            var label: String?
            if let swiftLabel = parameter.label, swiftLabel != parameter.name {
                label = swiftLabel
            }
            parameters.append((label, parameter.name, resolved.cSharpType))
        }

        return .method(
            CSharpClass.Method(
                documentation: method.documentation,
                isStatic: method.isStatic,
                isOverride: method.exportAnnotation.isOverride,
                name: exportAnnotation.name,
                mangledName: "\(type.mangledName)_\(exportAnnotation.name.mangled)",
                parameters: parameters,
                returnType: context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).cSharpType,
                body: nil
            )
        )
    }

    func cSharp(field: Variable, of type: TranslatedType, context: FishyJoesContext, useNativeName: Bool = false) -> CSharpClass.MethodOrVariable? {
        let csName: String
        var asMethod = false

        if useNativeName {
            guard field.exportAnnotation == nil else {
                fatalErr("field \(field.name) should not be annotated, as it's in a type being exported memberwise")
            }
            csName = field.name
        } else {
            guard let exportAnnotation = field.exportAnnotation else {
                return nil
            }
            asMethod = exportAnnotation.kind == .asMethod
            csName = exportAnnotation.name
        }
        let resolved = context.resolve(type: field.typeName.better)
        if asMethod {
            return .method(
                CSharpClass.Method(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    name: csName,
                    mangledName: "\(type.mangledName)_\(csName.mangled)",
                    parameters: [],
                    returnType: resolved.cSharpType,
                    body: nil
                )
            )
        } else {
            return .variable(
                CSharpClass.Variable(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    readOnly: !field.isMutable,
                    name: csName,
                    mangledName: "\(type.mangledName)_\(csName.mangled)",
                    type: resolved.cSharpType
                )
            )
        }
    }
}
