import Foundation
import SourceryRuntime

final class CSharpTranslator: Translator {
    required init() {}

    func translate(method: Method, context: FishyJoesContext) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            let resolved = context.resolve(type: selfType)
            containingNamespace = resolved.sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(resolved.converterType.name).peekCSharp(_cSharpThis)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        var formals: [(name: String, type: String)] = []
        if !method.isStatic {
            formals.append((name: "_cSharpThis", type: "csObject"))
        }
        formals.append(
            contentsOf: method.parameters.map { parameter in
                let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                return (name: parameter.name, type: resolved.converterType.name + ".CType")
            }
        )
        formals.append((name: "_exn", type: "csOutExn"))

        let fragment = context.swiftFragment(
            "CSharpInterface/\(containingNamespace)+cSharp-methods.swift",
            additionalImports: ["Foundation", "FishyJoesCSharpRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        let returnType = context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides)
        let returnSignature = "\(returnType.converterType.name).CType"

        let cMethod = "__cs_\(containingNamespace)_\(exportAnnotation.name)".mangled
        if let deprecation = method.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.output("@_cdecl(\"\(cMethod)\")")
        fragment.outputBlock("public func \(cMethod)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(returnSignature) {") {
            fragment.outputBlock("FishyJoesCSharpRuntime.Env.catching(to: _exn) {") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"

                var mutateBlock: (() -> Void) -> Void = { $0() }
                if method.isMutating {
                    mutateBlock = { body in
                        fragment.outputBlock("return try \(containingNamespace).mutateCSharp(_cSharpThis) { mutatingSelf in", closeWith: "}") {
                            body()
                        }
                    }
                    selfExpression = "mutatingSelf"
                }

                mutateBlock {
                    fragment.outputBlock(exportAnnotation.noReturn ? "try (" : "return try \(returnType.converterType.name).toCSharp(") {
                        fragment.outputBlock("\(selfExpression)\(callName)(") {
                            fragment.outputMap(method.parameters, separator: ",") { formal in
                                let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                return (formal.label.map { "\($0): " } ?? "") +
                                    "try \(resolved.converterType.name).peekCSharp(\(formal.name))"
                            }
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func translate(variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {
            return []
        }
        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace).peekCSharp(_cSharpThis)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        let cSharpName = upperCaseFirst(exportAnnotation.cSharpName)
        let cSharpGetName = "__cs_\(exportAnnotation.kind == .asMethod ? "" : "get_")\(containingNamespace)_\(cSharpName)".mangled
        let cSharpSetName = "__cs_set_\(containingNamespace)_\(cSharpName)".mangled

        let fragment = context.swiftFragment(
            "CSharpInterface/\(containingNamespace)+cSharp-methods.swift",
            additionalImports: ["Foundation", "FishyJoesCSharpRuntime"]
        )

        let resolved = context.resolve(type: variable.typeName.better)
        let converterName = resolved.converterType.name
        let cType = "\(converterName).CType"

        // Getter
        let formals = (variable.isStatic ? [] : [(name: "_cSharpThis", type: "csObject")]) + [
            (name: "_exn", type: "csOutExn"),
        ]

        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        if let deprecation = variable.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.output("@_cdecl(\"\(cSharpGetName)\")")
        fragment.outputBlock("public func \(cSharpGetName)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(cType) {") {
            fragment.outputBlock("FishyJoesCSharpRuntime.Env.catching(to: _exn) {") {
                fragment.output("try \(converterName).toCSharp(\(selfExpression).\(variable.name))")
            }
        }

        // Setter
        if variable.isMutable, variable.accessLevel.write == .public {
            let formals = (variable.isStatic ? [] : [(name: "_cSharpThis", type: "csObject")]) + [
                (name: "newValue", type: cType),
                (name: "_exn", type: "csOutExn"),
            ]

            if let deprecation = variable.deprecation {
                fragment.output(deprecation.swiftDeprecation)
            }
            fragment.output("@_cdecl(\"\(cSharpSetName)\")")
            fragment.outputBlock("public func \(cSharpSetName)(", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",") { formal in
                    "\(formal.name): \(formal.type)"
                }
            }
            fragment.outputBlock(" {") {
                fragment.outputBlock("FishyJoesCSharpRuntime.Env.catching(to: _exn) {") {
                    if variable.isStatic {
                        fragment.output("\(selfExpression).\(variable.name) = try \(converterName).peekCSharp(newValue)")
                    } else {
                        fragment.outputBlock("try \(containingNamespace).mutateCSharp(_cSharpThis) { value in", closeWith: "}") {
                            fragment.output("value.\(variable.name) = try \(converterName).peekCSharp(newValue)")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func setupFragments(context: FishyJoesContext, generatedTypes: Set<BetterType>) -> [SourceFragment] {
        let generatedTypes = generatedTypes.sorted { $0.name < $1.name }
        let fragment = context.cSharpFragment("TypeSetup.cs")
        fragment.output("using static Cricut.FishyJoesRuntime.Loader;")
        fragment.blankLine()

        let moduleRegisterTypesFn = "FishyJoes_\(context.module.name.mangled)_registerTypes"

        fragment.outputBlock("namespace Cricut.\(context.module.name) {") {
            fragment.outputBlock("public class _TypeSetup {") {
                fragment.output(context.module.dllImportMark)
                fragment.output("static extern void \(moduleRegisterTypesFn)();")
                fragment.blankLine()

                var initializerWriters: [() -> Void] = []
                for type in generatedTypes {
                    let resolved = context.resolve(type: type)

                    let setupParams = resolved.cSharpSetupParameters(in: context)
                    let setupDelegates = resolved.cSharpSetupDelegates(in: context)

                    setupDelegates.forEach { fragment.output($0) }

                    if resolved.definingModule == context.module {
                        precondition(!setupParams.contains(where: \.isTypeParameter), "unexpected type parameter in \(type.name)")
                        fragment.output(resolved.definingModule.dllImportMark)
                        fragment.outputBlock("static extern void \(resolved.cSharpSetupName)(", closeWith: ");") {
                            for param in setupParams {
                                fragment.output("\(param.type!) \(param.name!),")
                            }
                            fragment.output("out CreatedRef _exn")
                        }
                        fragment.blankLine()
                    } else if !type.isGeneric {
                        // non-generic types are sufficiently set up by defining module
                        continue
                    }

                    initializerWriters.append {
                        fragment.outputBlock("Once(\"setup_\(resolved.converterType.name)\", () => {", closeWith: "});") {
                            fragment.output("Console.WriteLine(\"setting up \(type.name)...\");")

                            var typeArgStr = ""
                            if case let typeArguments = setupParams.compactMap(\.typeValue), !typeArguments.isEmpty {
                                typeArgStr = "<\(typeArguments.joined(separator: ", "))>"
                            }

                            fragment.outputBlock("Utilities.Check((out CreatedRef exn) => \(resolved.cSharpSetupName)\(typeArgStr)(", closeWith: "));") {
                                for param in setupParams {
                                    param.valueWriter(fragment)
                                }
                                fragment.output("out exn")
                            }
                        }
                    }
                }

                fragment.output("public static void _ensureLoaded() {}")
                fragment.blankLine()

                fragment.outputBlock("static _TypeSetup() {") {
                    fragment.output("// There's no explicit way to call the static constructor, so do this instead")
                    fragment.output("FishyJoesRuntime.Loader.ensureLoaded();")
                    for dependency in context.module.dependencies {
                        fragment.output("\(dependency)._ensureLoaded();")
                    }
                    fragment.output("\(moduleRegisterTypesFn)();")

                    fragment.blankLine()
                    for writer in initializerWriters {
                        writer()
                    }
                }
            }
        }

        let swiftSetupFragment = context.swiftFragment(
            "CSharpInterface/TypeSetup.swift",
            additionalImports: ["Foundation", "FishyJoesCSharpRuntime"]
        )

        swiftSetupFragment.output("@_cdecl(\"\(moduleRegisterTypesFn)\")")
        swiftSetupFragment.outputBlock("public func \(moduleRegisterTypesFn)() {") {
            for type in generatedTypes {
                let resolved = context.resolve(type: type)
                swiftSetupFragment.output("Env.registerType(\(resolved.converterType.name).self, as: \"\(resolved.converterType.name)\")")
            }
        }

        let exportFragment = SourceFragment(sourceryDestination: "file:CSharpInterface/@_exported.swift")
        exportFragment.output("@_exported import \(context.module.name)")
        for dependency in context.module.dependencies {
            exportFragment.output("@_exported import \(dependency)_CSharpInterface")
        }

        return [fragment, swiftSetupFragment, exportFragment]
    }

    func cSharp(method: Method, of type: TranslatedType, context: FishyJoesContext) -> CSharpClass.MethodOrVariable? {
        let exportAnnotation = method.exportAnnotation
        var omitParameters = Set(exportAnnotation.omitParameters)
        var parameters: [(labelComment: String?, name: String, type: CSharpClass.CSType, defaultValue: String?)] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            var label: String?
            if let swiftLabel = parameter.label, swiftLabel != parameter.name {
                label = swiftLabel
            }
            var defaultValue: String?
            if let swiftDefaultValue = parameter.defaultValue {
                if let cSharpDefaultValue = cSharp(value: swiftDefaultValue) {
                    defaultValue = cSharpDefaultValue
                } else {
                    context.warnMissingDefault(parameter: parameter, in: method)
                }
            }
            parameters.append((label, parameter.name, resolved.cSharpType, defaultValue))
        }

        return .method(
            CSharpClass.Method(
                documentation: method.documentation,
                isStatic: method.isStatic,
                isOverride: method.exportAnnotation.isOverride,
                name: upperCaseFirst(exportAnnotation.name),
                mangledName: "\(type.mangledName)_\(exportAnnotation.name.mangled)",
                parameters: parameters,
                returnType: context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).cSharpType,
                deprecation: method.deprecation,
                body: nil
            )
        )
    }

    func cSharp(field: Variable, of type: TranslatedType, context: FishyJoesContext, useNativeName: Bool = false) -> CSharpClass.MethodOrVariable? {
        let csName: String
        var asMethod = false

        let isOverride = field.exportAnnotation?.isOverride ?? false

        if useNativeName {
            guard field.exportAnnotation == nil else {
                fatalErr("field \(field.name) should not be annotated, as it's in a type being exported memberwise")
            }
            csName = upperCaseFirst(field.name)
        } else {
            guard let exportAnnotation = field.exportAnnotation else {
                return nil
            }
            asMethod = exportAnnotation.kind == .asMethod || (field.isComputed && !isOverride)
            csName = upperCaseFirst(exportAnnotation.cSharpName)
        }
        let resolved = context.resolve(type: field.typeName.better)
        return .variable(
            CSharpClass.Variable(
                documentation: field.documentation,
                isStatic: field.isStatic,
                isOverride: isOverride,
                readOnly: !field.isMutable,
                asMethod: asMethod,
                name: csName,
                mangledName: "\(type.mangledName)_\(csName.mangled)",
                type: resolved.cSharpType,
                deprecation: field.deprecation
            )
        )
    }

    func defaultObjectMethods(for type: CSharpClass.CSType, members: [String]) -> [CSharpClass.Method] {
        [
            CSharpClass.Method(
                documentation: [],
                isStatic: false,
                isOverride: true,
                name: "Equals",
                mangledName: "",
                parameters: [(nil, "obj", .optional(.primitive("object")), nil)],
                returnType: .primitive("bool"),
                deprecation: nil,
                body: ["return obj is \(type.name) ? this == (\(type.name))obj : false;"]
            ),
            CSharpClass.Method(
                documentation: [],
                isStatic: true,
                isOverride: false,
                name: "operator ==",
                mangledName: "",
                parameters: [
                    (nil, "lhs", type, nil),
                    (nil, "rhs", type, nil),
                ],
                returnType: .primitive("bool"),
                deprecation: nil,
                body: members.map { "if (lhs.\($0) != rhs.\($0)) { return false; }" } + ["return true;"]
            ),
            CSharpClass.Method(
                documentation: [],
                isStatic: true,
                isOverride: false,
                name: "operator !=",
                mangledName: "",
                parameters: [
                    (nil, "lhs", type, nil),
                    (nil, "rhs", type, nil),
                ],
                returnType: .primitive("bool"),
                deprecation: nil,
                body: ["return !(lhs == rhs);"]
            ),
            CSharpClass.Method(
                documentation: [],
                isStatic: false,
                isOverride: true,
                name: "GetHashCode",
                mangledName: "",
                parameters: [],
                returnType: .primitive("int"),
                deprecation: nil,
                body: ["return Cricut.FishyJoesRuntime.Utilities.Hash<object?>(new object?[] {\(members.joined(separator: ", "))});"]
            ),
        ]
    }

    // Very hacky. But values are an entirely separate language to what we process
    func cSharp(value: String) -> String? {
        if let int = Int(value) {
            return "\(int)"
        } else if let double = Double(value) {
            return "\(double)"
        } else if value == "Double.ulpOfOne.squareRoot()" {
            return "1.4901161193847656E-8"
        }
        switch value {
        case "nil":
            return "null"
        case "true", "false":
            return value
        default:
            return nil
        }
    }
}
