import Foundation
import SourceryRuntime

final class DartTranslator: Translator {
    required init() {}

    func moduleRegisterTypesFn(context: FishyJoesContext) -> String {
        "FishyJoes_\(context.module.name.mangled)_registerTypes"
    }

    struct NativeMethod {
        var name: String
        var definingDartClass: String
        var args: [(name: String, type: DartClass.DartType)]
        var returnType: DartClass.DartType
    }

    public var nativeMethods: [NativeMethod] = []

    func translate(method: Method, context: FishyJoesContext) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            let resolved = context.resolve(type: selfType)
            containingNamespace = resolved.sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(resolved.converterType.name).peekDart(_dartThis, env: env)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        var formals = [(name: "envRef", type: "EnvRef")]
        if !method.isStatic {
            formals.append((name: "_dartThis", type: "foreignObject"))
        }
        formals.append(
            contentsOf: method.parameters.map { parameter in
                let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                return (name: parameter.name, type: resolved.converterType.name + ".CType")
            }
        )
        formals.append((name: "_exn", type: "foreignOutExn"))

        let fragment = context.swiftFragment(
            "DartInterface/\(containingNamespace)+dart-methods.swift",
            additionalImports: ["Foundation", "FishyJoesDartRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        let returnType = context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides)
        let returnSignature = "\(returnType.converterType.name).CType"

        let cMethod = "__dart_\(containingNamespace)_\(exportAnnotation.name)".mangled
        if let deprecation = method.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.output("@_cdecl(\"\(cMethod)\")")
        fragment.outputBlock("public func \(cMethod)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(returnSignature) {") {
            fragment.output("let env = Env(envRef)")
            fragment.outputBlock("return env.catching(to: _exn) {") {
                let callName = method.sourceKind == .initializer ? "" : ".\(method.callName)"

                var mutateBlock: (() -> Void) -> Void = { $0() }
                if method.isMutating {
                    mutateBlock = { body in
                        fragment.outputBlock("return try \(containingNamespace).mutateDart(_dartThis, env: env) { mutatingSelf in", closeWith: "}") {
                            body()
                        }
                    }
                    selfExpression = "mutatingSelf"
                }

                mutateBlock {
                    let body = {
                        fragment.outputBlock("\(selfExpression)\(callName)(", newLineTerminated: false) {
                            fragment.outputMap(method.parameters, separator: ",") { formal in
                                let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                return (formal.label.map { "\($0): " } ?? "") +
                                    "try \(resolved.converterType.name).peekDart(\(formal.name), env: env)"
                            }
                        }
                    }
                    if exportAnnotation.noReturn {
                        fragment.outputBlock("try (") {
                            body()
                            fragment.output()
                        }
                    } else {
                        fragment.outputBlock("return try \(returnType.converterType.name).toDart(") {
                            body()
                            fragment.output(",")
                            fragment.output("env: env")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func translate(variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {
            return []
        }
        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace).peekDart(_dartThis, env: env)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        let dartName = exportAnnotation.name
        let dartGetName = "__dart_\(exportAnnotation.kind == .asMethod ? "" : "get_")\(containingNamespace)_\(dartName)".mangled
        let dartSetName = "__dart_set_\(containingNamespace)_\(dartName)".mangled

        let fragment = context.swiftFragment(
            "DartInterface/\(containingNamespace)+dart-methods.swift",
            additionalImports: ["Foundation", "FishyJoesDartRuntime"]
        )

        let resolved = context.resolve(type: variable.typeName.better)
        let converterName = resolved.converterType.name
        let cType = "\(converterName).CType"

        // Getter
        var formals = [(name: "envRef", type: "EnvRef")]
        if !variable.isStatic {
            formals.append((name: "_dartThis", type: "foreignObject"))
        }
        formals.append((name: "_exn", type: "foreignOutExn"))

        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        if let deprecation = variable.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.output("@_cdecl(\"\(dartGetName)\")")
        fragment.outputBlock("public func \(dartGetName)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(cType) {") {
            fragment.output("let env = Env(envRef)")
            fragment.outputBlock("return env.catching(to: _exn) {") {
                fragment.output("try \(converterName).toDart(\(selfExpression).\(variable.name), env: env)")
            }
        }

        // Setter
        if variable.isPubliclyWritable {
            var formals = [(name: "envRef", type: "EnvRef")]
            if !variable.isStatic {
                formals.append((name: "_dartThis", type: "foreignObject"))
            }
            formals.append((name: "newValue", type: cType))
            formals.append((name: "_exn", type: "foreignOutExn"))

            if let deprecation = variable.deprecation {
                fragment.output(deprecation.swiftDeprecation)
            }
            fragment.output("@_cdecl(\"\(dartSetName)\")")
            fragment.outputBlock("public func \(dartSetName)(", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",") { formal in
                    "\(formal.name): \(formal.type)"
                }
            }
            fragment.outputBlock(" {") {
                fragment.output("let env = Env(envRef)")
                fragment.outputBlock("env.catching(to: _exn) {") {
                    if variable.isStatic {
                        fragment.output("\(selfExpression).\(variable.name) = try \(converterName).peekDart(newValue, env: env)")
                    } else {
                        fragment.outputBlock("try \(containingNamespace).mutateDart(_dartThis, env: env) { value in", closeWith: "}") {
                            fragment.output("value.\(variable.name) = try \(converterName).peekDart(newValue, env: env)")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func declareExternVoid(_ symbol: String, params: [ForeignSetupParameter<DartClass.DartType>]) -> ((SourceFragment) -> Void) {
        { fragment in
            fragment.outputBlock("final \(symbol) = dylib.lookupFunction<", closeWith: ">('\(symbol)');") {
                fragment.outputBlock("ffi.Void Function(", closeWith: "),") {
                    fragment.output("Env env,")
                    for param in params {
                        fragment.output("\(param.type!.name()) \(param.name!),")
                    }
                    fragment.output("OutCreatedRef exn")
                }
                fragment.outputBlock("void Function(") {
                    fragment.output("Env env,")
                    for param in params {
                        fragment.output("\(param.type!.name()) \(param.name!),")
                    }
                    fragment.output("OutCreatedRef exn")
                }
            }
        }
    }

    func setupFragments(context: FishyJoesContext, generatedTypes: [BetterType]) -> [SourceFragment] {
        let swiftSetupFragment = context.swiftFragment(
            "DartInterface/TypeSetup.swift",
            additionalImports: ["Foundation", "FishyJoesDartRuntime"]
        )

        swiftSetupFragment.output("@_cdecl(\"\(moduleRegisterTypesFn(context: context))\")")
        swiftSetupFragment.outputBlock("public func \(moduleRegisterTypesFn(context: context))() {") {
            for type in generatedTypes {
                let resolved = context.resolve(type: type)
                swiftSetupFragment.output("Env.registerType(\(resolved.converterType.name).self, as: \"\(resolved.converterType.name)\")")
            }
        }

        let exportFragment = SourceFragment(sourceryDestination: "file:DartInterface/@_exported.swift")
        exportFragment.output("@_exported import \(context.module.name)")
        for dependency in context.module.dependencies {
            exportFragment.output("@_exported import \(dependency)_DartInterface")
        }

        let fragment = context.dartFragment(
            "type_setup.dart",
            additionalImports: [
                "import 'package:path/path.dart' as path;",
                "import 'dart:io' show Platform, Directory;",
            ]
        )

        let moduleRegisterTypesFn = self.moduleRegisterTypesFn(context: context)
        var externDeclarations: [(SourceFragment) -> Void] = []

        var initializerWriters: [() -> Void] = []
        for type in generatedTypes {
            let resolved = context.resolve(type: type)

            let setupParams = resolved.dartSetupParameters(in: context)
            let setupDelegates = resolved.dartSetupDelegates(in: context)

            setupDelegates.forEach { fragment.output($0) }

            if resolved.definingModule == context.module {
                precondition(!setupParams.contains(where: \.isTypeParameter), "unexpected type parameter in \(type.name)")

                externDeclarations.append(
                    declareExternVoid(resolved.dartSetupName, params: setupParams)
                )

                // TODO
            } else if !type.isGeneric {
                // non-generic types are sufficiently set up by defining module
                continue
            }

            initializerWriters.append {
                fragment.outputBlock("Loader.shared.once(\"setup_\(resolved.converterType.name)\", () {", closeWith: "});") {
                    fragment.output("// print(\"setting up \(type.name) (env=0x${Loader.shared.env.address.toRadixString(16)})...\");")

                    fragment.outputBlock("utils.check<void>((exn) {", closeWith: "});") {
                        let setupName: String
                        if resolved.definingModule.name == "FishyJoesRuntime" {
                            setupName = "Loader.shared.\(resolved.dartSetupName)"
                        } else {
                            setupName = resolved.dartSetupName
                        }

                        var typeArgStr = ""
                        if case let typeArguments = setupParams.compactMap(\.typeValue), !typeArguments.isEmpty {
                            typeArgStr = "<\(typeArguments.map { $0.name() }.joined(separator: ", "))>"
                        }

                        fragment.outputBlock("\(setupName)\(typeArgStr)(", closeWith: ");") {
                            fragment.output("Loader.shared.env,")
                            for param in setupParams {
                                param.valueWriter(fragment)
                            }
                            fragment.output("exn")
                        }
                    }
                }
            }
        }

        for nativeMethod in nativeMethods.sorted(by: { $0.name < $1.name }) {
            externDeclarations.append { fragment in
                fragment.outputBlock("\(nativeMethod.definingDartClass).f\(nativeMethod.name) = dylib.lookupFunction<", closeWith: ">", newLineTerminated: false) {
                    fragment.outputBlock("\(nativeMethod.returnType.ffiCreatedTag) Function(", closeWith: "),") {
                        fragment.output("Env env,")
                        for (argName, argType) in nativeMethod.args {
                            fragment.output("\(argType.ffiUnownedTag) \(argName),")
                        }
                        fragment.output("OutCreatedRef _exn")
                    }
                    fragment.outputBlock("\(nativeMethod.returnType.ffiCreatedName) Function(") {
                        fragment.output("Env env,")
                        for (argName, argType) in nativeMethod.args {
                            fragment.output("\(argType.ffiUnownedName) \(argName),")
                        }
                        fragment.output("OutCreatedRef _exn")
                    }
                }
                fragment.output("(\"\(nativeMethod.name)\");")
            }
        }

        fragment.blankLine()
        fragment.outputBlock("final ensureLoaded = (() {", closeWith: "})();") {
            fragment.output("final dylib = Loader.openLibrary('\(context.module)-dart');")
            fragment.output("final arena = ffi.Arena();")

            fragment.blankLine()
            fragment.output("dylib.lookupFunction<ffi.Void Function(), void Function()>('\(moduleRegisterTypesFn)')();")

            fragment.blankLine()
            for externDeclaration in externDeclarations {
                externDeclaration(fragment)
            }

            fragment.blankLine()
            for writer in initializerWriters {
                writer()
                fragment.blankLine()
            }

            fragment.output("arena.releaseAll();")
        }

        let exportsFragment = SourceFragment(sourceryDestination: "file:../../dart/lib/src/generated/_exports.dart")
        for dartClass in context.dartClasses {
            exportsFragment.output("export './\(dartClass.unqualifiedName).dart';")
        }

        return [swiftSetupFragment, exportFragment, fragment, exportsFragment]
    }

    func dart(method: Method, of type: TranslatedType, context: FishyJoesContext) -> DartClass.MethodOrVariable? {
        let exportAnnotation = method.exportAnnotation
        var omitParameters = Set(exportAnnotation.omitParameters)
        var parameters: [(labelComment: String?, name: String, type: DartClass.DartType, defaultValue: String?)] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            var label: String?
            if let swiftLabel = parameter.label, swiftLabel != parameter.name {
                label = swiftLabel
            }
            var defaultValue: String?
            if let swiftDefaultValue = parameter.defaultValue {
                if let dartDefaultValue = dart(value: swiftDefaultValue) {
                    defaultValue = dartDefaultValue
                } else {
                    context.warnMissingDefault(parameter: parameter, in: method)
                }
            }
            parameters.append((label, parameter.name, resolved.dartType, defaultValue))
        }

        return .method(
            DartClass.Method(
                documentation: method.documentation,
                isStatic: method.isStatic,
                name: exportAnnotation.name,
                mangledName: "\(type.mangledName)_\(exportAnnotation.name.mangled)",
                parameters: parameters,
                returnType: context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).dartType,
                deprecation: method.deprecation,
                body: nil
            )
        )
    }

    func dart(field: Variable, of type: TranslatedType, context: FishyJoesContext, useNativeName: Bool = false) -> DartClass.MethodOrVariable? {
        let dartName: String
        var asMethod = false

        if useNativeName {
            guard field.exportAnnotation == nil else {
                fatalErr("field \(field.name) should not be annotated, as it's in a type being exported memberwise")
            }
            dartName = field.name
        } else {
            guard let exportAnnotation = field.exportAnnotation else {
                return nil
            }
            asMethod = exportAnnotation.kind == .asMethod
            dartName = exportAnnotation.name
        }
        let resolved = context.resolve(type: field.typeName.better)
        return .variable(
            DartClass.Variable(
                documentation: field.documentation,
                isStatic: field.isStatic,
                readOnly: !field.isPubliclyWritable,
                asMethod: asMethod,
                name: dartName,
                mangledName: "\(type.mangledName)_\(dartName.mangled)",
                type: resolved.dartType,
                deprecation: field.deprecation
            )
        )
    }

    // Very hacky. But values are an entirely separate language to what we process
    func dart(value: String) -> String? {
        if let int = Int(value) {
            return "\(int)"
        } else if let double = Double(value) {
            return "\(double)"
        } else if value == "Double.ulpOfOne.squareRoot()" {
            return "1.4901161193847656E-8"
        }
        switch value {
        case "nil":
            return "null"
        case "true", "false":
            return value
        default:
            return nil
        }
    }
}
