import Foundation
import SourceryRuntime

// Swift code common to C# and dart
final class IotaTranslator: Translator {
    required init() {}

    func moduleRegisterTypesFn(context: FishyJoesContext) -> String {
        "FishyJoes_\(context.module.name.mangled)_registerTypes"
    }

    func translate(method: Method, context: FishyJoesContext, betterType: BetterType) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String

        let resolved = context.resolve(type: betterType)
        let containingNamespace = resolved.sourceType.name
        let converterNamespace = resolved.converterType.name

        if method.isStatic {
            selfExpression = containingNamespace
        } else {
            selfExpression = "\(converterNamespace).peekIota(_iotaThis, env: env)"
        }

        var formals = [(name: "envRef", type: "EnvRef")]
        if !method.isStatic {
            formals.append((name: "_iotaThis", type: "foreignObject"))
        }
        formals.append(
            contentsOf: method.parameters.map { parameter in
                let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                return (name: parameter.name, type: resolved.converterType.name + ".CType")
            }
        )
        formals.append((name: "_exn", type: "foreignOutExn"))

        let fragment = context.swiftFragment(
            "IotaInterface/\(containingNamespace)+iota-methods.swift",
            additionalImports: ["Foundation", "FishyJoesIotaRuntime", "\(context.module.name)_CommonInterface"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        let returnType = context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides)
        let returnSignature = method.isAsync ? "foreignObject" : "\(returnType.converterType.name).CType"

        let cMethod = "__iota_\(containingNamespace)_\(exportAnnotation.name)".mangled
        if let deprecation = method.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.output("@_cdecl(\"\(cMethod)\")")
        fragment.outputBlock("public func \(cMethod)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(returnSignature) {") {
            fragment.output("let env = Env(envRef)")
            fragment.outputBlock("return env.catching(to: _exn) {") {
                let callName = method.sourceKind == .initializer ? "" : ".\(method.callName)"
                if method.isAsync {
                    for parameter in method.parameters {
                        let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                        fragment.output("let \(parameter.name) = try \(resolved.converterType.name).peekIota(\(parameter.name), env: env)")
                    }

                    if method.isMutating {
                        fragment.output("let _iotaThisRef = try IotaReference(_iotaThis, env: env)")
                    }
                    if !method.isStatic {
                        fragment.output("let _swiftSelf = UncheckedSendableBox(try \(selfExpression))")
                        selfExpression = "_swiftSelf.value"
                    }
                    if resolved is TranslatedProtocol,
                       method.isDefaultImplementation {
                        fragment.output("let _wrappedSwiftSelf = \(context.module.name)_CommonInterface.\(method.definedIn?.name ?? "")_sans_\(method.callName)(wrapped: _swiftSelf.value)")
                        selfExpression = "_wrappedSwiftSelf"
                    }

                    fragment.outputBlock("let _swiftFuture = Future {", newLineTerminated: false) {
                        fragment.outputBlock("\(method.isThrowing ? "try " : "")await \(selfExpression)\(callName)(") {
                            fragment.outputMap(method.parameters, separator: ",") { formal in
                                (formal.label.map { "\($0): " } ?? "") + formal.name
                            }
                        }
                    }
                    if method.isMutating {
                        // After the promise succeeds, write back the changes to the foreign object.
                        // Changes are not written back after an exception
                        fragment.outputBlock(".flatMap { result in", closeWith: "}") {
                            fragment.output("let (mutationFuture, mutationPromise) = Future<\(returnType.sourceType.name)>.make()")
                            fragment.outputBlock("env.onThread {") {
                                fragment.outputBlock("mutationPromise.handle(") {
                                    fragment.outputBlock("Result {") {
                                        fragment.output("try \(containingNamespace).mutateIota(_iotaThisRef.object, to: _swiftSelf.value, env: env)")
                                    }
                                }
                            }
                            fragment.output("return mutationFuture")
                        }
                    } else {
                        fragment.output()
                    }

                    let translatedFuture = TranslatedFuture(output: returnType)
                    // Since future shows up as an intermediate type, take special care to make sure it's set up properly and registered with the context.
                    context.addToTypeCache(translatedFuture)
                    fragment.output("return try \(translatedFuture.converterType.name).toIota(_swiftFuture, env: env)")
                } else {
                    var mutateBlock: (() -> Void) -> Void = { $0() }
                    if method.isMutating {
                        mutateBlock = { body in
                            fragment.outputBlock("return try \(converterNamespace).withMutatingIota(_iotaThis, env: env) { mutatingSelf in", closeWith: "}") {
                                body()
                            }
                        }
                        selfExpression = "mutatingSelf"
                    }

                    mutateBlock {
                        let body = {
                            if resolved is TranslatedProtocol,
                               method.isDefaultImplementation,
                               let definedInName = method.definedIn?.name {
                                fragment.outputBlock("try \(definedInName)_sans_\(method.callName)(wrapped:", closeWith: ")") {
                                    fragment.output("try \(converterNamespace).peekIota(_iotaThis, env: env)")
                                }
                                fragment.outputBlock("\(callName)(", newLineTerminated: false) {
                                    fragment.outputMap(method.parameters, separator: ",") { formal in
                                        let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                        return (formal.label.map { "\($0): " } ?? "") +
                                        "try \(resolved.converterType.name).peekIota(\(formal.name), env: env)"
                                    }
                                }
                            } else {
                                fragment.outputBlock("\(selfExpression)\(callName)(", newLineTerminated: false) {
                                    fragment.outputMap(method.parameters, separator: ",") { formal in
                                        let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                        return (formal.label.map { "\($0): " } ?? "") +
                                        "try \(resolved.converterType.name).peekIota(\(formal.name), env: env)"
                                    }
                                }
                            }
                        }
                        if exportAnnotation.noReturn {
                            fragment.outputBlock("try (") {
                                body()
                                fragment.output()
                            }
                        } else {
                            fragment.outputBlock("return try \(returnType.converterType.name).toIota(") {
                                body()
                                fragment.output(",")
                                fragment.output("env: env")
                            }
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func translate(variable: SourceryVariablePlus, context: FishyJoesContext, type: Type) -> [SourceFragment]  {
        guard let exportAnnotation = variable.sourceryVariable.exportAnnotation else {
            return []
        }
        var selfExpression: String
        
        let betterType = BetterType(named: type, context: context)
        let sourceResolved = context.resolve(type: betterType)
        let sourceTypeName = sourceResolved.sourceType.name
        let converterTypeName = sourceResolved.converterType.name
        
        let shouldWrap = type is SourceryProtocol && variable.isDefaultImplementation

        if variable.sourceryVariable.isStatic {
            selfExpression = sourceTypeName
        } else {
            selfExpression = "\(converterTypeName).peekIota(_iotaThis, env: env)"
        }

        if shouldWrap {
            selfExpression = "try \(context.module.name)_CommonInterface.\(sourceResolved.sourceType.nonNamespacedName)_sans_\(variable.sourceryVariable.name)(wrapped: \(selfExpression))"
        }

        let iotaName = exportAnnotation.name
        let iotaGetName = shouldWrap ? "__iota__default_\(sourceTypeName)_\(iotaName)".mangled : "__iota_get_\(sourceTypeName)_\(iotaName)".mangled
        let iotaSetName = "__iota_set_\(sourceTypeName)_\(iotaName)".mangled

        let fragment = context.swiftFragment(
            "IotaInterface/\(sourceTypeName)+iota-methods.swift",
            additionalImports: ["Foundation", "FishyJoesIotaRuntime", "\(context.module.name)_CommonInterface"]
        )

        let resolved = context.resolve(type: variable.sourceryVariable.typeName.better)
        let cType = "\(converterTypeName).CType"

        // Getter
        var formals = [(name: "envRef", type: "EnvRef")]
        if !variable.sourceryVariable.isStatic {
            formals.append((name: "_iotaThis", type: "foreignObject"))
        }
        formals.append((name: "_exn", type: "foreignOutExn"))

        fragment.output("// Generated by FishyJoes for `\(sourceTypeName).\(variable.sourceryVariable.name)`")
        if let deprecation = variable.sourceryVariable.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.output("@_cdecl(\"\(iotaGetName)\")")
        fragment.outputBlock("public func \(iotaGetName)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(cType) {") {
            fragment.output("let env = Env(envRef)")
            fragment.outputBlock("return env.catching(to: _exn) {") {
                fragment.output("try \(converterTypeName).toIota(\(selfExpression).\(variable.sourceryVariable.name), env: env)")
            }
        }

        // Setter
        if variable.sourceryVariable.isPubliclyWritable {
            var formals = [(name: "envRef", type: "EnvRef")]
            if !variable.sourceryVariable.isStatic {
                formals.append((name: "_iotaThis", type: "foreignObject"))
            }
            formals.append((name: "newValue", type: cType))
            formals.append((name: "_exn", type: "foreignOutExn"))

            if let deprecation = variable.sourceryVariable.deprecation {
                fragment.output(deprecation.swiftDeprecation)
            }
            fragment.output("@_cdecl(\"\(iotaSetName)\")")
            fragment.outputBlock("public func \(iotaSetName)(", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",") { formal in
                    "\(formal.name): \(formal.type)"
                }
            }
            fragment.outputBlock(" {") {
                fragment.output("let env = Env(envRef)")
                fragment.outputBlock("env.catching(to: _exn) {") {
                    if variable.sourceryVariable.isStatic {
                        fragment.output("\(selfExpression).\(variable.sourceryVariable.name) = try \(converterTypeName).peekIota(newValue, env: env)")
                    } else {
                        fragment.outputBlock("try \(converterTypeName).withMutatingIota(_iotaThis, env: env) { value in", closeWith: "}") {
                            fragment.output("value.\(variable.sourceryVariable.name) = try \(converterTypeName).peekIota(newValue, env: env)")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func setupFragments(context: FishyJoesContext, generatedTypes: [BetterType]) -> [SourceFragment] {
        let swiftSetupFragment = context.swiftFragment(
            "IotaInterface/TypeSetup.swift",
            additionalImports: ["Foundation", "FishyJoesIotaRuntime", "\(context.module.name)_CommonInterface"]
        )

        swiftSetupFragment.output("@_cdecl(\"\(moduleRegisterTypesFn(context: context))\")")
        swiftSetupFragment.outputBlock("public func \(moduleRegisterTypesFn(context: context))() {") {
            for type in generatedTypes {
                let resolved = context.resolve(type: type)
                swiftSetupFragment.output("Env.registerType(\(resolved.converterType.name).self, as: \"\(resolved.converterType.name)\")")
            }
        }

        let exportFragment = SourceFragment(sourceryDestination: "file:IotaInterface/@_exported.swift")
        exportFragment.output("@_exported import \(context.module.name)")
        for dependency in context.module.dependencies {
            exportFragment.output("@_exported import \(dependency)_IotaInterface")
        }

        return [swiftSetupFragment, exportFragment]
    }
}
