import Foundation
import SourceryRuntime

// Swift code common to C# and dart
final class IotaTranslator: Translator {
    required init() {}

    func moduleRegisterTypesFn(context: FishyJoesContext) -> String {
        "FishyJoes_\(context.module.name.mangled)_registerTypes"
    }

    func translate(method: Method, context: FishyJoesContext) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            let resolved = context.resolve(type: selfType)
            containingNamespace = resolved.sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(resolved.converterType.name).peekIota(_iotaThis)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        var formals: [(name: String, type: String)] = []
        if !method.isStatic {
            formals.append((name: "_iotaThis", type: "foreignObject"))
        }
        formals.append(
            contentsOf: method.parameters.map { parameter in
                let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                return (name: parameter.name, type: resolved.converterType.name + ".CType")
            }
        )
        formals.append((name: "_exn", type: "foreignOutExn"))

        let fragment = context.swiftFragment(
            "IotaInterface/\(containingNamespace)+iota-methods.swift",
            additionalImports: ["Foundation", "FishyJoesIotaRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        let returnType = context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides)
        let returnSignature = "\(returnType.converterType.name).CType"

        let cMethod = "__iota_\(containingNamespace)_\(exportAnnotation.name)".mangled
        if let deprecation = method.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.output("@_cdecl(\"\(cMethod)\")")
        fragment.outputBlock("public func \(cMethod)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(returnSignature) {") {
            fragment.outputBlock("FishyJoesIotaRuntime.Env.catching(to: _exn) {") {
                let callName = method.sourceKind == .initializer ? "" : ".\(method.callName)"

                var mutateBlock: (() -> Void) -> Void = { $0() }
                if method.isMutating {
                    mutateBlock = { body in
                        fragment.outputBlock("return try \(containingNamespace).mutateIota(_iotaThis) { mutatingSelf in", closeWith: "}") {
                            body()
                        }
                    }
                    selfExpression = "mutatingSelf"
                }

                mutateBlock {
                    fragment.outputBlock(exportAnnotation.noReturn ? "try (" : "return try \(returnType.converterType.name).toIota(") {
                        fragment.outputBlock("\(selfExpression)\(callName)(") {
                            fragment.outputMap(method.parameters, separator: ",") { formal in
                                let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                return (formal.label.map { "\($0): " } ?? "") +
                                    "try \(resolved.converterType.name).peekIota(\(formal.name))"
                            }
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func translate(variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {
            return []
        }
        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace).peekIota(_iotaThis)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        let iotaName = upperCaseFirst(exportAnnotation.cSharpName)
        let iotaGetName = "__iota_\(exportAnnotation.kind == .asMethod ? "" : "get_")\(containingNamespace)_\(iotaName)".mangled
        let iotaSetName = "__iota_set_\(containingNamespace)_\(iotaName)".mangled

        let fragment = context.swiftFragment(
            "IotaInterface/\(containingNamespace)+iota-methods.swift",
            additionalImports: ["Foundation", "FishyJoesIotaRuntime"]
        )

        let resolved = context.resolve(type: variable.typeName.better)
        let converterName = resolved.converterType.name
        let cType = "\(converterName).CType"

        // Getter
        let formals = (variable.isStatic ? [] : [(name: "_iotaThis", type: "foreignObject")]) + [
            (name: "_exn", type: "foreignOutExn"),
        ]

        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        if let deprecation = variable.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.output("@_cdecl(\"\(iotaGetName)\")")
        fragment.outputBlock("public func \(iotaGetName)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { formal in
                "\(formal.name): \(formal.type)"
            }
        }
        fragment.outputBlock(" -> \(cType) {") {
            fragment.outputBlock("FishyJoesIotaRuntime.Env.catching(to: _exn) {") {
                fragment.output("try \(converterName).toIota(\(selfExpression).\(variable.name))")
            }
        }

        // Setter
        if variable.isPubliclyWritable {
            let formals = (variable.isStatic ? [] : [(name: "_iotaThis", type: "foreignObject")]) + [
                (name: "newValue", type: cType),
                (name: "_exn", type: "foreignOutExn"),
            ]

            if let deprecation = variable.deprecation {
                fragment.output(deprecation.swiftDeprecation)
            }
            fragment.output("@_cdecl(\"\(iotaSetName)\")")
            fragment.outputBlock("public func \(iotaSetName)(", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",") { formal in
                    "\(formal.name): \(formal.type)"
                }
            }
            fragment.outputBlock(" {") {
                fragment.outputBlock("FishyJoesIotaRuntime.Env.catching(to: _exn) {") {
                    if variable.isStatic {
                        fragment.output("\(selfExpression).\(variable.name) = try \(converterName).peekIota(newValue)")
                    } else {
                        fragment.outputBlock("try \(containingNamespace).mutateIota(_iotaThis) { value in", closeWith: "}") {
                            fragment.output("value.\(variable.name) = try \(converterName).peekIota(newValue)")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func setupFragments(context: FishyJoesContext, generatedTypes: [BetterType]) -> [SourceFragment] {
        let swiftSetupFragment = context.swiftFragment(
            "IotaInterface/TypeSetup.swift",
            additionalImports: ["Foundation", "FishyJoesIotaRuntime"]
        )

        swiftSetupFragment.output("@_cdecl(\"\(moduleRegisterTypesFn(context: context))\")")
        swiftSetupFragment.outputBlock("public func \(moduleRegisterTypesFn(context: context))() {") {
            for type in generatedTypes {
                let resolved = context.resolve(type: type)
                swiftSetupFragment.output("Env.registerType(\(resolved.converterType.name).self, as: \"\(resolved.converterType.name)\")")
            }
        }

        let exportFragment = SourceFragment(sourceryDestination: "file:IotaInterface/@_exported.swift")
        exportFragment.output("@_exported import \(context.module.name)")
        for dependency in context.module.dependencies {
            exportFragment.output("@_exported import \(dependency)_IotaInterface")
        }

        return [swiftSetupFragment, exportFragment]
    }
}
