import Foundation
import SourceryRuntime

final class KotlinTranslator: Translator {
    required init() {}

    func javaClassName(_ name: String, in context: FishyJoesContext) -> String {
        "com/cricut/\(context.module.name.lowercased())/\(name.replacingOccurrences(of: ".", with: "$"))"
    }

    var allMethods: [String: [(javaName: String, signature: String, cName: String, isProtocolDefault: Bool)]] = [:]

    func translate(method: Method, context: FishyJoesContext, isProtocol: Bool, typeName: String) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            let resolved = context.resolve(type: selfType)
            containingNamespace = resolved.sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else if method.isAsync {
                if method.isMutating {
                    selfExpression = "\(resolved.converterType.name).mutateJava(_javaThisRef.object, env: &_javaEnv)"
                } else {
                    selfExpression = "\(resolved.converterType.name).fromJava(_javaThisRef.object, env: _javaEnv)"
                }
            } else {
                selfExpression = "\(resolved.converterType.name).fromJava(_javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }
        var formals = [(name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>")]
        if isProtocol,
           method.isInExtension {
            formals.append((name: "_javaCompanionThis", type: "jobject"))
        }
        formals.append((name: "_javaThis", type: "jobject"))
        do {
            var unnamedParamCnt = 1
            formals.append(
                contentsOf:
                    method.parameters.map { parameter in
                        let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                        var paramName = parameter.name
                        if paramName.isEmpty {
                            paramName = "_\(unnamedParamCnt)"
                            unnamedParamCnt += 1
                        }
                        return (name: paramName, type: resolved.converterType.name + ".CType")
                    }
            )
        }

        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["Foundation", "FishyJoesJavaRuntime", "\(context.module.name)_CommonInterface"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        var jniSignature = ""
        if isProtocol,
           method.isInExtension,
           let selfType = method.definedIn {
            let resolved = context.resolve(type: selfType)
            let className = javaClassName(resolved.kotlinName, in: context)
            jniSignature += "L\(className);"
        }
        for parameter in method.parameters {
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            jniSignature += resolved.jniType.asSignature
        }
        let returnType = context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides)
        let returnSignature = method.isAsync ? "FutureConverter<\(returnType.converterType.name)>.CType" : "\(returnType.converterType.name).CType"
        jniSignature = "(\(jniSignature))\(method.isAsync ? "Lkotlinx/coroutines/Deferred;" : returnType.jniType.asSignature)"

        var cMethod = "java_\(containingNamespace)"
        if isProtocol,
           method.isInExtension {
            cMethod += "__default"
        }
        cMethod += "_\(exportAnnotation.name)"
        cMethod = cMethod.replacingOccurrences(of: ".", with: "_")

        var javaName = "__jni"
        if isProtocol,
           method.isInExtension {
            javaName += "__default"
        }
        javaName += "_\(exportAnnotation.name)"
        allMethods[containingNamespace, default: []].append((javaName, jniSignature, cMethod, isProtocol && method.isInExtension))
        if let deprecation = method.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.outputBlock("let \(cMethod): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(returnSignature) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                let callName = method.sourceKind == .initializer ? "" : ".\(method.callName)"
                if method.isAsync {
                    var unnamedParamCnt = 1
                    for parameter in method.parameters {
                        var paramName = parameter.name
                        if paramName.isEmpty {
                            paramName = "_\(unnamedParamCnt)"
                            unnamedParamCnt += 1
                        }
                        let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                        fragment.output("let \(paramName) = try \(resolved.converterType.name).fromJava(\(paramName), env: _javaEnv)")
                    }
                    if !method.isStatic {
                        fragment.output("let _javaThisRef = try JavaReference(local: _javaThis, env: _javaEnv)")
                    }

                    fragment.outputBlock("return try swiftTask(env: _javaEnv) { _javaEnv, _vm in", closeWith: "}") {
                        let callBlock: (() -> Void) -> Void
                        if method.isMutating {
                            let _selfExpression = selfExpression
                            callBlock = { body in
                                fragment.outputBlock("return try await \(_selfExpression) { mutatingSelf, _javaEnv in", closeWith: "}") {
                                    body()
                                }
                            }
                            selfExpression = "mutatingSelf"
                        } else if !method.isStatic {
                            let _selfExpression = selfExpression
                            callBlock = { body in
                                fragment.output("let _swiftThis = try \(_selfExpression)")
                                body()
                            }
                            selfExpression = "_swiftThis"
                        } else {
                            callBlock = { $0() }
                        }

                        callBlock {
                            fragment.outputBlock("let value: \(returnType.converterType.name).SwiftType = try await {", closeWith: "}()") {
                                fragment.output("try Env.relinquishJVMThread(on: _vm)")
                                fragment.output("defer { _javaEnv = try! Env.acquireJVMThread(on: _vm) }")
                                fragment.outputBlock("return \(method.isThrowing ? "try " : "")await \(selfExpression)\(callName)(", closeWith: ")") {
                                    fragment.outputMap(method.parameters, separator: ",") { formal in
                                        (formal.label.map { "\($0): "} ?? "") + formal.name
                                    }
                                }
                            }
                            fragment.output("return try \(returnType.converterType.name).toJavaObject(value, env: _javaEnv)")
                        }
                    }
                } else {
                    var mutateBlock: (() -> Void) -> Void = { $0() }
                    if method.isMutating {
                        mutateBlock = { body in
                            fragment.outputBlock("return try \(containingNamespace).mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in", closeWith: "}") {
                                body()
                            }
                        }
                        selfExpression = "mutatingSelf"
                    }

                    mutateBlock {
                        fragment.outputBlock("return try \(returnType.converterType.name).toJava(") {
                            if isProtocol,
                               method.isInExtension {
                                let foreignProtocolType = "_Java\(typeName)"
                                fragment.outputBlock("\(method.isThrowing ? "try " : "")\(foreignProtocolType)_sans_\(method.callName)(wrapped:", closeWith: ")", newLineTerminated: false) {
                                    fragment.output("\(method.isThrowing ? "try " : "")\(selfExpression)")
                                }
                                fragment.outputBlock("\(callName)(", closeWith: "),") {
                                    var unnamedParamCnt = 1
                                    fragment.outputMap(method.parameters, separator: ",") { formal in
                                        var paramName = formal.name
                                        if paramName.isEmpty {
                                            paramName += "_\(unnamedParamCnt)"
                                            unnamedParamCnt += 1
                                        }
                                        let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                        return (formal.label.map { "\($0): " } ?? "") +
                                        "try \(resolved.converterType.name).fromJava(\(paramName), env: _javaEnv)"
                                    }
                                }
                                fragment.output("env: _javaEnv")
                            } else {
                                fragment.outputBlock("\(method.isThrowing ? "try " : "")\(selfExpression)\(callName)(", closeWith: "),") {
                                    var unnamedParamCnt = 1
                                    fragment.outputMap(method.parameters, separator: ",") { formal in
                                        var paramName = formal.name
                                        if paramName.isEmpty {
                                            paramName += "_\(unnamedParamCnt)"
                                            unnamedParamCnt += 1
                                        }
                                        let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                        return (formal.label.map { "\($0): " } ?? "") +
                                        "try \(resolved.converterType.name).fromJava(\(paramName), env: _javaEnv)"
                                    }
                                }
                                fragment.output("env: _javaEnv")
                            }
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func translate(variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {
            return []
        }
        let kotlinName = exportAnnotation.name
        let jvmGetName = "__jni_\(exportAnnotation.kind == .asMethod ? "" : "get_")\(kotlinName)"
        let jvmSetName = "__jni_set_\(kotlinName)"

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            let resolved = context.resolve(type: selfType)
            containingNamespace = resolved.converterType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(resolved.converterType.name).fromJava(_javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        let cGetName = "java_get_\(containingNamespace)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")
        let cSetName = "java_set_\(containingNamespace)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")

        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["Foundation", "FishyJoesJavaRuntime", "\(context.module.name)_CommonInterface"]
        )

        let resolved = context.resolve(type: variable.typeName.better)

        // TODO: support async variables
        // if variable.isAsyncOrIsolated {
        //     resolved = TranslatedFuture(output: resolved)
        //     context.addToTypeCache(resolved)
        // }

        let jniSignature = resolved.jniType.asSignature
        let converterName = resolved.converterType.name
        let cType = "\(converterName).CType"

        // Getter
        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ]

        allMethods[containingNamespace, default: []].append((jvmGetName, "()" + jniSignature, cGetName, false))
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        if let deprecation = variable.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.outputBlock("let \(cGetName): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(cType) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                let value = "\(selfExpression).\(variable.name)"
                // TODO: support async variables
                // if variable.isAsyncOrIsolated {
                //     value = "Future { try await \(value) }"
                // }
                fragment.output("try \(converterName).toJava(\(value), env: _javaEnv)")
            }
        }

        // Setter
        if variable.isPubliclyWritable {
            let formals = [
                (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
                (name: "_javaThis", type: "jobject"),
                (name: "newValue", type: cType),
            ]
            allMethods[containingNamespace, default: []].append((jvmSetName, "(\(jniSignature))V", cSetName, false))
            if let deprecation = variable.deprecation {
                fragment.output(deprecation.swiftDeprecation)
            }
            fragment.outputBlock("let \(cSetName): @convention(c) (", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",", \.type)
            }
            fragment.outputBlock(" -> Void = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
                fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                    if variable.isStatic {
                        fragment.output("\(selfExpression).\(variable.name) = try \(converterName).fromJava(newValue, env: _javaEnv)")
                    } else {
                        fragment.outputBlock("try \(containingNamespace).mutateJava(_javaThis, env: _javaEnv) { value in", closeWith: "}") {
                            fragment.output("value.\(variable.name) = try \(converterName).fromJava(newValue, env: _javaEnv)")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func setupFragments(context: FishyJoesContext, generatedTypes: [BetterType]) -> [SourceFragment] {
        let typeSetupFragment = context.swiftFragment(
            "JavaInterface/TypeSetup.swift",
            additionalImports: ["Foundation", "FishyJoesJavaRuntime", "\(context.module.name)_CommonInterface"]
        )

        var usedMethods: Set<String> = []

        typeSetupFragment.output("@available(*, deprecated, message: \"Not actually deprecated, but this silences warnings because it may refer to deprecated methods\")")
        typeSetupFragment.output("@_cdecl(\"JNI_OnLoad\")")
        typeSetupFragment.outputBlock("public func jniOnLoad(vm: UnsafeMutablePointer<JavaVM?>, reserved: UnsafeMutableRawPointer) -> jint {") {
            typeSetupFragment.output("var envRaw: UnsafeMutableRawPointer?")
            typeSetupFragment.outputBlock("guard vm.pointee!.pointee.GetEnv(vm, &envRaw, JNI_VERSION_1_4) == JNI_OK else {") {
                typeSetupFragment.output("fatalError(\"Couldn't obtain jvm environment\")")
            }
            typeSetupFragment.output("let env = UnsafeMutablePointer<JNIEnv?>(OpaquePointer(envRaw))")
            typeSetupFragment.outputBlock("return FishyJoesJavaRuntime.callbackBody(env!) { env in", closeWith: "}") {
                typeSetupFragment.output("let bag = CStringBag()")
                for type in generatedTypes {
                    let resolved = context.resolve(type: type)
                    typeSetupFragment.output("// print(\"setting up \(resolved.converterType.name)...\")")
                    typeSetupFragment.output("try \(resolved.converterType.name).javaSetup(env: env)")
                    if case .named = type {
                        if let nativeMethods = allMethods[resolved.sourceType.name] {
                            let protocolDefaultMethods = nativeMethods.filter { $0.isProtocolDefault }
                            let normalMethods = nativeMethods.filter { !$0.isProtocolDefault }

                            if !protocolDefaultMethods.isEmpty {
                                typeSetupFragment.outputBlock("try env.RegisterNatives(", closeWith: ")") {
                                    typeSetupFragment.output("\(resolved.converterType.name).externalCompanionClass", newLineTerminated: false)
                                    for (method, signature, cName, _) in protocolDefaultMethods {
                                            typeSetupFragment.output(",")
                                            typeSetupFragment.outputBlock("JNINativeMethod(", newLineTerminated: false) {
                                                typeSetupFragment.output("name: bag.add(\"\(method)\"),")
                                                typeSetupFragment.output("signature: bag.add(\"\(signature)\"),")
                                                typeSetupFragment.output("fnPtr: unsafeBitCast(\(cName), to: UnsafeMutableRawPointer.self)")
                                            }
                                    }
                                    typeSetupFragment.output()
                                }
                            }
                            typeSetupFragment.outputBlock("try env.RegisterNatives(", closeWith: ")") {
                                typeSetupFragment.output("\(resolved.converterType.name).externalWitnessClass ?? \(resolved.converterType.name).javaClass", newLineTerminated: false)
                                for (method, signature, cName, _) in normalMethods {
                                    typeSetupFragment.output(",")
                                    typeSetupFragment.outputBlock("JNINativeMethod(", newLineTerminated: false) {
                                        typeSetupFragment.output("name: bag.add(\"\(method)\"),")
                                        typeSetupFragment.output("signature: bag.add(\"\(signature)\"),")
                                        typeSetupFragment.output("fnPtr: unsafeBitCast(\(cName), to: UnsafeMutableRawPointer.self)")
                                    }
                                }
                                typeSetupFragment.output()
                            }

                            usedMethods.insert(resolved.sourceType.name)
                        }
                        if resolved.converterType.name != resolved.sourceType.name,
                           let nativeMethods = allMethods[resolved.converterType.name] {
                            let protocolDefaultMethods = nativeMethods.filter { $0.isProtocolDefault }
                            let normalMethods = nativeMethods.filter { !$0.isProtocolDefault }

                            if !protocolDefaultMethods.isEmpty {
                                typeSetupFragment.outputBlock("try env.RegisterNatives(", closeWith: ")") {
                                    typeSetupFragment.output("\(resolved.converterType.name).externalCompanionClass", newLineTerminated: false)
                                    for (method, signature, cName, _) in protocolDefaultMethods {
                                            typeSetupFragment.output(",")
                                            typeSetupFragment.outputBlock("JNINativeMethod(", newLineTerminated: false) {
                                                typeSetupFragment.output("name: bag.add(\"\(method)\"),")
                                                typeSetupFragment.output("signature: bag.add(\"\(signature)\"),")
                                                typeSetupFragment.output("fnPtr: unsafeBitCast(\(cName), to: UnsafeMutableRawPointer.self)")
                                            }
                                    }
                                    typeSetupFragment.output()
                                }
                            }
                            typeSetupFragment.outputBlock("try env.RegisterNatives(", closeWith: ")") {
                                typeSetupFragment.output("\(resolved.converterType.name).externalWitnessClass ?? \(resolved.converterType.name).javaClass", newLineTerminated: false)
                                for (method, signature, cName, _) in normalMethods {
                                    typeSetupFragment.output(",")
                                    typeSetupFragment.outputBlock("JNINativeMethod(", newLineTerminated: false) {
                                        typeSetupFragment.output("name: bag.add(\"\(method)\"),")
                                        typeSetupFragment.output("signature: bag.add(\"\(signature)\"),")
                                        typeSetupFragment.output("fnPtr: unsafeBitCast(\(cName), to: UnsafeMutableRawPointer.self)")
                                    }
                                }
                                typeSetupFragment.output()
                            }

                            usedMethods.insert(resolved.converterType.name)
                        }
                    }
                }
                typeSetupFragment.output("return JNI_VERSION_1_4")
            }
        }

        let droppedMethods = Set(allMethods.keys).subtracting(usedMethods)
        guard droppedMethods.isEmpty else {
            fatalErr("methods for \(droppedMethods) were never set up! Probably a bug.")
        }

        let module = context.module
        let repName = "\(module.name)LoaderRepresentative"
        let ktFragment = SourceFragment(
            sourceryDestination: "file:../../kotlin/src/generated/kotlin/com/cricut/\(module.name.lowercased())/\(repName).kt"
        )
        ktFragment.output("package \(module.kotlinPackage)")
        ktFragment.blankLine()
        ktFragment.output("import com.cricut.fishyjoes.runtime.LibraryLoader")
        ktFragment.output("import com.cricut.fishyjoes.runtime.FishyJoesRuntimeRepresentative")
        for dependency in module.dependencies {
            ktFragment.output("import com.cricut.\(dependency.lowercased()).\(dependency)LoaderRepresentative")
        }

        ktFragment.blankLine()
        ktFragment.outputBlock("public object \(repName): LibraryLoader.LibraryRepresentative {") {
            ktFragment.output("override fun ensureLoaded() {}")
            ktFragment.output("override val nativeLibs = listOf(\"\(module.name)\", \"\(module.name)-java\")")
            let deps = ["FishyJoesRuntimeRepresentative"] + module.dependencies.map { "\($0)LoaderRepresentative" }
            ktFragment.outputBlock("override val dependencies: List<LibraryLoader.LibraryRepresentative> = listOf(") {
                ktFragment.outputMap(deps, separator: ",", { $0 })
            }
            ktFragment.blankLine()
            ktFragment.outputBlock("init {") {
                ktFragment.output("LibraryLoader.loadRepresentative(this)")
            }
        }

        ktFragment.outputBlock("internal fun loadNativeLibs() {") {
            ktFragment.output("\(repName).ensureLoaded()")
        }

        let exportFragment = SourceFragment(sourceryDestination: "file:JavaInterface/@_exported.swift")
        exportFragment.output("@_exported import \(module.name)")
        for dependency in module.dependencies {
            exportFragment.output("@_exported import \(dependency)_JavaInterface")
        }

        return [typeSetupFragment, ktFragment, exportFragment]
    }

    func kotlin(method: Method, context: FishyJoesContext) -> KotlinClass.MethodOrVariable? {
        let exportAnnotation = method.exportAnnotation
        let omitParameters = Set(exportAnnotation.omitParameters)
        let compatParameters = Set(exportAnnotation.compatibilityOrder)

        var parameters: [(labelComment: String?, name: String, KotlinClass.KType, String?)] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                continue
            }
            if compatParameters.contains(parameter.name) {
                precondition(
                    parameter.defaultValue != nil,
                    """
                    Can't use non-default parameter \(parameter.name) in compatibilityParameters annotation
                        context: \(context.debugContext)
                    """
                )
            }

            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            var label: String?
            if let swiftLabel = parameter.label, swiftLabel != parameter.name {
                label = swiftLabel
            }
            var defaultValue: String?
            if let swiftDefaultValue = parameter.defaultValue {
                if let kotlinDefaultValue = kotlin(value: swiftDefaultValue) {
                    defaultValue = kotlinDefaultValue
                } else {
                    context.warnMissingDefault(parameter: parameter, in: method)
                }
            }
            parameters.append((label, parameter.name, resolved.kotlinType, defaultValue))
        }

        return .method(
            KotlinClass.Method(
                documentation: method.documentation,
                isStatic: method.isStatic,
                isSuspend: method.isAsync,
                isOverride: exportAnnotation.isOverride,
                name: exportAnnotation.name,
                parameters: parameters,
                compatibilityOrder: exportAnnotation.compatibilityOrder,
                returnType: context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).kotlinType,
                deprecation: method.deprecation,
                body: nil
            )
        )
    }

    func kotlin(field: Variable, context: FishyJoesContext, useNativeName: Bool = false) -> KotlinClass.MethodOrVariable? {
        let ktName: String
        var asMethod = false

        if useNativeName {
            guard field.exportAnnotation == nil else {
                fatalErr("field \(field.name) should not be annotated, as it's in a type being exported memberwise")
            }
            ktName = field.name
        } else {
            guard let exportAnnotation = field.exportAnnotation else {
                return nil
            }
            asMethod = exportAnnotation.kind == .asMethod
            ktName = exportAnnotation.name
        }
        let resolved = context.resolve(type: field.typeName.better)
        let deprecation = Deprecation(from: field.attributes)
        if asMethod {
            precondition(!field.isPubliclyWritable, "\(context.debugContext): Can't export mutable fields as methods: \(field.name)")
            return .method(
                KotlinClass.Method(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isSuspend: field.isAsyncOrIsolated,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    name: ktName,
                    parameters: [],
                    compatibilityOrder: [],
                    returnType: resolved.kotlinType,
                    deprecation: deprecation,
                    body: nil
                )
            )
        } else {
            return .variable(
                KotlinClass.Variable(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    isMutable: field.isMutable,
                    isPubliclyWritable: field.isPubliclyWritable,
                    name: ktName,
                    type: resolved.kotlinType,
                    deprecation: deprecation
                )
            )
        }
    }

    // Very hacky. But values are an entirely separate language to what we process
    func kotlin(value: String) -> String? {
        if let int = Int(value) {
            return "\(int)"
        } else if let double = Double(value) {
            return "\(double)"
        } else if value == "Double.ulpOfOne.squareRoot()" {
            return "1.4901161193847656E-8"
        }
        switch value {
        case "nil":
            return "null"
        case "true", "false":
            return value
        default:
            return nil
        }
    }

    func conform(_ kotlinClass: KotlinClass, to protoName: String, context: FishyJoesContext) {
        let resolved = context.resolve(type: .named(.init(name: protoName, module: nil)))

        kotlinClass.conformances.insert(resolved.kotlinName)

        if let proto = resolved as? TranslatedProtocol {
            let protoDefs = Set(
                proto.methods.compactMap { context.kotlin(method: $0).map(OverrideSignature.init) } +
                proto.computedVariables.compactMap { context.kotlin(field: $0).map(OverrideSignature.init) }
            )

            kotlinClass.methods = kotlinClass.methods.map { method in
                var modified = method
                if protoDefs.contains(OverrideSignature(.method(method))) {
                    modified.isOverride = true
                }
                return modified
            }
            kotlinClass.fields = kotlinClass.fields.map { field in
                var modified = field
                if protoDefs.contains(OverrideSignature(.variable(field))) {
                    modified.isOverride = true
                }
                return modified
            }
            if let product = kotlinClass as? KotlinProductClass {
                product.fields = product.fields.map { field in
                    var modified = field
                    if protoDefs.contains(OverrideSignature(.variable(field))) {
                        modified.isOverride = true
                    }
                    return modified
                }
                if case let .`public`(constructorFields, constructorArguments) = product.constructor {
                    let overriddenConstructorFields = constructorFields.map { field in
                        var modified = field
                        if protoDefs.contains(OverrideSignature(.variable(field))) {
                            modified.isOverride = true
                        }
                        return modified
                    }

                    product.constructor = .public(fields: overriddenConstructorFields, arguments: constructorArguments)
                }
            }
        }
    }
}

extension KotlinClass {
    func conforming(to protocols: Set<String>, context: FishyJoesContext) -> KotlinClass {
        protocols.reduce(into: self) { kClass, proto in
            context.kotlinTranslator.conform(kClass, to: proto, context: context)
        }
    }
}

private struct OverrideSignature: Hashable {
    let isStatic: Bool
    let name: String
    let parameters: [KotlinClass.KType]?
    let returnType: KotlinClass.KType
    init(_ methodOrVar: KotlinClass.MethodOrVariable) {
        switch methodOrVar {
        case .method(let method):
            isStatic = method.isStatic
            name = method.name
            parameters = method.parameters.map(\.2)
            returnType = method.returnType
        case .variable(let variable):
            isStatic = variable.isStatic
            name = variable.name
            parameters = nil
            returnType = variable.type
        }
    }
}
