import Foundation
import SourceryDataModel

final class KotlinTranslator: Translator {
    required init() {}

    func javaClassName(_ name: String, in context: FishyJoesContext) -> String {
        "com/cricut/\(context.module.name.lowercased())/\(name.replacingOccurrences(of: ".", with: "$"))"
    }

    struct MethodInfo: Hashable {
        let javaName: String
        let signature: String
        let cName: String
        let isProtocolDefault: Bool
    }
    var allMethods: [String: Set<MethodInfo>] = [:]

    func translate(method: Method, context: FishyJoesContext, betterType: BetterType) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String

        let resolved = context.resolve(type: betterType)
        let containingNamespace = resolved.sourceType.name
        let converterNamespace = resolved.converterType.name

        if method.isStatic {
            selfExpression = containingNamespace
        } else if method.isAsync {
            if method.isMutating {
                selfExpression = "await \(resolved.converterType.name).mutateJava(_javaThisRef.object, env: &_javaEnv)"
            } else {
                selfExpression = "\(resolved.converterType.name).fromJava(_javaThisRef.createLocalRef(env: _javaEnv), env: _javaEnv)"
            }
        } else {
            selfExpression = "\(resolved.converterType.name).fromJava(_javaThis, env: _javaEnv)"
        }

        var formals = [(name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>")]
        if resolved is TranslatedProtocol,
           method.isDefaultImplementation {
            formals.append((name: "_javaCompanionThis", type: "jobject"))
        }
        formals.append((name: "_javaThis", type: "jobject"))
        do {
            formals.append(
                contentsOf:
                    method.parameters.map { parameter in
                        let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                        return (name: parameter.name, type: resolved.converterType.name + ".CType")
                    }
            )
        }

        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+java-methods.swift",
            additionalImports: ["Foundation", "FishyJoesJavaRuntime", "\(context.module.name)_CommonInterface"]
        )

        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        var jniSignature = ""
        if method.isDefaultImplementation,
            resolved is TranslatedProtocol {
            let className = javaClassName(resolved.kotlinName, in: context)
            jniSignature += "L\(className);"
        }
        for parameter in method.parameters {
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            jniSignature += resolved.jniType.asSignature
        }
        let returnType = context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides)
        let returnSignature = method.isAsync ? "FutureConverter<\(returnType.converterType.name)>.CType" : "\(returnType.converterType.name).CType"
        jniSignature = "(\(jniSignature))\(method.isAsync ? "Lkotlinx/coroutines/Deferred;" : returnType.jniType.asSignature)"

        var cMethod = "java_\(converterNamespace)"
        if method.isDefaultImplementation {
            cMethod += "__default"
        }
        cMethod += "_\(exportAnnotation.name)"
        cMethod = cMethod.replacingOccurrences(of: ".", with: "_")

        var javaName = "__jni"
        if method.isDefaultImplementation {
            javaName += "__default"
        }
        javaName += "_\(exportAnnotation.name)"
        allMethods[containingNamespace, default: []].insert(MethodInfo(javaName: javaName, signature: jniSignature, cName: cMethod, isProtocolDefault: method.isDefaultImplementation))
        if let deprecation = method.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.outputBlock("let \(cMethod): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(returnSignature) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                let callName = method.sourceKind == .initializer ? "" : ".\(method.callName)"
                if method.isAsync {
                    for parameter in method.parameters {
                        let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
                        fragment.output("let \(parameter.name) = try \(resolved.converterType.name).fromJava(\(parameter.name), env: _javaEnv)")
                    }
                    if !method.isStatic {
                        fragment.output("let _javaThisRef = try JavaReference(local: _javaThis, env: _javaEnv)")
                    }

                    fragment.outputBlock("return try swiftTask(env: _javaEnv) { _javaEnv, _vm in", closeWith: "}") {
                        let callBlock: (() -> Void) -> Void
                        if method.isMutating {
                            let _selfExpression = selfExpression
                            callBlock = { body in
                                fragment.outputBlock("return try \(_selfExpression) { mutatingSelf, _javaEnv in", closeWith: "}") {
                                    body()
                                }
                            }
                            selfExpression = "mutatingSelf"
                        } else if !method.isStatic {
                            let _selfExpression = selfExpression
                            callBlock = { body in
                                if resolved is TranslatedProtocol,
                                   method.isDefaultImplementation {
                                    fragment.outputBlock("let _swiftThis = \(betterType.nonNamespacedName)_sans_\(method.callName)(wrapped:", closeWith: ")") {
                                        fragment.output("try \(_selfExpression)")
                                    }
                                } else {
                                    fragment.output("let _swiftThis = try \(_selfExpression)")
                                }
                                body()
                            }
                            selfExpression = "_swiftThis"
                        } else {
                            callBlock = { $0() }
                        }

                        callBlock {
                            fragment.outputBlock("let value: \(returnType.converterType.name).SwiftType =", closeWith: "") {
                                fragment.outputBlock("try await _javaEnv.withRelinquishedJVMThread(jvm: _vm) {") {
                                    fragment.outputBlock("\(method.isThrowing ? "try " : "")\(method.isAsync ? "await " : "")\(selfExpression)\(callName)(", closeWith: ")") {
                                        fragment.outputMap(method.parameters, separator: ",") { formal in
                                            (formal.label.map { "\($0): "} ?? "") + formal.name
                                        }
                                    }
                                }
                            }
                            fragment.output("return try \(returnType.converterType.name).toJavaObject(value, env: _javaEnv)")
                        }
                    }
                } else {
                    var mutateBlock: (() -> Void) -> Void = { $0() }
                    if method.isMutating {
                        mutateBlock = { body in
                            fragment.outputBlock("return try \(converterNamespace).mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in", closeWith: "}") {
                                body()
                            }
                        }
                        selfExpression = "mutatingSelf"
                    }

                    mutateBlock {
                        let body = {
                            if resolved is TranslatedProtocol,
                               method.isDefaultImplementation {
                                fragment.outputBlock("\(method.isThrowing ? "try " : "")\(betterType.nonNamespacedName)_sans_\(method.callName)(wrapped:", closeWith: ")", newLineTerminated: false) {
                                    fragment.output("try \(selfExpression)")
                                }
                                fragment.outputBlock("\(callName)(", newLineTerminated: false) {
                                    fragment.outputMap(method.parameters, separator: ",") { formal in
                                        let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                        return (formal.label.map { "\($0): " } ?? "") +
                                        "try \(resolved.converterType.name).fromJava(\(formal.name), env: _javaEnv)"
                                    }
                                }
                            } else {
                                fragment.outputBlock("\(method.isThrowing ? "try " : "")\(method.isAsync ? "await ": "")\(selfExpression)\(callName)(", newLineTerminated: false) {
                                    fragment.outputMap(method.parameters, separator: ",") { formal in
                                        let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                        return (formal.label.map { "\($0): " } ?? "") +
                                        "try \(resolved.converterType.name).fromJava(\(formal.name), env: _javaEnv)"
                                    }
                                }
                            }
                        }
                        if exportAnnotation.noReturn {
                            body()
                            fragment.output()
                        } else {
                            fragment.outputBlock("return try \(returnType.converterType.name).toJava(") {
                                body()
                                fragment.output(",")
                                fragment.output("env: _javaEnv")
                            }
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func translate(field: Field, context: FishyJoesContext, type: SourceryType) -> [SourceFragment] {
        guard let exportAnnotation = field.exportAnnotation else {
            return []
        }

        var selfExpression: String

        let betterType = BetterType(named: type, context: context)
        let sourceResolved = context.resolve(type: betterType)
        let sourceTypeName = sourceResolved.sourceType.name
        let converterTypeName = sourceResolved.converterType.name

        let shouldWrap = type.kind == .protocol && field.isDefaultImplementation

        let kotlinName = exportAnnotation.name
        let jvmGetName = shouldWrap ? "__jni__default_\(kotlinName)" : "__jni_\(exportAnnotation.kind == .asMethod ? "" : "get_")\(kotlinName)"
        let jvmSetName = "__jni_set_\(kotlinName)"

        if field.isStatic {
            selfExpression = sourceTypeName
        } else {
            selfExpression = "\(converterTypeName).fromJava(_javaThis, env: _javaEnv)"
        }

        if shouldWrap {
            selfExpression = "try \(context.module.name)_CommonInterface.\(sourceResolved.sourceType.nonNamespacedName)_sans_\(field.name)(wrapped: \(selfExpression))"
        }

        let cGetName = "java_get_\(sourceTypeName)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")
        let cSetName = "java_set_\(sourceTypeName)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")

        let fragment = context.swiftFragment(
            "JavaInterface/\(sourceTypeName)+java-methods.swift",
            additionalImports: ["Foundation", "FishyJoesJavaRuntime", "\(context.module.name)_CommonInterface"]
        )

        let resolved = context.resolve(type: field.type)

        let jniSignature = resolved.jniType.asSignature
        let converterName = resolved.converterType.name
        let cType = "\(converterName).CType"

        // Getter
        var formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>")
        ]
        if shouldWrap {
            formals.append((name: "_javaCompanionThis", type: "jobject"))
        }
        formals.append((name: "_javaThis", type: "jobject"))

        let className = javaClassName(sourceResolved.kotlinName, in: context)
        allMethods[sourceTypeName, default: []].insert(MethodInfo(javaName: jvmGetName, signature: "(\(shouldWrap ? "L\(className);" : "" ))" + jniSignature, cName: cGetName, isProtocolDefault: shouldWrap))
        fragment.output("// Generated by FishyJoes for `\(sourceTypeName).\(field.name)`")
        if let deprecation = field.deprecation {
            fragment.output(deprecation.swiftDeprecation)
        }
        fragment.outputBlock("let \(cGetName): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(cType) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                let value = "\(selfExpression).\(field.name)"
                fragment.output("try \(converterName).toJava(\(value), env: _javaEnv)")
            }
        }

        // Setter
        if field.isPubliclyWritable {
            let formals = [
                (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
                (name: "_javaThis", type: "jobject"),
                (name: "newValue", type: cType),
            ]
            allMethods[sourceTypeName, default: []].insert(MethodInfo(javaName: jvmSetName, signature: "(\(jniSignature))V", cName: cSetName, isProtocolDefault: false))
            if let deprecation = field.deprecation {
                fragment.output(deprecation.swiftDeprecation)
            }
            fragment.outputBlock("let \(cSetName): @convention(c) (", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",", \.type)
            }
            fragment.outputBlock(" -> Void = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
                fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                    if field.isStatic {
                        fragment.output("\(selfExpression).\(field.name) = try \(converterName).fromJava(newValue, env: _javaEnv)")
                    } else {
                        fragment.outputBlock("try \(sourceTypeName).mutateJava(_javaThis, env: _javaEnv) { value in", closeWith: "}") {
                            fragment.output("value.\(field.name) = try \(converterName).fromJava(newValue, env: _javaEnv)")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func setupFragments(context: FishyJoesContext, generatedTypes: [BetterType]) -> [SourceFragment] {
        let typeSetupFragment = context.swiftFragment(
            "JavaInterface/TypeSetup.swift",
            withDedicatedFile: true,
            additionalImports: ["Foundation", "FishyJoesJavaRuntime", "\(context.module.name)_CommonInterface"]
        )

        var usedMethods: Set<String> = []

        typeSetupFragment.output("@available(*, deprecated, message: \"Not actually deprecated, but this silences warnings because it may refer to deprecated methods\")")
        typeSetupFragment.output("@_cdecl(\"JNI_OnLoad\")")
        typeSetupFragment.outputBlock("public func jniOnLoad(vm: UnsafeMutablePointer<JavaVM?>, reserved: UnsafeMutableRawPointer) -> jint {") {
            typeSetupFragment.output("var envRaw: UnsafeMutableRawPointer?")
            typeSetupFragment.outputBlock("guard vm.pointee!.pointee.GetEnv(vm, &envRaw, JNI_VERSION_1_4) == JNI_OK else {") {
                typeSetupFragment.output("fatalError(\"Couldn't obtain jvm environment\")")
            }
            typeSetupFragment.output("let env = UnsafeMutablePointer<JNIEnv?>(OpaquePointer(envRaw))")
            typeSetupFragment.outputBlock("let result = FishyJoesJavaRuntime.callbackBody(env!) { (env) -> jint? in", closeWith: "}") {
                typeSetupFragment.output("let bag = CStringBag()")
                for type in generatedTypes {
                    let resolved = context.resolve(type: type)
                    typeSetupFragment.output("// print(\"setting up \(resolved.converterType.name)...\")")
                    typeSetupFragment.output("try \(resolved.converterType.name).javaSetup(env: env)")
                    if case .named = type {
                        if let nativeMethods = allMethods[resolved.sourceType.name]?.sorted(by: { $0.javaName < $1.javaName }) {
                            // check for defaults here
                            let protocolDefaultMethodInfos = nativeMethods.filter { $0.isProtocolDefault }
                            let normalMethodInfos = nativeMethods.filter { !$0.isProtocolDefault }

                            if resolved is TranslatedProtocol,
                               !protocolDefaultMethodInfos.isEmpty {
                                typeSetupFragment.outputBlock("try env.RegisterNatives(", closeWith: ")") {
                                    typeSetupFragment.output("\(resolved.converterType.name).externalCompanionClass", newLineTerminated: false)
                                    for methodInfo in protocolDefaultMethodInfos {
                                            typeSetupFragment.output(",")
                                            typeSetupFragment.outputBlock("JNINativeMethod(", newLineTerminated: false) {
                                                typeSetupFragment.output("name: bag.add(\"\(methodInfo.javaName)\"),")
                                                typeSetupFragment.output("signature: bag.add(\"\(methodInfo.signature)\"),")
                                                typeSetupFragment.output("fnPtr: unsafeBitCast(\(methodInfo.cName), to: UnsafeMutableRawPointer.self)")
                                            }
                                    }
                                    typeSetupFragment.output()
                                }
                            }
                            typeSetupFragment.outputBlock("try env.RegisterNatives(", closeWith: ")") {
                                let doExternalWitness = resolved is TranslatedProtocol
                                if doExternalWitness {
                                    typeSetupFragment.output("\(resolved.converterType.name).externalWitnessClass!", newLineTerminated: false)
                                } else {
                                    typeSetupFragment.output("\(resolved.converterType.name).javaClass", newLineTerminated: false)
                                }

                                for methodInfo in normalMethodInfos {
                                    typeSetupFragment.output(",")
                                    typeSetupFragment.outputBlock("JNINativeMethod(", newLineTerminated: false) {
                                        typeSetupFragment.output("name: bag.add(\"\(methodInfo.javaName)\"),")
                                        typeSetupFragment.output("signature: bag.add(\"\(methodInfo.signature)\"),")
                                        typeSetupFragment.output("fnPtr: unsafeBitCast(\(methodInfo.cName), to: UnsafeMutableRawPointer.self)")
                                    }
                                }
                                if !doExternalWitness {
                                    for methodInfo in protocolDefaultMethodInfos {
                                        typeSetupFragment.output(",")
                                        typeSetupFragment.outputBlock("JNINativeMethod(", newLineTerminated: false) {
                                            typeSetupFragment.output("name: bag.add(\"\(methodInfo.javaName)\"),")
                                            typeSetupFragment.output("signature: bag.add(\"\(methodInfo.signature)\"),")
                                            typeSetupFragment.output("fnPtr: unsafeBitCast(\(methodInfo.cName), to: UnsafeMutableRawPointer.self)")
                                        }
                                    }
                                }
                                typeSetupFragment.output()
                            }

                            usedMethods.insert(resolved.sourceType.name)
                        }
                    }
                }
                typeSetupFragment.output("return JNI_VERSION_1_4")
            }
            typeSetupFragment.output("return result ?? JNI_VERSION_1_4")
        }

        let droppedMethods = Set(allMethods.keys).subtracting(usedMethods)
        guard droppedMethods.isEmpty else {
            fatalErr("methods for \(droppedMethods) were never set up! Probably a bug.")
        }

        let module = context.module
        let repName = "\(module.name)LoaderRepresentative"
        let ktFragment = context.kotlinFragment("\(repName).kt")

        ktFragment.outputBlock("public object \(repName): LibraryLoader.LibraryRepresentative {") {
            ktFragment.output("override fun ensureLoaded() {}")

            var nativeLibs = [String]()
            nativeLibs.append(contentsOf: module.extraDynamicLibraries)
            nativeLibs.append(contentsOf: [module.name, "\(module.name)-java"])
            let listOfStr = nativeLibs.map { "\"\($0)\"" }.joined(separator: ", ")

            ktFragment.output("override val nativeLibs = listOf(\(listOfStr))")
            let deps = ["FishyJoesRuntimeRepresentative"] + module.dependencies.map { "\($0)LoaderRepresentative" }
            ktFragment.outputBlock("override val dependencies: List<LibraryLoader.LibraryRepresentative> = listOf(") {
                ktFragment.outputMap(deps, separator: ",", { $0 })
            }
            ktFragment.blankLine()
            ktFragment.outputBlock("init {") {
                ktFragment.output("LibraryLoader.loadRepresentative(this)")
            }
        }

        ktFragment.outputBlock("internal fun loadNativeLibs() {") {
            ktFragment.output("\(repName).ensureLoaded()")
        }

        let exportFragment = context.swiftFragment("JavaInterface/@_exported.swift", withDedicatedFile: true)
        exportFragment.output("@_exported import \(module.name)")
        for dependency in module.dependencies {
            exportFragment.output("@_exported import \(dependency)_JavaInterface")
        }

        return [typeSetupFragment, ktFragment, exportFragment]
    }

    func kotlin(method: Method, context: FishyJoesContext) -> KotlinClass.MethodOrVariable? {
        let exportAnnotation = method.exportAnnotation
        let omitParameters = Set(exportAnnotation.omitParameters)
        let compatParameters = Set(exportAnnotation.compatibilityOrder)

        var parameters: [(labelComment: String?, name: String, KotlinClass.KType, String?)] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                continue
            }
            if compatParameters.contains(parameter.name) {
                precondition(
                    parameter.defaultValue != nil,
                    """
                    Can't use non-default parameter \(parameter.name) in compatibilityParameters annotation
                        context: \(context.debugContext)
                    """
                )
            }

            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            var label: String?
            if let swiftLabel = parameter.label, swiftLabel != parameter.name {
                label = swiftLabel
            }
            var defaultValue: String?
            if let swiftDefaultValue = parameter.defaultValue {
                if let kotlinDefaultValue = kotlin(value: swiftDefaultValue) {
                    defaultValue = kotlinDefaultValue
                } else {
                    context.warnMissingDefault(parameter: parameter, in: method)
                }
            }
            parameters.append((label, parameter.name, resolved.kotlinType, defaultValue))
        }

        return .method(
            KotlinClass.Method(
                documentation: method.documentation,
                isStatic: method.isStatic,
                isSuspend: method.isAsync,
                isOverride: exportAnnotation.isOverride,
                isDefaultImplementation: method.isDefaultImplementation,
                name: exportAnnotation.name,
                parameters: parameters,
                compatibilityOrder: exportAnnotation.compatibilityOrder,
                returnType: context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).kotlinType,
                deprecation: method.deprecation,
                body: nil
            )
        )
    }

    func kotlin(field: Field, context: FishyJoesContext, useNativeName: Bool = false) -> KotlinClass.MethodOrVariable? {
        let ktName: String
        var asMethod = false

        if useNativeName {
            guard field.exportAnnotation == nil else {
                fatalErr("field \(field.name) should not be annotated, as it's in a type being exported memberwise")
            }
            ktName = field.name
        } else {
            guard let exportAnnotation = field.exportAnnotation else {
                return nil
            }
            asMethod = exportAnnotation.kind == .asMethod
            ktName = exportAnnotation.name
        }
        let resolved = context.resolve(type: field.type)
        if asMethod {
            precondition(!field.isPubliclyWritable, "\(context.debugContext): Can't export mutable fields as methods: \(field.name)")
            return .method(
                KotlinClass.Method(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isSuspend: field.isAsync,
                    isOverride: field.isOverride,
                    isDefaultImplementation: field.isDefaultImplementation,
                    name: ktName,
                    parameters: [],
                    compatibilityOrder: [],
                    returnType: resolved.kotlinType,
                    deprecation: field.deprecation,
                    body: nil
                )
            )
        } else {
            if field.isAsync {
                fatalError(
                    """
                        Field \(field.name) is isolated or async.
                        No direct version of async properties exists in kotlin.
                        Maybe use exportAsMethod instead?
                        context: \(context.debugContext)
                        """
                )
            }
            return .variable(
                KotlinClass.Variable(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.isOverride,
                    isMutable: field.isMutable,
                    isPubliclyWritable: field.isPubliclyWritable,
                    isDefaultImplementation: field.isDefaultImplementation,
                    name: ktName,
                    type: resolved.kotlinType,
                    deprecation: field.deprecation
                )
            )
        }
    }

    // Very hacky. But values are an entirely separate language to what we process
    func kotlin(value: String) -> String? {
        if let int = Int(value) {
            return "\(int)"
        }
        if let double = Double(value) {
            return "\(double)"
        }
        switch value {
        case "Double.ulpOfOne.squareRoot()":
            return "1.4901161193847656E-8"
        case "Int8.min":
            return String(Int8.min)
        case "Int8.max":
            return String(Int8.max)
        case "Int16.min":
            return String(Int16.min)
        case "Int16.max":
            return String(Int16.max)
        case "Int32.min":
            return String(Int32.min)
        case "Int32.max":
            return String(Int32.max)
        case "Int64.min":
            return String(Int64.min)
        case "Int64.max":
            return String(Int64.max)
        case "Int.min":
            return String(Int.min)
        case "Int.max":
            return String(Int.max)
        case "UInt8.min":
            return String(UInt8.min)
        case "UInt8.max":
            return String(UInt8.max)
        case "UInt16.min":
            return String(UInt16.min)
        case "UInt16.max":
            return String(UInt16.max)
        case "UInt32.min":
            return String(UInt32.min)
        case "UInt32.max":
            return String(UInt32.max)
        case "UInt64.min":
            return String(UInt64.min)
        case "UInt64.max":
            return String(UInt64.max)
        case "UInt.min":
            return String(UInt.min)
        case "UInt.max":
            return String(UInt.max)
        case "true", "false":
            return value
        case "nil":
            return "null"
        default:
            return nil
        }
    }

    func conform(_ kotlinClass: KotlinClass, to translatedProtocol: TranslatedProtocol, context: FishyJoesContext) {
        kotlinClass.conformances.insert(translatedProtocol.kotlinType)

        let protoDefs = Set(
            translatedProtocol.methods.compactMap { context.kotlin(method: $0).map(OverrideSignature.init) } +
            translatedProtocol.fields.compactMap { context.kotlin(field: $0).map(OverrideSignature.init) }
        )

        kotlinClass.methods = kotlinClass.methods.map { method in
            var modified = method
            if protoDefs.contains(OverrideSignature(.method(method))) {
                modified.isOverride = true
            }
            return modified
        }
        kotlinClass.fields = kotlinClass.fields.map { field in
            var modified = field
            if protoDefs.contains(OverrideSignature(.variable(field))) {
                modified.isOverride = true
            }
            return modified
        }
        if let product = kotlinClass as? KotlinProductClass {
            product.fields = product.fields.map { field in
                var modified = field
                if protoDefs.contains(OverrideSignature(.variable(field))) {
                    modified.isOverride = true
                }
                return modified
            }
            if case let .`public`(constructorFields, constructorArguments) = product.constructor {
                let overriddenConstructorFields = constructorFields.map { field in
                    var modified = field
                    if protoDefs.contains(OverrideSignature(.variable(field))) {
                        modified.isOverride = true
                    }
                    return modified
                }

                product.constructor = .public(fields: overriddenConstructorFields, arguments: constructorArguments)
            }
        }
    }
}

extension KotlinClass {
    func conforming(to protocols: [TranslatedProtocol], context: FishyJoesContext) -> KotlinClass {
        protocols.reduce(into: self) { kClass, proto in
            context.kotlinTranslator.conform(kClass, to: proto, context: context)
        }
    }
}

private struct OverrideSignature: Hashable {
    let isStatic: Bool
    let name: String
    let parameters: [KotlinClass.KType]?
    let returnType: KotlinClass.KType
    init(_ methodOrVar: KotlinClass.MethodOrVariable) {
        switch methodOrVar {
        case .method(let method):
            isStatic = method.isStatic
            name = method.name
            parameters = method.parameters.map(\.2)
            returnType = method.returnType
        case .variable(let variable):
            isStatic = variable.isStatic
            name = variable.name
            parameters = nil
            returnType = variable.type
        }
    }
}
