import Foundation
import SourceryRuntime

final class KotlinTranslator: Translator {
    required init() {}

    func javaClassName(_ name: String, in context: FishyJoesContext) -> String {
        "com/cricut/\(context.module.name.lowercased())/\(name.replacingOccurrences(of: ".", with: "$"))"
    }

    var allMethods: [String: [(javaName: String, signature: String, cName: String)]] = [:]

    func translate(method: Method, context: FishyJoesContext) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            let resolved = context.resolve(type: selfType)
            containingNamespace = resolved.sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(resolved.converterType.name).fromJava(_javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ] + method.parameters.map { parameter in
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            return (name: parameter.name, type: resolved.converterType.name + ".CType")
        }
        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["Foundation", "FishyJoesJavaRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        var jniSignature = ""
        for parameter in method.parameters {
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            jniSignature += resolved.jniType.asSignature
        }
        let returnType = context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides)
        let returnSignature = "\(returnType.converterType.name).CType"
        jniSignature = "(\(jniSignature))\(returnType.jniType.asSignature)"

        let cMethod = "java_\(containingNamespace)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")
        allMethods[containingNamespace, default: []].append(("__jni_\(exportAnnotation.name)", jniSignature, cMethod))
        fragment.outputBlock("let \(cMethod): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(returnSignature) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"

                // let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })
                var mutateBlock: (() -> Void) -> Void = { $0() }
                if method.isMutating {
                    fragment.output("var mutatingSelf = try \(selfExpression)")
                    mutateBlock = { body in
                        fragment.outputBlock("return try \(containingNamespace).mutateJava(_javaThis, env: _javaEnv) { mutatingSelf in", closeWith: "}") {
                            body()
                        }
                    }
                    selfExpression = "mutatingSelf"
                }

                mutateBlock {
                    fragment.outputBlock("return try \(returnType.converterType.name).toJava(") {
                        fragment.outputBlock("\(selfExpression)\(callName)(", closeWith: "),") {
                            fragment.outputMap(method.parameters, separator: ",") { formal in
                                let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                                return (formal.label.map { "\($0): " } ?? "") +
                                    "try \(resolved.converterType.name).fromJava(\(formal.name), env: _javaEnv)"
                            }
                        }
                        fragment.output("env: _javaEnv")
                    }
                }
            }
        }

        return [fragment]
    }

    func translate(variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {
            return []
        }
        let kotlinName = exportAnnotation.name
        let jvmGetName = "__jni_\(exportAnnotation.kind == .asMethod ? "" : "get_")\(kotlinName)"
        let jvmSetName = "__jni_set_\(kotlinName)"

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace).fromJava(_javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module.name
            selfExpression = context.module.name
        }

        let cGetName = "java_get_\(containingNamespace)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")
        let cSetName = "java_set_\(containingNamespace)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")

        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["Foundation", "FishyJoesJavaRuntime"]
        )

        let resolved = context.resolve(type: variable.typeName.better)
        let jniSignature = resolved.jniType.asSignature
        let converterName = resolved.converterType.name
        let cType = "\(converterName).CType"

        // Getter
        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ]

        allMethods[containingNamespace, default: []].append((jvmGetName, "()" + jniSignature, cGetName))
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        fragment.outputBlock("let \(cGetName): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(cType) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                fragment.output("try \(converterName).toJava(\(selfExpression).\(variable.name), env: _javaEnv)")
            }
        }

        // Setter
        if variable.isMutable, variable.accessLevel.write == .public {
            let formals = [
                (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
                (name: "_javaThis", type: "jobject"),
                (name: "newValue", type: cType),
            ]
            allMethods[containingNamespace, default: []].append((jvmSetName, "(\(jniSignature))V", cSetName))
            fragment.outputBlock("let \(cSetName): @convention(c) (", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",", \.type)
            }
            fragment.outputBlock(" -> Void = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
                fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                    if variable.isStatic {
                        fragment.output("\(selfExpression).\(variable.name) = try \(converterName).fromJava(newValue, env: _javaEnv)")
                    } else {
                        fragment.outputBlock("try \(containingNamespace).mutateJava(_javaThis, env: _javaEnv) { value in", closeWith: "}") {
                            fragment.output("value.\(variable.name) = try \(converterName).fromJava(newValue, env: _javaEnv)")
                        }
                    }
                }
            }
        }

        return [fragment]
    }

    func setupFragments(context: FishyJoesContext, generatedTypes: Set<BetterType>) -> [SourceFragment] {
        let javaTypeListFragment = context.swiftFragment(
            "JavaInterface/TypeSetup.swift",
            additionalImports: ["Foundation", "FishyJoesJavaRuntime"]
        )

        javaTypeListFragment.output("@_cdecl(\"JNI_OnLoad\")")
        javaTypeListFragment.outputBlock("public func jniOnLoad(vm: UnsafeMutablePointer<JavaVM?>, reserved: UnsafeMutableRawPointer) -> jint {") {
            javaTypeListFragment.output("var envRaw: UnsafeMutableRawPointer?")
            javaTypeListFragment.outputBlock("guard vm.pointee!.pointee.GetEnv(vm, &envRaw, JNI_VERSION_1_4) == JNI_OK else {") {
                javaTypeListFragment.output("fatalError(\"Couldn't obtain jvm environment\")")
            }
            javaTypeListFragment.output("let env = UnsafeMutablePointer<JNIEnv?>(OpaquePointer(envRaw))")
            javaTypeListFragment.outputBlock("return FishyJoesJavaRuntime.callbackBody(env!) { env in", closeWith: "}") {
                javaTypeListFragment.output("let bag = CStringBag()")
                for type in generatedTypes.sorted(by: { "\($0)" < "\($1)" }) {
                    guard type != .void else { continue }
                    let resolved = context.resolve(type: type)
                    javaTypeListFragment.output("// print(\"setting up \(resolved.converterType.name)...\")")
                    javaTypeListFragment.output("try \(resolved.converterType.name).javaSetup(env: env)")
                    if case .named = type {
                        if let nativeMethods = allMethods[type.name] {
                            javaTypeListFragment.outputBlock("try env.RegisterNatives(\(resolved.converterType.name).javaClass,", closeWith: ")") {
                                for (method, signature, cName) in nativeMethods {
                                    let isLast = cName == nativeMethods.last?.cName
                                    javaTypeListFragment.outputBlock("JNINativeMethod(", closeWith: isLast ? ")" : "),") {
                                        javaTypeListFragment.output("name: bag.add(\"\(method)\"),")
                                        javaTypeListFragment.output("signature: bag.add(\"\(signature)\"),")
                                        javaTypeListFragment.output("fnPtr: unsafeBitCast(\(cName), to: UnsafeMutableRawPointer.self)")
                                    }
                                }
                            }
                        }
                    }
                }
                javaTypeListFragment.output("return JNI_VERSION_1_4")
            }
        }

        let module = context.module
        let ktFragment = SourceFragment(
            sourceryDestination: "file:../../kotlin/src/generated/kotlin/com/cricut/\(module.name.lowercased())/loadNativeLibs.kt"
        )
        ktFragment.output("package \(module.kotlinPackage)")
        ktFragment.blankLine()
        ktFragment.output("import com.cricut.fishyjoes.runtime.LibraryLoader")
        ktFragment.blankLine()
        ktFragment.outputBlock("internal fun loadNativeLibs() {") {
            ktFragment.output("LibraryLoader.ensureLoaded(\"FishyJoesJavaRuntime\")")
            for dependency in module.dependencies {
                ktFragment.output("LibraryLoader.ensureLoaded(\"\(dependency)\")")
                ktFragment.output("LibraryLoader.ensureLoaded(\"\(dependency)-java\")")
            }
            ktFragment.output("LibraryLoader.ensureLoaded(\"\(module.name)\")")
            ktFragment.output("LibraryLoader.ensureLoaded(\"\(module.name)-java\")")
        }

        let exportFragment = SourceFragment(sourceryDestination: "file:JavaInterface/@_exported.swift")
        exportFragment.output("@_exported import \(module.name)")
        for dependency in module.dependencies {
            exportFragment.output("@_exported import \(dependency)_JavaInterface")
        }

        return [javaTypeListFragment, ktFragment, exportFragment]
    }

    func kotlin(method: Method, context: FishyJoesContext) -> KotlinClass.MethodOrVariable? {
        let exportAnnotation = method.exportAnnotation
        var omitParameters = Set(exportAnnotation.omitParameters)
        var parameters: [(labelComment: String?, name: String, KotlinClass.KType, String?)] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            var label: String?
            if let swiftLabel = parameter.label, swiftLabel != parameter.name {
                label = swiftLabel
            }
            var defaultValue: String?
            if let swiftDefaultValue = parameter.defaultValue {
                if let kotlinDefaultValue = kotlin(value: swiftDefaultValue) {
                    defaultValue = kotlinDefaultValue
                } else {
                    context.warnMissingDefault(parameter: parameter, in: method)
                }
            }
            parameters.append((label, parameter.name, resolved.kotlinType, defaultValue))
        }

        return .method(
            KotlinClass.Method(
                documentation: method.documentation,
                isStatic: method.isStatic,
                isOverride: method.exportAnnotation.isOverride,
                name: exportAnnotation.name,
                parameters: parameters,
                returnType: context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).kotlinType,
                body: nil
            )
        )
    }

    func kotlin(field: Variable, context: FishyJoesContext, useNativeName: Bool = false) -> KotlinClass.MethodOrVariable? {
        let ktName: String
        var asMethod = false

        if useNativeName {
            guard field.exportAnnotation == nil else {
                fatalErr("field \(field.name) should not be annotated, as it's in a type being exported memberwise")
            }
            ktName = field.name
        } else {
            guard let exportAnnotation = field.exportAnnotation else {
                return nil
            }
            asMethod = exportAnnotation.kind == .asMethod
            ktName = exportAnnotation.name
        }
        let resolved = context.resolve(type: field.typeName.better)
        if asMethod {
            return .method(
                KotlinClass.Method(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    name: ktName,
                    parameters: [],
                    returnType: resolved.kotlinType,
                    body: nil
                )
            )
        } else {
            return .variable(
                KotlinClass.Variable(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    readOnly: !field.isMutable,
                    name: ktName,
                    type: resolved.kotlinType
                )
            )
        }
    }

    // Very hacky. But values are an entirely separate language to what we process
    func kotlin(value: String) -> String? {
        if let int = Int(value) {
            return "\(int)"
        } else if let double = Double(value) {
            return "\(double)"
        } else if value.first == "." {
            return nil
        } else if value == "Double.ulpOfOne.squareRoot()" {
            return "1.4901161193847656E-8"
        }
        switch value {
        case "nil":
            return "null"
        case "true", "false":
            return value
        default:
            return "IDUNNO(\(value))"
        }
    }
}
