import SourceryRuntime

struct TranslatedStruct: TranslatedType {
    let sourceType: BetterType
    let cName: String
    let nodeName: String
    let globalName: String
    let globalCName: String
    let asC: String
    let asSwift: String
    let storedVariables: [Variable]
    let computedVariables: [Variable]
    let methods: [Method]
    let documentation: [String]

    init(context: FishyJoesContext, type: Type) {
        guard let exportAnnotation = type.exportAnnotation,
              let cTypeName = exportAnnotation.c else {
            fatalErr("c symbol not specified")
        }
        let nodeTypeName = exportAnnotation.js ?? cTypeName
        guard type.kind == "struct" else { fatalErr("not a struct") }

        self.sourceType = .unknown(type.name)
        self.cName = cTypeName
        self.nodeName = nodeTypeName
        self.globalName = "\(context.module).\(type.globalName)"
        self.globalCName = "CTypes.\(cName)"
        self.asC = "as\(cTypeName)"
        self.asSwift = "as\(type.localName)"

        self.storedVariables = type.storedVariables
        self.computedVariables = type.computedVariables.filter { $0.exportAnnotation != nil }

        self.methods = type.methods.filter { $0.annotations["cdecl"] != nil }
        self.documentation = type.documentation
    }

    func definitionFragments(in context: FishyJoesContext) -> [SourceFragment] {
        // Generate C version of the swift type
        let headerName = "CTypes/include/\(cName).h"
        let headerFragment = context.cHeaderFragment(headerName)

        Set(storedVariables.compactMap { storedVar in
                context.resolve(type: storedVar.typeName.better).cForwardDeclaration
            })
            .sorted()
            .forEach { headerFragment.output($0) }

        headerFragment.output("// generated by sourcery:cdecl for \(globalName)`")
        headerFragment.outputBlock("typedef struct \(cName) {", newLineTerminated: false) {
            for storedVar in storedVariables {
                let resolved = context.resolve(type: storedVar.typeName.better)
                headerFragment.output("\(resolved.cName) \(storedVar.name);")
            }
        }
        headerFragment.output(" \(cName);")

        let conversionFragment = context.swiftFragment("CInterface/\(globalName)+\(cName).swift")
        conversionFragment.outputBlock("extension \(globalName) {") {
            conversionFragment.outputBlock("var \(asC): \(globalCName) {") {
                conversionFragment.outputBlock("get {") {
                    conversionFragment.outputBlock("\(globalCName)(") {
                        conversionFragment.outputMap(storedVariables, separator: ",") { storedVar in
                            let resolved = context.resolve(type: storedVar.typeName.better)
                            return "\(storedVar.name): \(storedVar.name)\(resolved.asCAccessor)"
                        }
                    }
                }
                conversionFragment.output("set { self = newValue.\(asSwift) }")
            }
        }

        conversionFragment.output()
        conversionFragment.outputBlock("extension \(globalCName) {") {
            conversionFragment.outputBlock("var \(asSwift): \(globalName) {") {
                conversionFragment.outputBlock("get {") {
                    conversionFragment.outputBlock("\(globalName)(") {
                        conversionFragment.outputMap(storedVariables, separator: ",") { storedVar in
                            let resolved = context.resolve(type: storedVar.typeName.better)
                            return "\(storedVar.name): \(resolved.wrapAsSwift(expression: storedVar.name))"
                        }
                    }
                }
                conversionFragment.output("set { self = newValue.\(asC) }")
            }
        }

        let nodeFragment = context.swiftFragment(
            "NodeInterface/\(globalName)+node.swift",
            additionalImports: ["FishyJoesRuntime"]
        )

        nodeFragment.outputBlock("extension \(globalName): FishyJoesRuntime.NodeMutable {") {

            nodeFragment.outputBlock("public init(fromNode value: napi_value?, env: napi_env) throws {") {
                // TODO: type check
                nodeFragment.outputBlock("self.init(") {
                    nodeFragment.outputMap(storedVariables, separator: ",") { storedVar in
                        let resolved = context.resolve(type: storedVar.typeName.better)
                        return """
                            \(storedVar.name): try { () -> \(resolved.globalName) in
                                var fieldValue: napi_value?
                                try check(napi_get_named_property(env, value, \"\(storedVar.name)\", &fieldValue))
                                return try \(resolved.globalName)(fromNode: fieldValue, env: env)
                            }()
                            """
                    }
                }
            }

            nodeFragment.outputBlock("public func toNode(env: napi_env) throws -> napi_value? {") {
                nodeFragment.output("let constructor = try FishyJoesRuntime.InstanceData.data(for: env).constructor(for: \"\(nodeName)\", env: env)")
                nodeFragment.outputBlock("let args: [napi_value?] = [") {
                    for storedVar in storedVariables {
                        nodeFragment.output("try \(storedVar.name).toNode(env: env),")
                    }
                }
                nodeFragment.output("var result: napi_value?")
                nodeFragment.output("try check(napi_new_instance(env, constructor, args.count, args, &result))")
                nodeFragment.output("return result")
            }

            nodeFragment.outputBlock("public func mutateNode(this: napi_value?, env: napi_env) throws {") {
                for storedVar in storedVariables {
                    guard storedVar.isMutable else { continue }
                    nodeFragment.output("try check(napi_set_named_property(env, this, \"\(storedVar.name)\", \(storedVar.name).toNode(env: env)))")
                }
            }

            nodeFragment.outputBlock("public static func nodeSetup(env: napi_env, module: napi_value) throws {") {
                nodeFragment.output("print(\"setting up \(globalName)\")")

                nodeFragment.outputBlock("let nodeClass = try NodeClass(") {
                    nodeFragment.output("env: env,")
                    nodeFragment.output("name: \"\(nodeName)\",")
                    var properties: [String] =
                        context.nodeTranslator.properties(for: methods) +
                        context.nodeTranslator.properties(for: computedVariables)
                    for storedVar in storedVariables {
                        properties.append("\"\(storedVar.name)\": (.stored(mutable: \(storedVar.isMutable)), isStatic: \(storedVar.isStatic)),")
                    }
                    if properties.isEmpty {
                        nodeFragment.output("properties: [:],")
                    } else {
                        nodeFragment.outputBlock("properties: [", closeWith: "],") {
                            for prop in properties {
                                nodeFragment.output(prop)
                            }
                        }
                    }
                    nodeFragment.outputBlock("constructor: { env, info in", closeWith: "}") {
                        nodeFragment.outputBlock("FishyJoesRuntime.callbackBody(env, info, name: \"\(nodeName)_constructor\", expectedArgumentCount: \(storedVariables.count)) { env in", closeWith: "}") {
                            nodeFragment.output("// TODO: typecheck?")
                            nodeFragment.output("let this = try env.this()")
                            for (index, storedVar) in storedVariables.enumerated() {
                                nodeFragment.output("try check(napi_set_named_property(env.env, this, \"\(storedVar.name)\", env.argument(at: \(index))))")
                            }
                            nodeFragment.output("return this")
                        }
                    }
                }
                nodeFragment.output("try check(napi_set_named_property(env, module, \"\(nodeName)\", nodeClass.constructor.value(env: env)))")
            }
        }

        context.tsFragment.classes.append(
            .init(
                documentation: documentation,
                name: nodeName,
                fields: storedVariables.compactMap(context.ts(field:)),
                methods: methods.compactMap(context.ts(method:))
            )
        )

        return [headerFragment, conversionFragment, nodeFragment]
    }

    var asSwiftAccessor: String { ".\(asSwift)" }
    var asCAccessor: String { ".\(asC)" }

    var cForwardDeclaration: String? { "#include \"\(cName).h\"" }
}
