import SourceryRuntime

struct TranslatedReference: TranslatedType {
    let sourceType: BetterType
    let concreteStructName: String
    let cName: String
    let nodeName: String
    let globalName: String
    let globalCName: String
    let asCAccessor: String
    let cForwardDeclaration: String?
    let methods: [Method]
    let computedVariables: [Variable]
    let documentation: [String]

    func wrapAsSwift(expression: String) -> String {
        // TODO
        "Swift.UnsafeMutablePointer<\(globalName)>(\(expression)).pointee"
    }

    init(context: FishyJoesContext, type: Type) {
        guard let exportAnnotation = type.exportAnnotation,
              let cTypeName = exportAnnotation.c else {
            fatalErr("c symbol not specified")
        }
        let nodeName = exportAnnotation.js ?? cTypeName

        self.sourceType = .unknown(type.name)
        self.concreteStructName = cTypeName
        self.cName = "\(cTypeName)Ref"
        self.nodeName = nodeName
        self.globalName = "\(context.module).\(type.globalName)"
        self.globalCName = "CTypes.\(cName)"
        self.asCAccessor = ".as\(cTypeName)"
        self.cForwardDeclaration = "#include \"\(cTypeName).h\""
        self.methods = type.methods.filter { $0.exportAnnotation != nil }
        self.computedVariables = type.variables.filter { $0.exportAnnotation != nil }
        self.documentation = type.documentation
    }

    func definitionFragments(in context: FishyJoesContext) -> [SourceFragment] {
        let headerName = "CTypes/include/\(concreteStructName).h"
        let headerFragment = context.cHeaderFragment(headerName)

        headerFragment.output("// generated by sourcery:cdecl for \(globalName)`")
        headerFragment.output("struct \(concreteStructName);")
        headerFragment.output("typedef struct \(concreteStructName) * _Nonnull \(cName);")

        let conversionFragment = context.swiftFragment("CInterface/\(globalName)+\(cName).swift")
        // NOTE: globalCName is a typealias to Swift.OpaquePointer. Don't extend it.
        conversionFragment.outputBlock("extension \(globalName) {") {
            conversionFragment.outputBlock("var as\(concreteStructName): \(globalCName) {") {
                conversionFragment.outputBlock("get {") {
                    conversionFragment.output("let pointer = Swift.UnsafeMutablePointer<\(globalName)>.allocate(capacity: 1)")
                    conversionFragment.output("pointer.pointee = self")
                    conversionFragment.output("// TODO: figure out memory conventions")
                    conversionFragment.output("return .init(pointer)")
                }
                conversionFragment.outputBlock("set {") {
                    conversionFragment.output("self = \(wrapAsSwift(expression: "newValue"))")
                }
            }
        }

        let nodeFragment = context.swiftFragment(
            "NodeInterface/\(globalName)+node.swift",
            additionalImports: ["FishyJoesRuntime"]
        )
        nodeFragment.outputBlock("extension \(globalName): FishyJoesRuntime.NodeConvertible {") {
            nodeFragment.outputBlock("public init(fromNode value: napi_value?, env: napi_env) throws {") {
                nodeFragment.output("var pointer: UnsafeMutableRawPointer?")
                nodeFragment.output("try check(napi_unwrap(env, value, &pointer))")
                nodeFragment.outputBlock("guard let pointer = pointer else {") {
                    nodeFragment.output("throw JSException(message: \"expected \(globalName), got nil\")")
                }
                nodeFragment.output("self = Box<\(globalName)>.takeUnretainedOpaque(pointer).value")
            }
            nodeFragment.outputBlock("public func toNode(env: napi_env) throws -> napi_value? {") {
                nodeFragment.output("let constructor = try FishyJoesRuntime.InstanceData.data(for: env).constructor(for: \"\(nodeName)\", env: env)")
                nodeFragment.output("var args: napi_value? = try FishyJoesRuntime.Box(self).retainedExternal(env: env)")
                nodeFragment.output("var result: napi_value?")
                nodeFragment.output("try check(napi_new_instance(env, constructor, 1, &args, &result))")
                nodeFragment.output("return result")
            }
            nodeFragment.outputBlock("public static func nodeSetup(env: napi_env, module: napi_value) throws {") {
                nodeFragment.output("print(\"setting up \(globalName)\")")

                nodeFragment.outputBlock("let nodeClass = try NodeClass(") {
                    nodeFragment.output("env: env,")
                    nodeFragment.output("name: \"\(nodeName)\",")
                    let properties: [String] =
                        context.nodeTranslator.properties(for: methods) +
                        context.nodeTranslator.properties(for: computedVariables)
                    if properties.isEmpty {
                        nodeFragment.output("properties: [:],")
                    } else {
                        nodeFragment.outputBlock("properties: [", closeWith: "],") {
                            for prop in properties {
                                nodeFragment.output(prop)
                            }
                        }
                    }
                    nodeFragment.outputBlock("constructor: { env, info in", closeWith: "}") {
                        nodeFragment.outputBlock("FishyJoesRuntime.callbackBody(env, info, name: \"\(nodeName)_constructor\", expectedArgumentCount: 1) { env in", closeWith: "}") {
                            nodeFragment.output("// TODO: typecheck?")
                            nodeFragment.output("let this = try env.this()")
                            nodeFragment.output("let selfValue = try env.argument(at: 0)")
                            nodeFragment.output("let boxed = try FishyJoesRuntime.Box<\(globalName)>.takeRetained(selfValue, env: env.env)")
                            nodeFragment.outputBlock("let finalizer: napi_finalize = { env, data, _ in", closeWith: "}") {
                                nodeFragment.output("FishyJoesRuntime.Box<\(globalName)>.releaseOpaque(data)")
                            }
                            nodeFragment.output("try check(env: env.env, napi_wrap(env.env, this, boxed.retainedOpaque(), finalizer, nil, nil))")
                            nodeFragment.output("return this")
                        }
                    }
                }
                nodeFragment.output("try check(napi_set_named_property(env, module, \"\(nodeName)\", nodeClass.constructor.value(env: env)))")
            }
        }

        context.tsFragment.classes.append(
            .init(
                documentation: documentation,
                name: nodeName,
                fields: computedVariables.compactMap(context.ts(field:)),
                methods: methods.compactMap(context.ts(method:))
            )
        )

        return [headerFragment, conversionFragment, nodeFragment]
    }
}
