import SourceryRuntime

struct TranslatedStruct: TranslatedType {
    let sourceType: BetterType
    let cName: String
    let globalName: String
    let globalCName: String
    let asC: String
    let asSwift: String
    let storedVariables: [Variable]

    init(context: CDeclareContext, type: Type) {
        guard let cTypeName = type.annotations["cdecl"] as? String else { fatalErr("cdecl symbol not specified") }
        guard type.kind == "struct" else { fatalErr("not a struct") }

        self.sourceType = .unknown(type.name)
        self.cName = cTypeName
        self.globalName = "\(context.module).\(type.globalName)"
        self.globalCName = "CTypes.\(cName)"
        self.asC = "as\(cTypeName)"
        self.asSwift = "as\(type.localName)"

        let omitVariables = ((type.annotations["cdecl.omitVariables"] as? String).map { Set($0.components(separatedBy: " ")) }) ?? []
        self.storedVariables = type.storedVariables.filter { !omitVariables.contains($0.name) }
    }

    func definitionFragments(in context: CDeclareContext) -> [SourceFragment] {
        // Generate C version of the swift type
        let headerName = "CTypes/include/\(cName).h"
        let headerFragment = context.cHeaderFragment(headerName)

        Set(storedVariables.compactMap { storedVar in
                context.resolve(type: storedVar.typeName.better).cForwardDeclaration
            })
            .sorted()
            .forEach { headerFragment.output($0) }

        headerFragment.output("// generated by sourcery:cdecl for \(globalName)`")
        headerFragment.outputBlock("typedef struct \(cName) {", newLineTerminated: false) {
            for storedVar in storedVariables {
                let resolved = context.resolve(type: storedVar.typeName.better)
                headerFragment.output("\(resolved.cName) \(storedVar.name);")
            }
        }
        headerFragment.output(" \(cName);")

        let conversionFragment = context.swiftFragment("CInterface/\(globalName)+\(cName).swift")
        conversionFragment.outputBlock("extension \(globalName) {") {
            conversionFragment.outputBlock("var \(asC): \(globalCName) {") {
                conversionFragment.outputBlock("get {") {
                    conversionFragment.outputBlock("\(globalCName)(") {
                        conversionFragment.outputMap(storedVariables, separator: ",") { storedVar in
                            let resolved = context.resolve(type: storedVar.typeName.better)
                            return "\(storedVar.name): \(storedVar.name)\(resolved.asCAccessor)"
                        }
                    }
                }
                conversionFragment.output("set { self = newValue.\(asSwift) }")
            }
        }

        conversionFragment.output()
        conversionFragment.outputBlock("extension \(globalCName) {") {
            conversionFragment.outputBlock("var \(asSwift): \(globalName) {") {
                conversionFragment.outputBlock("get {") {
                    conversionFragment.outputBlock("\(globalName)(") {
                        conversionFragment.outputMap(storedVariables, separator: ",") { storedVar in
                            let resolved = context.resolve(type: storedVar.typeName.better)
                            return "\(storedVar.name): \(resolved.wrapAsSwift(expression: storedVar.name))"
                        }
                    }
                }
                conversionFragment.output("set { self = newValue.\(asC) }")
            }
        }

        return [headerFragment, conversionFragment]
    }

    var asSwiftAccessor: String { ".\(asSwift)" }
    var asCAccessor: String { ".\(asC)" }

    var cForwardDeclaration: String? { "#include \"\(cName).h\"" }
}
