import SourceryRuntime

struct TranslatedReference: TranslatedType {
    let sourceType: BetterType
    let concreteStructName: String
    let cName: String
    let nodeName: String
    let globalName: String
    let globalCName: String
    let asCAccessor: String
    let cForwardDeclaration: String?
    let methods: [Method]
    let getters: [Variable]

    func wrapAsSwift(expression: String) -> String {
        // TODO
        "Swift.UnsafeMutablePointer<\(globalName)>(\(expression)).pointee"
    }

    init(context: CDeclareContext, type: Type) {
        guard let cTypeName = type.annotations["cdecl.referenceType"] as? String else { fatalErr("cdecl symbol not specified") }
        let nodeName = type.annotations["nodedecl"] as? String ?? cTypeName

        self.sourceType = .unknown(type.name)
        self.concreteStructName = cTypeName
        self.cName = "\(cTypeName)Ref"
        self.nodeName = nodeName
        self.globalName = "\(context.module).\(type.globalName)"
        self.globalCName = "CTypes.\(cName)"
        self.asCAccessor = ".as\(cTypeName)"
        self.cForwardDeclaration = "#include \"\(cTypeName).h\""
        self.methods = type.methods.filter { $0.annotations["cdecl"] != nil }
        self.getters = type.variables.filter { $0.annotations["cdecl.get"] != nil }
    }

    func definitionFragments(in context: CDeclareContext) -> [SourceFragment] {
        let headerName = "CTypes/include/\(concreteStructName).h"
        let headerFragment = context.cHeaderFragment(headerName)

        headerFragment.output("// generated by sourcery:cdecl for \(globalName)`")
        headerFragment.output("struct \(concreteStructName);")
        headerFragment.output("typedef struct \(concreteStructName) * _Nonnull \(cName);")

        let conversionFragment = context.swiftFragment("CInterface/\(globalName)+\(cName).swift")
        // NOTE: globalCName is a typealias to Swift.OpaquePointer. Don't extend it.
        conversionFragment.outputBlock("extension \(globalName) {") {
            conversionFragment.outputBlock("var as\(concreteStructName): \(globalCName) {") {
                conversionFragment.outputBlock("get {") {
                    conversionFragment.output("let pointer = Swift.UnsafeMutablePointer<\(globalName)>.allocate(capacity: 1)")
                    conversionFragment.output("pointer.pointee = self")
                    conversionFragment.output("// TODO: figure out memory conventions")
                    conversionFragment.output("return .init(pointer)")
                }
                conversionFragment.outputBlock("set {") {
                    conversionFragment.output("self = \(wrapAsSwift(expression: "newValue"))")
                }
            }
        }

        let nodeFragment = context.swiftFragment(
            "NodeInterface/\(globalName)+node.swift",
            additionalImports: ["NodeUtils"]
        )
        nodeFragment.outputBlock("extension \(globalName): NodeUtils.NodeConvertible {") {
            nodeFragment.outputBlock("public static func nodeSetup(env: napi_env, module: napi_value) throws {") {
                nodeFragment.output("print(\"setting up \(globalName)\")")
                nodeFragment.output("var constructor: napi_value?")
                nodeFragment.output("var undefined: napi_value?")
                nodeFragment.output("try check(napi_get_undefined(env, &undefined))")
                nodeFragment.outputBlock("let properties: [napi_property_descriptor] = [") {
                    for method in methods {
                        guard let cName = method.annotations["cdecl"] as? String else { continue }
                        let nodeName = method.annotations["nodedecl"] as? String ?? cName
                        let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })
                        if isMutating {
                            // TODO: do
                            continue
                        }

                        nodeFragment.outputBlock("napi_property_descriptor(", closeWith: "),") {
                            nodeFragment.output("utf8name: nil, name: try \"\(nodeName)\".toNode(env: env),")
                            nodeFragment.output("method: node_\(cName), getter: nil, setter: nil, value: nil,")
                            if method.isStatic {
                                nodeFragment.output("attributes: napi_static,")
                            } else {
                                nodeFragment.output("attributes: napi_default,")
                            }
                            nodeFragment.output("data: nil")
                        }
                    }

                    for getter in getters {
                        guard let cName = getter.annotations["cdecl.get"] as? String else { continue }
                        let nodeName = getter.annotations["nodedecl"] as? String ?? cName

                        nodeFragment.outputBlock("napi_property_descriptor(", closeWith: "),") {
                            nodeFragment.output("utf8name: nil, name: try \"\(nodeName)\".toNode(env: env),")
                            nodeFragment.output("method: nil, getter: node_\(cName), setter: nil, value: nil,")
                            if getter.isStatic {
                                nodeFragment.output("attributes: napi_static,")
                            } else {
                                nodeFragment.output("attributes: napi_default,")
                            }
                            nodeFragment.output("data: nil")
                        }
                    }
                }
                nodeFragment.outputBlock("try check(napi_define_class(", closeWith: "))") {
                    nodeFragment.output("env,")
                    nodeFragment.output("\"\(nodeName)\", -1,")
                    nodeFragment.outputBlock("{ env, info in", closeWith: "},") {
                        nodeFragment.outputBlock("NodeUtils.callbackBody(env, info, name: \"\(nodeName)_constructor\", expectedArgumentCount: 1) { env in", closeWith: "}") {
                            nodeFragment.output("// TODO: typecheck?")
                            nodeFragment.output("let this = try env.this()")
                            nodeFragment.output("let selfValue = try env.argument(at: 0)")
                            nodeFragment.output("let boxed = try NodeUtils.Box<\(globalName)>.takeRetained(selfValue, env: env.env)")
                            nodeFragment.outputBlock("let finalizer: napi_finalize = { env, data, _ in", closeWith: "}") {
                                nodeFragment.output("NodeUtils.Box<\(globalName)>.releaseOpaque(data)")
                            }
                            nodeFragment.output("try check(env: env.env, napi_wrap(env.env, this, boxed.retainedOpaque(), finalizer, nil, nil))")
                            nodeFragment.output("return this")
                        }
                    }
                    nodeFragment.output("nil,")
                    nodeFragment.output("properties.count, properties,")
                    nodeFragment.output("&constructor")
                }
                nodeFragment.output("try NodeUtils.InstanceData.data(for: env).constructors[\"\(nodeName)\"] = NodeUtils.Reference(env: env, value: constructor)")
                nodeFragment.output("try check(napi_set_named_property(env, module, \"\(nodeName)\", constructor))")
            }

            nodeFragment.outputBlock("public init(fromNode value: napi_value?, env: napi_env) throws {") {
                // nodeFragment.output("self = try NodeUtils.Box<\(globalName)>.takeUnretained(value, env: env).value")
                nodeFragment.output("var pointer: UnsafeMutableRawPointer?")
                nodeFragment.output("try check(napi_unwrap(env, value, &pointer))")
                nodeFragment.outputBlock("guard let pointer = pointer else {") {
                    nodeFragment.output("throw JSException(message: \"expected \(globalName), got nil\")")
                }
                nodeFragment.output("self = Box<\(globalName)>.takeUnretainedOpaque(pointer).value")
            }
            nodeFragment.outputBlock("public func toNode(env: napi_env) throws -> napi_value? {") {
                nodeFragment.output("let constructor = try NodeUtils.InstanceData.data(for: env).constructor(for: \"\(nodeName)\", env: env)")
                nodeFragment.output("var args: napi_value? = try NodeUtils.Box(self).retainedExternal(env: env)")
                nodeFragment.output("var result: napi_value?")
                nodeFragment.output("try check(napi_new_instance(env, constructor, 1, &args, &result))")
                nodeFragment.output("return result")
            }
        }

        context.tsFragment.classes.append(
            .init(
                name: nodeName,
                fields: getters.compactMap { getter in
                    guard let nodeName = getter.annotations["nodedecl"] as? String ?? getter.annotations["cdecl.get"] as? String else { return nil }
                    let resolved = context.resolve(type: getter.typeName.better)
                    return TypeScriptAnnotations.Variable(readOnly: true, name: nodeName, type: resolved.nodeType)
                },
                methods: methods.compactMap(context.ts(method:))
            )
        )

        return [headerFragment, conversionFragment, nodeFragment]
    }
}
