import SourceryRuntime

struct TranslatedEnum: TranslatedType {
    let sourceType: BetterType
    let cName: String
    let globalName: String
    let globalCName: String
    let asC: String
    let asSwift: String
    let enumType: Enum

    init(context: CDeclareContext, type: Enum) {
        guard let cTypeName = type.annotations["cdecl"] as? String else { fatalErr("cdecl symbol not specified") }

        self.sourceType = .unknown(type.name)
        self.cName = cTypeName
        self.globalName = "\(context.module).\(type.globalName)"
        self.globalCName = "CTypes.\(cName)"
        self.asC = "as\(cTypeName)"
        self.asSwift = "as\(type.localName)"
        self.enumType = type
    }

    func definitionFragments(in context: CDeclareContext) -> [SourceFragment] {
        // Generate C version of the swift type
        let headerName = "CTypes/include/\(cName).h"
        let headerFragment = context.cHeaderFragment(headerName)

        Set(enumType.cases.flatMap(\.associatedValues).compactMap { value in
                context.resolve(type: value.typeName.better).cForwardDeclaration
            })
            .sorted()
            .forEach { headerFragment.output($0) }

        headerFragment.output("// generated by sourcery:cdecl for \(globalName)`")
        if !enumType.hasAssociatedValues {
            headerFragment.outputBlock("typedef enum \(cName) {", newLineTerminated: false) {
                headerFragment.outputMap(enumType.cases.enumerated(), separator: ",") { indexed in
                    "\(cName)_\(indexed.element.name) = \(indexed.offset)"
                }
            }
            headerFragment.output(" \(cName);")
        } else {
            headerFragment.outputBlock("typedef struct \(cName) {", newLineTerminated: false) {
                headerFragment.outputBlock("union {", newLineTerminated: false) {
                    for enumCase in enumType.cases {
                        headerFragment.outputBlock("struct {", newLineTerminated: false) {
                            for value in enumCase.associatedValues {
                                let resolved = context.resolve(type: value.typeName.better)
                                guard let localName = value.localName else {
                                    fatalError("expected enum case \(resolved.cName) to have a local name. Probably a bug in CDeclare")
                                }
                                headerFragment.output("\(resolved.cName) \(localName);")
                            }
                        }
                        headerFragment.output(" \(enumCase.name);")
                    }
                }
                headerFragment.output(" associatedValues;")
                headerFragment.outputBlock("enum: uint8_t {", newLineTerminated: false) {
                    headerFragment.outputMap(enumType.cases.enumerated(), separator: ",") { indexed in
                        "\(indexed.element.name) = \(indexed.offset)"
                    }
                }
                headerFragment.output(" tag;")
            }
            headerFragment.output(" \(cName);")
        }

        let conversionFragment = context.swiftFragment("CInterface/\(cName).swift")
        conversionFragment.outputBlock("extension \(globalName) {") {
            conversionFragment.outputBlock("var \(asC): \(globalCName) {") {
                conversionFragment.outputBlock("get {") {
                    if enumType.hasAssociatedValues {
                        fatalErr("TODO")
                    } else {
                        conversionFragment.outputBlock("switch self {") {
                            for enumCase in enumType.cases {
                                conversionFragment.output("case .\(enumCase.name): return \(globalCName)_\(enumCase.name)")
                            }
                        }
                    }
                }
                conversionFragment.output("set { self = newValue.\(asSwift) }")
            }
        }

        conversionFragment.output()
        conversionFragment.outputBlock("extension \(globalCName) {") {
            conversionFragment.outputBlock("var \(asSwift): \(globalName) {") {
                conversionFragment.outputBlock("get {") {
                    if enumType.hasAssociatedValues {
                        fatalErr("TODO")
                    } else {
                        conversionFragment.outputBlock("switch self {") {
                            for enumCase in enumType.cases {
                                conversionFragment.output("case \(globalCName)_\(enumCase.name): return .\(enumCase.name)")
                            }
                            conversionFragment.output("default: fatalError(\"invalid enum \\(self) for \(globalCName)\")")
                        }
                    }
                }
                conversionFragment.output("set { self = newValue.\(asC) }")
            }
        }

        let nodeFragment = context.swiftFragment(
            "NodeInterface/\(globalName)+\(cName)+node.swift",
            additionalImports: ["NodeUtils"]
        )
        nodeFragment.outputBlock("extension \(globalCName): NodeUtils.NodeConvertible {") {
            nodeFragment.outputBlock("public init(_ value: napi_value?, env: napi_env) throws {") {
                nodeFragment.output("fatalError()")
            }
        }

        return [headerFragment, conversionFragment, nodeFragment]
    }

    var asSwiftAccessor: String { ".\(asSwift)" }
    var asCAccessor: String { ".\(asC)" }

    var cForwardDeclaration: String? { "#include \"\(cName).h\"" }
}
