import SourceryRuntime

struct TranslatedReference: TranslatedType {
    let sourceType: BetterType
    let concreteStructName: String
    let cName: String
    let globalName: String
    let globalCName: String
    let asCAccessor: String
    let cForwardDeclaration: String?

    func wrapAsSwift(expression: String) -> String {
        // TODO
        "Swift.UnsafeMutablePointer<\(globalName)>(\(expression)).pointee"
    }

    init(context: CDeclareContext, type: Type) {
        guard let cTypeName = type.annotations["cdecl.referenceType"] as? String else { fatalErr("cdecl symbol not specified") }

        self.sourceType = .unknown(type.name)
        self.concreteStructName = cTypeName
        self.cName = "\(cTypeName)Ref"
        self.globalName = "\(context.module).\(type.globalName)"
        self.globalCName = "CTypes.\(cName)"
        self.asCAccessor = ".as\(cTypeName)"
        self.cForwardDeclaration = "#include \"\(cTypeName).h\""
    }

    func definitionFragments(in context: CDeclareContext) -> [SourceFragment] {
        let headerName = "CTypes/include/\(concreteStructName).h"
        let headerFragment = context.cHeaderFragment(headerName)

        headerFragment.output("// generated by sourcery:cdecl for \(globalName)`")
        headerFragment.output("struct \(concreteStructName);")
        headerFragment.output("typedef struct \(concreteStructName) * _Nonnull \(cName);")

        let conversionFragment = context.swiftFragment("CInterface/\(globalName)+\(cName).swift")
        // NOTE: globalCName is a typealias to Swift.OpaquePointer. Don't extend it.
        conversionFragment.outputBlock("extension \(globalName) {") {
            conversionFragment.outputBlock("var as\(concreteStructName): \(globalCName) {") {
                conversionFragment.outputBlock("get {") {
                    conversionFragment.output("let pointer = Swift.UnsafeMutablePointer<\(globalName)>.allocate(capacity: 1)")
                    conversionFragment.output("pointer.pointee = self")
                    conversionFragment.output("// TODO: figure out memory conventions")
                    conversionFragment.output("return .init(pointer)")
                }
                conversionFragment.outputBlock("set {") {
                    conversionFragment.output("self = \(wrapAsSwift(expression: "newValue"))")
                }
            }
        }

        return [headerFragment, conversionFragment]
    }
}
