import Foundation
import SourceryRuntime

struct CTranslate {
    func translate(method: SourceryMethod, context: FishyJoesContext) -> [SourceFragment] {
        guard let cName = method.exportAnnotation?.c else { return [] }

        var selfParameter: SwiftFormal?
        let selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).globalName
            // Method.isMutating seems to be a bit buggy...
            let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfParameter = SwiftFormal(
                    label: "self",
                    name: "self",
                    type: context.resolve(type: isMutating ? .unsafeMutablePointer(selfType) : selfType)
                )
                selfExpression = selfParameter!.asSwiftExpression
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        debug("generating \(containingNamespace).\(method.name)`")
        var omitParameters = Set(method.exportAnnotation?.omitParameters ?? [])
        var nonSelfParameters: [SwiftFormal] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            nonSelfParameters.append(
                SwiftFormal(
                    label: parameter.argumentLabel,
                    name: parameter.name,
                    type: context.resolve(type: parameter.typeName.better)
                )
            )
        }
        precondition(omitParameters.isEmpty, "Can't find parameters \(omitParameters) to omit")

        let translatedReturn = context.resolve(type: method.returnTypeName.better)
        // formals.append(contentsOf: translatedReturn.outFormals)

        let cBridgeFragment = context.swiftFragment("CInterface/\(containingNamespace)+cdecl.swift")
        cBridgeFragment.output("// Generated by sourcery:cdecl for `\(containingNamespace).\(method.name)`")
        cBridgeFragment.output("@_cdecl(\"\(cName)\")")
        let allParameters = selfParameter.asArray + nonSelfParameters
        let formals = allParameters.flatMap(\.asSwiftFormals)
        cBridgeFragment.outputBlock("public func \(cName)(", newLineTerminated: false) {
            cBridgeFragment.outputMap(formals, separator: ",") { $0 }
        }
        cBridgeFragment.outputBlock("\(translatedReturn.globalCName == "Swift.Void" ? "" : " -> \(translatedReturn.globalCName)") {") {
            // supress the name "init" and, more importantly, "init?"; one is bad style to call, the other is a type error
            let callName = method.isInitializer ? "" : ".\(method.callName)"
            cBridgeFragment.outputBlock("\(selfExpression)\(callName)(", newLineTerminated: false) {
                cBridgeFragment.outputMap(nonSelfParameters, separator: ",", \.asSwiftLabeledArgument)
            }
            cBridgeFragment.output(translatedReturn.asCAccessor)
        }

        return [cBridgeFragment]
    }

    func translateGetter(for variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let cName = variable.exportAnnotation?.c else { return [] }

        var formals: [String] = []
        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).globalName

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                let translated = context.resolve(type: selfType).asFormals(label: "self", name: "self")
                formals.append(contentsOf: translated.formals.map(\.asSwiftFormal))
                selfExpression = translated.expression
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let translatedReturn = context.resolve(type: variable.typeName.better)
        // formals.append(contentsOf: translatedReturn.outFormals)

        debug("generating getter: CInterface/\(containingNamespace)+cdecl.swift for `\(containingNamespace).\(variable.name)`")
        let fragment = context.swiftFragment("CInterface/\(containingNamespace)+cdecl.swift")
        fragment.output("// Generated by sourcery:cdecl.get for `\(containingNamespace).\(variable.name)`")
        fragment.output("@_cdecl(\"\(cName)\")")
        fragment.outputBlock("public func \(cName)(", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",") { $0 }
        }
        fragment.outputBlock("\(translatedReturn.globalCName == "Swift.Void" ? "" : " -> \(translatedReturn.globalCName)") {") {
            fragment.output("\(selfExpression).\(variable.name)\(translatedReturn.asCAccessor)")
        }
        debug(fragment)
        return [fragment]
    }

    func translateSetter(for variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let cName = variable.exportAnnotation?.cSet else { return [] }
        fatalErr("TODO: translateSetter for \(cName)")
    }
}
