import Foundation
import SourceryRuntime

class KotlinTranslate {
    func javaClassName(_ name: String, in context: FishyJoesContext) -> String {
        "com/cricut/\(context.module.lowercased())/\(name.replacingOccurrences(of: ".", with: "$"))"
    }

    var allMethods: [String: [(javaName: String, signature: String, cname: String)]] = [:]

    func translate(method: SourceryMethod, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = method.exportAnnotation,
              let cName = exportAnnotation.c else {
            return []
        }
        let javaName = exportAnnotation.js ?? cName

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace)(fromJava: _javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        var omitParameters = Set(exportAnnotation.omitParameters)
        var parameters: [SwiftFormal] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            parameters.append(
                SwiftFormal(
                    label: parameter.argumentLabel,
                    name: parameter.name,
                    type: context.resolve(type: parameter.typeName.better)
                )
            )
        }
        precondition(omitParameters.isEmpty, "Can't find parameters \(omitParameters) to omit")

        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ] + parameters.map { parameter in
            let sourceType = parameter.type.sourceProxyType ?? parameter.type.sourceType
            return (name: parameter.name, type: sourceType.name + ".CType")
        }
        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        var jniSignature = "("
        for parameter in parameters {
            jniSignature += parameter.type.jniType.asSignature
        }
        jniSignature += ")"
        let returnSignature: String
        switch method.returnTypeName.better {
        case .void:
            returnSignature = "Void"
            jniSignature += "V"
        case let type:
            returnSignature = "\(type.name).CType"
            let resolved = context.resolve(type: type)
            jniSignature += resolved.jniType.asSignature
        }
        allMethods[containingNamespace, default: []].append((javaName, jniSignature, "java_\(cName)"))
        fragment.outputBlock("let java_\(cName): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(returnSignature) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"

                // Method.isMutating seems to be a bit buggy...
                let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })
                if isMutating {
                    fragment.output("var mutatingSelf = try \(selfExpression)")
                    selfExpression = "mutatingSelf"
                }

                let isVoid = method.returnTypeName.better == .void
                fragment.outputBlock("\(isVoid ? "" : "let result = try ")\(selfExpression)\(callName)(", newLineTerminated: false) {
                    fragment.outputMap(parameters, separator: ",") { formal in
                        let constructor: String
                        if let proxy = formal.type.sourceProxyType {
                            constructor = "\(proxy.name).proxyInit"
                        } else {
                            constructor = formal.type.sourceType.name
                        }
                        return (formal.label.map { "\($0): " } ?? "") +
                            "try \(constructor)(fromJava: \(formal.name), env: _javaEnv)"
                    }
                }
                fragment.output(isVoid ? "" : ".toJava(env: _javaEnv)")
                if isMutating {
                    fragment.output("try mutatingSelf.mutateJava(this: _javaThis, env: _javaEnv)")
                }
                if !isVoid {
                    fragment.output("return result")
                }
            }
        }

        return [fragment]
    }

    func translateGetter(for variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation,
              let cName = exportAnnotation.c else {
            return []
        }
        let kotlinName = exportAnnotation.js ?? cName
        // https://stackoverflow.com/a/43339430/73681
        let jvmName: String
        if kotlinName.hasPrefix("is") {
            jvmName = kotlinName
        } else {
            jvmName = "get" + kotlinName.prefix(1).capitalized + kotlinName.dropFirst()
        }

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace)(fromJava: _javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")

        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ]

        let returnSignature: String
        switch variable.typeName.better {
        case .void:
            returnSignature = "Void"
        case let type:
            returnSignature = "\(type.name).CType"
        }
        let jniSignature = context.resolve(type: variable.typeName.better).jniType.asSignature

        allMethods[containingNamespace, default: []].append((jvmName, "()" + jniSignature, "java_get_\(cName)"))
        fragment.outputBlock("let java_get_\(cName): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(returnSignature) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                fragment.output("try \(selfExpression).\(variable.name).toJava(env: _javaEnv)")
            }
        }

        return [fragment]
    }

    // func properties(for methods: [SourceryMethod]) -> [String] {
    //     var result: [String] = []
    //     for method in methods {
    //         guard let exportAnnotation = method.exportAnnotation,
    //               let cName = exportAnnotation.c else {
    //             continue
    //         }
    //         let javaName = exportAnnotation.js ?? cName
    //         result.append("\"\(javaName)\": (.method(java_\(cName)), isStatic: \(method.isStatic)),")
    //     }
    //     return result
    // }

    // func properties(for computedVariables: [Variable]) -> [String] {
    //     var result: [String] = []
    //     for variable in computedVariables {
    //         guard let exportAnnotation = variable.exportAnnotation,
    //               let cName = exportAnnotation.c else {
    //             continue
    //         }
    //         let javaName = exportAnnotation.js ?? cName
    //         result.append("\"\(javaName)\": (.accessor(getter: java_\(cName), setter: nil), isStatic: \(variable.isStatic)),")
    //     }
    //     return result
    // }

    func setupFragment(context: FishyJoesContext, generatedTypes: Set<BetterType>) -> SourceFragment {
        let javaTypeListFragment = context.swiftFragment(
            "JavaInterface/TypeSetup.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )

        javaTypeListFragment.output("@_cdecl(\"JNI_OnLoad\")")
        javaTypeListFragment.outputBlock("public func JNIOnLoad(vm: UnsafeMutablePointer<JavaVM?>, reserved: UnsafeMutableRawPointer) -> jint {") {
            javaTypeListFragment.output("var envRaw: UnsafeMutableRawPointer?")
            javaTypeListFragment.outputBlock("guard vm.pointee!.pointee.GetEnv(vm, &envRaw, JNI_VERSION_1_4) == JNI_OK else {") {
                javaTypeListFragment.output("fatalError(\"Couldn't obtain jvm environment\")")
            }
            javaTypeListFragment.output("let env = UnsafeMutablePointer<JNIEnv?>(OpaquePointer(envRaw))")
            javaTypeListFragment.outputBlock("return FishyJoesJavaRuntime.callbackBody(env!) { env in", closeWith: "}") {
                javaTypeListFragment.output("let bag = CStringBag()")
                for type in generatedTypes.sorted(by: { "\($0)" < "\($1)" }) {
                    // TODO: better
                    guard case .named = type else {
                        continue
                    }
                    javaTypeListFragment.output("try \(type.name).javaSetup(env: env)")
                    if let nativeMethods = allMethods[type.name] {
                        javaTypeListFragment.outputBlock(
                            "try javaOk(env.fns.RegisterNatives(env.env, \(type.name).javaClass, [",
                            closeWith: "], \(nativeMethods.count)))"
                        ) {
                            for (method, signature, cName) in nativeMethods {
                                javaTypeListFragment.outputBlock("JNINativeMethod(", closeWith: "),") {
                                    javaTypeListFragment.output("name: bag.add(\"\(method)\"),")
                                    javaTypeListFragment.output("signature: bag.add(\"\(signature)\"),")
                                    javaTypeListFragment.output("fnPtr: unsafeBitCast(\(cName), to: UnsafeMutableRawPointer.self)")
                                }
                            }
                        }
                    }
                }
                javaTypeListFragment.output("return JNI_VERSION_1_4")
            }
        }
        return javaTypeListFragment
    }
}
