import Foundation
import SourceryRuntime

class KotlinTranslate {
    func javaClassName(_ name: String, in context: FishyJoesContext) -> String {
        "com/cricut/\(context.module.lowercased())/\(name.replacingOccurrences(of: ".", with: "$"))"
    }

    var allMethods: [String: [(javaName: String, signature: String, cName: String)]] = [:]

    func translate(method: Method, context: FishyJoesContext) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation
        let javaName = exportAnnotation.js ?? exportAnnotation.c

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace)(fromJava: _javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ] + method.parameters.map { parameter in
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            let sourceType = resolved.sourceProxyType ?? resolved.sourceType
            return (name: parameter.name, type: sourceType.name + ".CType")
        }
        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        var jniSignature = "("
        for parameter in method.parameters {
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            jniSignature += resolved.jniType.asSignature
        }
        jniSignature += ")"
        let returnSignature: String
        let resultBlock: (() -> Void) -> Void
        switch method.returnType {
        case .void:
            returnSignature = "Void"
            jniSignature += "V"
            resultBlock = { body in
                body()
                fragment.blankLine()
            }
        case let type:
            let resolved = context.resolve(type: type, generics: exportAnnotation.genericOverrides)
            if let returnProxy = resolved.sourceProxyType?.name {
                resultBlock = { body in
                    fragment.outputBlock("let result = try \(returnProxy).proxyToJava(") {
                        fragment.output("for: ", newLineTerminated: false)
                        body()
                        fragment.blankLine()
                        fragment.output(", env: _javaEnv")
                    }
                }
                returnSignature = "\(returnProxy).CType"
            } else {
                resultBlock = { body in
                    fragment.output("let result = try ", newLineTerminated: false)
                    body()
                    fragment.output(".toJava(env: _javaEnv)")
                }
                returnSignature = "\(resolved.sourceType.name).CType"
            }
            jniSignature += resolved.jniType.asSignature
        }
        let cMethod = "java_\(exportAnnotation.c)"
        allMethods[containingNamespace, default: []].append((javaName, jniSignature, cMethod))
        fragment.outputBlock("let \(cMethod): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(returnSignature) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"

                // let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })
                if method.isMutating {
                    fragment.output("var mutatingSelf = try \(selfExpression)")
                    selfExpression = "mutatingSelf"
                }

                resultBlock {
                    fragment.outputBlock("\(selfExpression)\(callName)(", newLineTerminated: false) {
                        fragment.outputMap(method.parameters, separator: ",") { formal in
                            let constructor: String
                            let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                            if let proxy = resolved.sourceProxyType {
                                constructor = "\(proxy.name).proxyInit"
                            } else {
                                constructor = resolved.sourceType.name
                            }
                            return (formal.label.map { "\($0): " } ?? "") +
                                "try \(constructor)(fromJava: \(formal.name), env: _javaEnv)"
                        }
                    }
                }
                if method.isMutating {
                    fragment.output("try mutatingSelf.mutateJava(this: _javaThis, env: _javaEnv)")
                }
                if method.returnType != .void {
                    fragment.output("return result")
                }
            }
        }

        return [fragment]
    }

    func translateGetter(for variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {
            return []
        }
        let cName = exportAnnotation.c
        let kotlinName = exportAnnotation.js ?? cName
        // https://stackoverflow.com/a/43339430/73681
        let jvmName: String
        if kotlinName.hasPrefix("is") || exportAnnotation.kind == .asMethod {
            jvmName = kotlinName
        } else {
            jvmName = "get" + kotlinName.prefix(1).capitalized + kotlinName.dropFirst()
        }

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace)(fromJava: _javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")

        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ]

        let returnSignature: String
        switch variable.typeName.better {
        case .void:
            returnSignature = "Void"
        case let type:
            returnSignature = "\(type.name).CType"
        }
        let jniSignature = context.resolve(type: variable.typeName.better).jniType.asSignature

        allMethods[containingNamespace, default: []].append((jvmName, "()" + jniSignature, "java_get_\(cName)"))
        fragment.outputBlock("let java_get_\(cName): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(returnSignature) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                fragment.output("try \(selfExpression).\(variable.name).toJava(env: _javaEnv)")
            }
        }

        return [fragment]
    }

    // func properties(for methods: [SourceryMethod]) -> [String] {
    //     var result: [String] = []
    //     for method in methods {
    //         guard let exportAnnotation = method.exportAnnotation,
    //               let cName = exportAnnotation.c else {
    //             continue
    //         }
    //         let javaName = exportAnnotation.js ?? cName
    //         result.append("\"\(javaName)\": (.method(java_\(cName)), isStatic: \(method.isStatic)),")
    //     }
    //     return result
    // }

    // func properties(for computedVariables: [Variable]) -> [String] {
    //     var result: [String] = []
    //     for variable in computedVariables {
    //         guard let exportAnnotation = variable.exportAnnotation,
    //               let cName = exportAnnotation.c else {
    //             continue
    //         }
    //         let javaName = exportAnnotation.js ?? cName
    //         result.append("\"\(javaName)\": (.accessor(getter: java_\(cName), setter: nil), isStatic: \(variable.isStatic)),")
    //     }
    //     return result
    // }

    func setupFragment(context: FishyJoesContext, generatedTypes: Set<BetterType>) -> SourceFragment {
        let javaTypeListFragment = context.swiftFragment(
            "JavaInterface/TypeSetup.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )

        javaTypeListFragment.output("@_cdecl(\"JNI_OnLoad\")")
        javaTypeListFragment.outputBlock("public func JNIOnLoad(vm: UnsafeMutablePointer<JavaVM?>, reserved: UnsafeMutableRawPointer) -> jint {") {
            javaTypeListFragment.output("var envRaw: UnsafeMutableRawPointer?")
            javaTypeListFragment.outputBlock("guard vm.pointee!.pointee.GetEnv(vm, &envRaw, JNI_VERSION_1_4) == JNI_OK else {") {
                javaTypeListFragment.output("fatalError(\"Couldn't obtain jvm environment\")")
            }
            javaTypeListFragment.output("let env = UnsafeMutablePointer<JNIEnv?>(OpaquePointer(envRaw))")
            javaTypeListFragment.outputBlock("return FishyJoesJavaRuntime.callbackBody(env!) { env in", closeWith: "}") {
                javaTypeListFragment.output("let bag = CStringBag()")
                for type in generatedTypes.sorted(by: { "\($0)" < "\($1)" }) {
                    guard type != .void else { continue }
                    let resolved = context.resolve(type: type)
                    let proxy = resolved.sourceProxyType ?? resolved.sourceType
                    javaTypeListFragment.output("// print(\"setting up \(proxy.name)...\")")
                    javaTypeListFragment.output("try \(proxy.name).javaSetup(env: env)")
                    if case .named = type {
                        if let nativeMethods = allMethods[type.name] {
                            javaTypeListFragment.outputBlock("try javaOk(env.RegisterNatives(\(type.name).javaClass, ", closeWith: "))") {
                                for (method, signature, cName) in nativeMethods {
                                    let isLast = cName == nativeMethods.last?.cName
                                    javaTypeListFragment.outputBlock("JNINativeMethod(", closeWith: isLast ? ")" : "),") {
                                        javaTypeListFragment.output("name: bag.add(\"\(method)\"),")
                                        javaTypeListFragment.output("signature: bag.add(\"\(signature)\"),")
                                        javaTypeListFragment.output("fnPtr: unsafeBitCast(\(cName), to: UnsafeMutableRawPointer.self)")
                                    }
                                }
                            }
                        }
                    }
                }
                javaTypeListFragment.output("return JNI_VERSION_1_4")
            }
        }
        return javaTypeListFragment
    }

    func kotlin(method: Method, context: FishyJoesContext) -> KotlinClass.MethodOrVariable? {
        let exportAnnotation = method.exportAnnotation
        let nodeName = exportAnnotation.js ?? exportAnnotation.c
        var omitParameters = Set(exportAnnotation.omitParameters)
        var parameters: [(labelComment: String?, name: String, KotlinClass.KType)] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            var label: String?
            if let swiftLabel = parameter.label, swiftLabel != parameter.name {
                label = swiftLabel
            }
            parameters.append((label, parameter.name, resolved.kotlinType))
        }

        return .method(
            KotlinClass.Method(
                documentation: method.documentation,
                isStatic: method.isStatic,
                isOverride: method.exportAnnotation.isOverride,
                name: nodeName,
                parameters: parameters,
                returnType: context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).kotlinType,
                body: nil
            )
        )
    }

    func kotlin(field: Variable, context: FishyJoesContext, useNativeName: Bool = false) -> KotlinClass.MethodOrVariable? {
        let ktName: String
        var asMethod = false

        if useNativeName {
            guard field.exportAnnotation == nil else {
                fatalErr("field \(field.name) should not be annotated, as it's in a type being exported memberwise")
            }
            ktName = field.name
        } else {
            guard let exportAnnotation = field.exportAnnotation else {
                return nil
            }
            let annotatedName = exportAnnotation.js ?? exportAnnotation.c
            asMethod = exportAnnotation.kind == .asMethod
            ktName = annotatedName
        }
        let resolved = context.resolve(type: field.typeName.better)
        if asMethod {
            return .method(
                KotlinClass.Method(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    name: ktName,
                    parameters: [],
                    returnType: resolved.kotlinType,
                    body: nil
                )
            )
        } else {
            return .variable(
                KotlinClass.Variable(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    readOnly: !field.isMutable,
                    name: ktName,
                    type: resolved.kotlinType
                )
            )
        }
    }
}
