import Foundation
import SourceryRuntime

class KotlinTranslate {
    func javaClassName(_ name: String, in context: FishyJoesContext) -> String {
        "com/cricut/\(context.module.lowercased())/\(name.replacingOccurrences(of: ".", with: "$"))"
    }

    var allMethods: [String: [(javaName: String, signature: String, cName: String)]] = [:]

    func translate(method: Method, context: FishyJoesContext) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace).fromJava(_javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ] + method.parameters.map { parameter in
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            return (name: parameter.name, type: resolved.converterType.name + ".CType")
        }
        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        var jniSignature = "("
        for parameter in method.parameters {
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            jniSignature += resolved.jniType.asSignature
        }
        jniSignature += ")"
        let returnSignature: String
        let resultBlock: (() -> Void) -> Void
        switch method.returnType {
        case .void:
            returnSignature = "Void"
            jniSignature += "V"
            resultBlock = { body in
                if method.isThrowing {
                    fragment.output("try ", newLineTerminated: false)
                }
                body()
                fragment.blankLine()
            }
        case let type:
            let resolved = context.resolve(type: type, generics: exportAnnotation.genericOverrides)
            resultBlock = { body in
                fragment.outputBlock("let result = try \(resolved.converterType.name).toJava(") {
                    body()
                    fragment.blankLine()
                    fragment.output(", env: _javaEnv")
                }
            }
            returnSignature = "\(resolved.converterType.name).CType"
            jniSignature += resolved.jniType.asSignature
        }
        let cMethod = "java_\(containingNamespace)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")
        allMethods[containingNamespace, default: []].append((exportAnnotation.name, jniSignature, cMethod))
        fragment.outputBlock("let \(cMethod): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(returnSignature) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"

                // let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })
                if method.isMutating {
                    fragment.output("var mutatingSelf = try \(selfExpression)")
                    selfExpression = "mutatingSelf"
                }

                resultBlock {
                    fragment.outputBlock("\(selfExpression)\(callName)(", newLineTerminated: false) {
                        fragment.outputMap(method.parameters, separator: ",") { formal in
                            let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                            return (formal.label.map { "\($0): " } ?? "") +
                                "try \(resolved.converterType.name).fromJava(\(formal.name), env: _javaEnv)"
                        }
                    }
                }
                if method.isMutating {
                    fragment.output("try \(containingNamespace).mutateJava(mutatingSelf, javaThis: _javaThis, env: _javaEnv)")
                }
                if method.returnType != .void {
                    fragment.output("return result")
                }
            }
        }

        return [fragment]
    }

    func translate(variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {
            return []
        }
        let kotlinName = exportAnnotation.name
        // https://stackoverflow.com/a/43339430/73681
        let jvmGetName: String
        let jvmSetName: String
        if kotlinName.hasPrefix("is") {
            jvmGetName = kotlinName
            jvmSetName = "set" + upperCaseFirst(kotlinName.dropFirst(2))
        } else {
            jvmGetName = "get" + upperCaseFirst(kotlinName)
            jvmSetName = "set" + upperCaseFirst(kotlinName)
        }

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "\(containingNamespace).fromJava(_javaThis, env: _javaEnv)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let cGetName = "java_get_\(containingNamespace)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")
        let cSetName = "java_set_\(containingNamespace)_\(exportAnnotation.name)".replacingOccurrences(of: ".", with: "_")

        let fragment = context.swiftFragment(
            "JavaInterface/\(containingNamespace)+javadecl.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )

        let resolved = context.resolve(type: variable.typeName.better)
        let jniSignature = resolved.jniType.asSignature
        let converterName = resolved.converterType.name
        let cType = "\(converterName).CType"

        // Getter
        let formals = [
            (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
            (name: "_javaThis", type: "jobject"),
        ]

        allMethods[containingNamespace, default: []].append((jvmGetName, "()" + jniSignature, cGetName))
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        fragment.outputBlock("let \(cGetName): @convention(c) (", newLineTerminated: false) {
            fragment.outputMap(formals, separator: ",", \.type)
        }
        fragment.outputBlock(" -> \(cType) = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
            fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                fragment.output("try \(converterName).toJava(\(selfExpression).\(variable.name), env: _javaEnv)")
            }
        }

        // Setter
        if variable.isMutable, variable.accessLevel.write == .public {
            let formals = [
                (name: "_javaEnv", type: "UnsafeMutablePointer<JNIEnv?>"),
                (name: "_javaThis", type: "jobject"),
                (name: "newValue", type: cType),
            ]
            allMethods[containingNamespace, default: []].append((jvmSetName, "(\(jniSignature))V", cSetName))
            fragment.outputBlock("let \(cSetName): @convention(c) (", newLineTerminated: false) {
                fragment.outputMap(formals, separator: ",", \.type)
            }
            fragment.outputBlock(" -> Void = { \(formals.map(\.name).joined(separator: ", ")) in", closeWith: "}") {
                fragment.outputBlock("FishyJoesJavaRuntime.callbackBody(_javaEnv) { _javaEnv in", closeWith: "}") {
                    if variable.isStatic {
                        fragment.output("\(selfExpression).\(variable.name) = try \(converterName).fromJava(newValue, env: _javaEnv)")
                    } else {
                        fragment.output("var mutatingSelf = try \(selfExpression)")
                        fragment.output("mutatingSelf.\(variable.name) = try \(converterName).fromJava(newValue, env: _javaEnv)")
                        fragment.output("try \(containingNamespace).mutateJava(mutatingSelf, javaThis: _javaThis, env: _javaEnv)")
                    }
                }
            }
        }

        return [fragment]
    }

    func setupFragment(context: FishyJoesContext, generatedTypes: Set<BetterType>) -> SourceFragment {
        let javaTypeListFragment = context.swiftFragment(
            "JavaInterface/TypeSetup.swift",
            additionalImports: ["FishyJoesJavaRuntime"]
        )

        javaTypeListFragment.output("@_cdecl(\"JNI_OnLoad\")")
        javaTypeListFragment.outputBlock("public func JNIOnLoad(vm: UnsafeMutablePointer<JavaVM?>, reserved: UnsafeMutableRawPointer) -> jint {") {
            javaTypeListFragment.output("var envRaw: UnsafeMutableRawPointer?")
            javaTypeListFragment.outputBlock("guard vm.pointee!.pointee.GetEnv(vm, &envRaw, JNI_VERSION_1_4) == JNI_OK else {") {
                javaTypeListFragment.output("fatalError(\"Couldn't obtain jvm environment\")")
            }
            javaTypeListFragment.output("let env = UnsafeMutablePointer<JNIEnv?>(OpaquePointer(envRaw))")
            javaTypeListFragment.outputBlock("return FishyJoesJavaRuntime.callbackBody(env!) { env in", closeWith: "}") {
                javaTypeListFragment.output("let bag = CStringBag()")
                for type in generatedTypes.sorted(by: { "\($0)" < "\($1)" }) {
                    guard type != .void else { continue }
                    let resolved = context.resolve(type: type)
                    javaTypeListFragment.output("// print(\"setting up \(resolved.converterType.name)...\")")
                    javaTypeListFragment.output("try \(resolved.converterType.name).javaSetup(env: env)")
                    if case .named = type {
                        if let nativeMethods = allMethods[type.name] {
                            javaTypeListFragment.outputBlock("try javaOk(env.RegisterNatives(\(type.name).javaClass, ", closeWith: "))") {
                                for (method, signature, cName) in nativeMethods {
                                    let isLast = cName == nativeMethods.last?.cName
                                    javaTypeListFragment.outputBlock("JNINativeMethod(", closeWith: isLast ? ")" : "),") {
                                        javaTypeListFragment.output("name: bag.add(\"\(method)\"),")
                                        javaTypeListFragment.output("signature: bag.add(\"\(signature)\"),")
                                        javaTypeListFragment.output("fnPtr: unsafeBitCast(\(cName), to: UnsafeMutableRawPointer.self)")
                                    }
                                }
                            }
                        }
                    }
                }
                javaTypeListFragment.output("return JNI_VERSION_1_4")
            }
        }
        return javaTypeListFragment
    }

    func kotlin(method: Method, context: FishyJoesContext) -> KotlinClass.MethodOrVariable? {
        let exportAnnotation = method.exportAnnotation
        var omitParameters = Set(exportAnnotation.omitParameters)
        var parameters: [(labelComment: String?, name: String, KotlinClass.KType)] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            let resolved = context.resolve(type: parameter.type, generics: exportAnnotation.genericOverrides)
            var label: String?
            if let swiftLabel = parameter.label, swiftLabel != parameter.name {
                label = swiftLabel
            }
            parameters.append((label, parameter.name, resolved.kotlinType))
        }

        return .method(
            KotlinClass.Method(
                documentation: method.documentation,
                isStatic: method.isStatic,
                isOverride: method.exportAnnotation.isOverride,
                name: exportAnnotation.name,
                parameters: parameters,
                returnType: context.resolve(type: method.returnType, generics: exportAnnotation.genericOverrides).kotlinType,
                body: nil
            )
        )
    }

    func kotlin(field: Variable, context: FishyJoesContext, useNativeName: Bool = false) -> KotlinClass.MethodOrVariable? {
        let ktName: String
        var asMethod = false

        if useNativeName {
            guard field.exportAnnotation == nil else {
                fatalErr("field \(field.name) should not be annotated, as it's in a type being exported memberwise")
            }
            ktName = field.name
        } else {
            guard let exportAnnotation = field.exportAnnotation else {
                return nil
            }
            asMethod = exportAnnotation.kind == .asMethod
            ktName = exportAnnotation.name
        }
        let resolved = context.resolve(type: field.typeName.better)
        if asMethod {
            return .method(
                KotlinClass.Method(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    name: ktName,
                    parameters: [],
                    returnType: resolved.kotlinType,
                    body: nil
                )
            )
        } else {
            return .variable(
                KotlinClass.Variable(
                    documentation: field.documentation,
                    isStatic: field.isStatic,
                    isOverride: field.exportAnnotation?.isOverride ?? false,
                    readOnly: !field.isMutable,
                    name: ktName,
                    type: resolved.kotlinType
                )
            )
        }
    }
}
