import Foundation
import SourceryRuntime
import Darwin

func debug(file: StaticString = #file, line: UInt = #line, _ msgs: Any? ...) {
    let message = "\(file):\(line): " + msgs.map { "\($0 ?? "<null>")" }.joined(separator: " ") + "\n"
    _ = message.withCString { fputs($0, stderr) }
}

struct NodeTranslate {
    func translateGetter(for variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation else {return []}
        let cName = exportAnnotation.c
        let nodeName = exportAnnotation.js ?? cName

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "env.this(as: \(containingNamespace).self)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let fragment = context.swiftFragment(
            "NodeInterface/\(containingNamespace)+nodedecl.swift",
            additionalImports: ["FishyJoesNodeRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        fragment.outputBlock("let node_\(cName): napi_callback = { env, info in", closeWith: "}") {
            fragment.outputBlock("FishyJoesNodeRuntime.callbackBody(env, info, name: \"\(nodeName)\", expectedArgumentCount: 0) { env in", closeWith: "}") {
                fragment.output("try \(selfExpression).\(variable.name).toNode(env: env.env)")
            }
        }

        return [fragment]
    }

    func translate(method: Method, context: FishyJoesContext) -> [SourceFragment] {
        let exportAnnotation = method.exportAnnotation
        let cName = exportAnnotation.c
        let nodeName = exportAnnotation.js ?? cName

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedIn {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "env.this(as: \(containingNamespace).self)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let fragment = context.swiftFragment(
            "NodeInterface/\(containingNamespace)+nodedecl.swift",
            additionalImports: ["FishyJoesNodeRuntime"]
        )

        let resultBlock: (() -> Void) -> Void
        switch method.returnType {
        case .void:
            resultBlock = { body in
                body()
                fragment.blankLine()
                fragment.output("let result: napi_value? = nil")
            }
        case let type:
            let resolved = context.resolve(type: type, generics: exportAnnotation.genericOverrides)
            if let returnProxy = resolved.sourceProxyType?.name {
                resultBlock = { body in
                    fragment.outputBlock("let result = try \(returnProxy).proxyToNode(") {
                        fragment.output("for: ", newLineTerminated: false)
                        body()
                        fragment.blankLine()
                        fragment.output(", env: env.env")
                    }
                }
            } else {
                resultBlock = { body in
                    fragment.output("let result = try ", newLineTerminated: false)
                    body()
                    fragment.output(".toNode(env: env.env)")
                }
            }
        }

        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        fragment.outputBlock("let node_\(cName): napi_callback = { env, info in", closeWith: "}") {
            fragment.outputBlock("FishyJoesNodeRuntime.callbackBody(env, info, name: \"\(nodeName)\", expectedArgumentCount: \(method.parameters.count)) { env in", closeWith: "}") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"

                if method.isMutating {
                    fragment.output("var mutatingSelf = try \(selfExpression)")
                    selfExpression = "mutatingSelf"
                }

                resultBlock {
                    fragment.outputBlock("\(selfExpression)\(callName)(", newLineTerminated: false) {
                        fragment.outputMap(method.parameters.enumerated(), separator: ",") {
                            let (index, formal) = $0
                            let resolved = context.resolve(type: formal.type, generics: exportAnnotation.genericOverrides)
                            let result = (formal.label.map { "\($0): " } ?? "") + "try env.argument(at: \(index), "
                            if let proxy = resolved.sourceProxyType {
                                return result + "asProxyType: \(proxy.name).self)"
                            } else {
                                return result + "as: \(resolved.sourceType.name).self)"
                            }
                        }
                    }
                }
                if method.isMutating {
                    fragment.output("try mutatingSelf.mutateNode(this: env.this(), env: env.env)")
                }
                fragment.output("return result")
            }
        }

        return [fragment]
    }

    func properties(for methods: [Method]) -> [String] {
        var result: [String] = []
        for method in methods {
            let exportAnnotation = method.exportAnnotation
            let cName = exportAnnotation.c
            let nodeName = exportAnnotation.js ?? cName
            result.append("\"\(nodeName)\": (.method(node_\(cName)), isStatic: \(method.isStatic)),")
        }
        return result
    }

    func properties(for computedVariables: [Variable]) -> [String] {
        var result: [String] = []
        for variable in computedVariables {
            guard let exportAnnotation = variable.exportAnnotation else {
                continue
            }
            let cName = exportAnnotation.c
            let nodeName = exportAnnotation.js ?? cName
            result.append("\"\(nodeName)\": (.accessor(getter: node_\(cName), setter: nil), isStatic: \(variable.isStatic)),")
        }
        return result
    }

    func setupFragment(context: FishyJoesContext, generatedTypes: Set<BetterType>) -> SourceFragment {
        let nodeTypeListFragment = context.swiftFragment(
            "NodeInterface/TypeSetup.swift",
            additionalImports: ["FishyJoesNodeRuntime"]
        )

        nodeTypeListFragment.output("@_cdecl(\"napi_register_module_v1\")")
        nodeTypeListFragment.outputBlock("public func napi_register_module_v1(env: napi_env, exports: napi_value) -> napi_value? {") {
            nodeTypeListFragment.outputBlock("FishyJoesNodeRuntime.rethrowToNode(env: env) {") {
                nodeTypeListFragment.output("var module: napi_value!")
                nodeTypeListFragment.output("try check(napi_create_object(env, &module))")
                nodeTypeListFragment.output("napi_set_named_property(env, exports, \"\(context.module)\", module)")
                nodeTypeListFragment.output("napi_set_named_property(env, exports, \"default\", module)")
                nodeTypeListFragment.blankLine()
                for type in generatedTypes.sorted(by: { "\($0)" < "\($1)" }) {
                    // TODO: better
                    guard case .named = type else {
                        continue
                    }
                    nodeTypeListFragment.output("try \(type.name).nodeSetup(env: env, module: module)")
                }
                nodeTypeListFragment.output("return exports")
            }
        }
        return nodeTypeListFragment
    }
}
