import Foundation
import SourceryRuntime

func debug(_ msgs: Any? ...) {
    let message = msgs.map { "\($0 ?? "<null>")" }.joined(separator: " ") + "\n"
    FileHandle.standardError.write(message.data(using: .utf8)!)
}

struct NodeTranslate {
    func translateGetter(for variable: Variable, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = variable.exportAnnotation,
              let cName = exportAnnotation.c else {
            return []
        }
        let nodeName = exportAnnotation.js ?? cName

        let selfExpression: String
        let containingNamespace: String

        if let selfType = variable.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if variable.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "env.this(as: \(containingNamespace).self)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        let fragment = context.swiftFragment(
            "NodeInterface/\(containingNamespace)+nodedecl.swift",
            additionalImports: ["FishyJoesNodeRuntime"]
        )
        fragment.output("// Generated by FishyJoes for `\(containingNamespace).\(variable.name)`")
        fragment.outputBlock("let node_\(cName): napi_callback = { env, info in", closeWith: "}") {
            fragment.outputBlock("FishyJoesNodeRuntime.callbackBody(env, info, name: \"\(nodeName)\", expectedArgumentCount: 0) { env in", closeWith: "}") {
                fragment.output("try \(selfExpression).\(variable.name).toNode(env: env.env)")
            }
        }

        return [fragment]
    }

    func translate(method: SourceryMethod, context: FishyJoesContext) -> [SourceFragment] {
        guard let exportAnnotation = method.exportAnnotation,
              let cName = exportAnnotation.c else {
            return []
        }
        let nodeName = exportAnnotation.js ?? cName

        var selfExpression: String
        let containingNamespace: String

        if let selfType = method.definedInTypeName?.better {
            containingNamespace = context.resolve(type: selfType).sourceType.name

            if method.isStatic {
                selfExpression = containingNamespace
            } else {
                selfExpression = "env.this(as: \(containingNamespace).self)"
            }
        } else {
            containingNamespace = context.module
            selfExpression = context.module
        }

        var omitParameters = Set(exportAnnotation.omitParameters)
        var parameters: [SwiftFormal] = []
        for parameter in method.parameters {
            if omitParameters.contains(parameter.name) {
                precondition(parameter.defaultValue != nil, "Can't omit non-default parameter")
                omitParameters.remove(parameter.name)
                continue
            }
            parameters.append(
                SwiftFormal(
                    label: parameter.argumentLabel,
                    name: parameter.name,
                    type: context.resolve(type: parameter.typeName.better, generics: exportAnnotation.genericOverrides)
                )
            )
        }
        precondition(omitParameters.isEmpty, "Can't find parameters \(omitParameters) to omit")

        let formals = parameters.map(\.asSwiftFormal)
        let nodeBridgeFragment = context.swiftFragment(
            "NodeInterface/\(containingNamespace)+nodedecl.swift",
            additionalImports: ["FishyJoesNodeRuntime"]
        )
        nodeBridgeFragment.output("// Generated by FishyJoes for `\(containingNamespace).\(method.name)`")
        nodeBridgeFragment.outputBlock("let node_\(cName): napi_callback = { env, info in", closeWith: "}") {
            nodeBridgeFragment.outputBlock("FishyJoesNodeRuntime.callbackBody(env, info, name: \"\(nodeName)\", expectedArgumentCount: \(formals.count)) { env in", closeWith: "}") {
                let callName = method.isInitializer ? "" : ".\(method.callName)"

                // Method.isMutating seems to be a bit buggy...
                let isMutating = method.isMutating || method.modifiers.contains(where: { $0.name == "mutating" })
                if isMutating {
                    nodeBridgeFragment.output("var mutatingSelf = try \(selfExpression)")
                    selfExpression = "mutatingSelf"
                }

                let isVoid = method.returnTypeName.better == .void
                nodeBridgeFragment.outputBlock("\(isVoid ? "" : "let result = try ")\(selfExpression)\(callName)(", newLineTerminated: false) {
                    nodeBridgeFragment.outputMap(parameters.enumerated(), separator: ",") {
                        let (index, formal) = $0
                        return (formal.label.map { "\($0): " } ?? "") + "try env.argument(at: \(index), as: \(formal.type.sourceType.name).self)"
                    }
                }
                nodeBridgeFragment.output(isVoid ? "" : ".toNode(env: env.env)")
                if isMutating {
                    nodeBridgeFragment.output("try mutatingSelf.mutateNode(this: env.this(), env: env.env)")
                }
                nodeBridgeFragment.output("return \(isVoid ? "nil" : "result")")
            }
        }

        return [nodeBridgeFragment]
    }

    func properties(for methods: [SourceryMethod]) -> [String] {
        var result: [String] = []
        for method in methods {
            guard let exportAnnotation = method.exportAnnotation,
                  let cName = exportAnnotation.c else {
                continue
            }
            let nodeName = exportAnnotation.js ?? cName
            result.append("\"\(nodeName)\": (.method(node_\(cName)), isStatic: \(method.isStatic)),")
        }
        return result
    }

    func properties(for computedVariables: [Variable]) -> [String] {
        var result: [String] = []
        for variable in computedVariables {
            guard let exportAnnotation = variable.exportAnnotation,
                  let cName = exportAnnotation.c else {
                continue
            }
            let nodeName = exportAnnotation.js ?? cName
            result.append("\"\(nodeName)\": (.accessor(getter: node_\(cName), setter: nil), isStatic: \(variable.isStatic)),")
        }
        return result
    }


    func setupFragment(context: FishyJoesContext, generatedTypes: Set<BetterType>) -> SourceFragment {
        let nodeTypeListFragment = context.swiftFragment(
            "NodeInterface/TypeSetup.swift",
            additionalImports: ["FishyJoesNodeRuntime"]
        )

        nodeTypeListFragment.output("@_cdecl(\"napi_register_module_v1\")")
        nodeTypeListFragment.outputBlock("public func napi_register_module_v1(env: napi_env, exports: napi_value) -> napi_value? {") {
            nodeTypeListFragment.outputBlock("FishyJoesNodeRuntime.rethrowToNode(env: env) {") {
                nodeTypeListFragment.output("var module: napi_value!")
                nodeTypeListFragment.output("try check(napi_create_object(env, &module))")
                nodeTypeListFragment.output("napi_set_named_property(env, exports, \"\(context.module)\", module)")
                nodeTypeListFragment.output("napi_set_named_property(env, exports, \"default\", module)")
                nodeTypeListFragment.output()
                for type in generatedTypes.sorted(by: { "\($0)" < "\($1)" }) {
                    // TODO: better
                    guard case .named = type else {
                        continue
                    }
                    nodeTypeListFragment.output("try \(type.name).nodeSetup(env: env, module: module)")
                }
                nodeTypeListFragment.output("return exports")
            }
        }
        return nodeTypeListFragment
    }
}
