name: "C# runtime"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  label:
    types:
      - created
  pull_request:
  release:
    types: [published]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-test-c-sharp-mac:
    name: "mac: Build and test C# runtime"
    runs-on: macOS-12
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Build FishyJoesCSharpRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-c-sharp-runtime.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac_generated
          path: c-sharp-runtime/runtimes

  build-test-c-sharp-linux:
    name: "linux: Build and test C# runtime"
    runs-on: ubuntu-latest
    container:
      image: swift
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      LIB_DIR: c-sharp-runtime/runtimes/linux/native
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Configure build environment
        run: |
          set -euxo pipefail
          sudo apt-get install zsh

      - name: Build FishyJoesCSharpRuntime
        run: |
          set -euxo pipefail

          ./scripts/compile-c-sharp-runtime.sh

      - name: Copy System Swift Runtime SOs
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cp -dv /usr/lib/swift/linux/libswift*.so* $LIB_DIR
          cp -dv /usr/lib/swift/linux/libicu*.so* $LIB_DIR
          cp -dv /usr/lib/swift/linux/libFoundation*.so $LIB_DIR
          cp -dv /usr/lib/swift/linux/libBlocksRuntime.so $LIB_DIR
          cp -dv /usr/lib/swift/linux/libdispatch.so $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libicui18n.so* $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libicuuc.so* $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libicudata.so* $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libxml2.so* $LIB_DIR

      - name: Patch Executables & System Swift Runtime SOs to Use Relative Libraries
        run: |
          apt update
          apt install patchelf

          cd $LIB_DIR

          SWIFT_RUN_PATH='/usr/lib/swift/linux:./:$ORIGIN'
          for LIB in lib*.so*; do
            patchelf --set-rpath $SWIFT_RUN_PATH $LIB
          done

      - name: Upload library
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu_generated
          path: c-sharp-runtime/runtimes

  build-test-c-sharp-windows:
    name: "windows: Build and test C# bindings"
    runs-on: windows-2019
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: |
            swift build --product FishyJoesCSharpRuntime --configuration release --build-path ./.build/windows-build
          swift-version: "5.4.2"

      - name: Copy resources
        shell: bash
        run: |
          set -euxo pipefail

          LIB_DIR=c-sharp-runtime/runtimes/win/native/

          mkdir -p $LIB_DIR
          cp .build/windows-build/x86_64-unknown-windows-msvc/release/FishyJoesCSharpRuntime.dll $LIB_DIR
          ls /
          cp -R /Library/icu-*/usr/bin/*.dll $LIB_DIR
          cp -R /Library/Swift-development/bin/*.dll $LIB_DIR

      - name: Upload library
        uses: actions/upload-artifact@v2
        with:
          name: windows_generated
          path: c-sharp-runtime/runtimes

  c-sharp-publish:
    name: "Publish C# package"
    runs-on: ubuntu-latest
    needs: [build-test-c-sharp-mac, build-test-c-sharp-linux, build-test-c-sharp-windows]
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      GITHUB_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Configure build environment
        run: |
          set -euxo pipefail
          sudo apt-get install zsh

      - name: Retrieve Artifacts
        uses: actions/download-artifact@v2

      - name: Install Artifacts
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ls *

          rm -rf c-sharp-runtime/runtimes
          mkdir -p c-sharp-runtime/runtimes
          mv mac_generated/osx c-sharp-runtime/runtimes/
          mv ubuntu_generated/linux c-sharp-runtime/runtimes/
          mv windows_generated/win c-sharp-runtime/runtimes/

          ls -R c-sharp-runtime/

      - name: Determine version
        shell: zsh {0}
        run: |
          set -euxo pipefail

          VERSION=${GITHUB_REF#refs/*/}
          if [[ ! $VERSION =~ [0-9]+\.[0-9]+\.[0-9]+ ]]; then
              VERSION="0.0.1-$(git rev-parse --short HEAD)"
          fi
          echo "Detected Version is '$VERSION'"
          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Pack
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd c-sharp-runtime
          dotnet pack -c Release -o out /p:PackageVersion="${{ env.VERSION }}"

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: out/*.nupkg

      - name: Publish
        shell: zsh {0}
        if: github.event_name == 'release'
        run: |
          set -euxo pipefail

          dotnet nuget push ./c-sharp-runtime/out/*.nupkg \
            --source https://nuget.pkg.github.com/cricut \
            --api-key ${{ github.token }} \
            --skip-duplicate
