name: dart-runtime

on:
  workflow_dispatch:
  push:
    branches:
      - main
  label:
    types:
      - created
  pull_request:
  release:
    types: [published]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-test-dart-mac:
    name: "mac: Build and test dart runtime"
    runs-on: macOS-12
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Build FishyJoesDartRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          libdir=dart-runtime/native

          rm -rf $libdir
          mkdir -p $libdir/macos

          swift build --configuration release --product FishyJoesDartRuntime
          cp .build/release/libFishyJoesDartRuntime.dylib $libdir/macos
          codesign -s - $libdir/macos/libFishyJoesDartRuntime.dylib

      - name: Upload library
        uses: actions/upload-artifact@v2
        with:
          name: mac_lib
          path: dart-runtime/native/macos/libFishyJoesDartRuntime.dylib

  build-test-dart-linux:
    name: "linux: Build and test dart runtime"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Configure build environment
        run: |
          set -euxo pipefail
          sudo apt-get install zsh

      - name: Build FishyJoesDartRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          libdir=dart-runtime/native

          rm -rf $libdir
          mkdir -p $libdir/linux

          swift build --configuration release --product FishyJoesDartRuntime
          cp .build/release/libFishyJoesDartRuntime.so $libdir/linux

      - name: Upload library
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu_lib
          path: dart-runtime/native/linux/libFishyJoesDartRuntime.so

  build-test-dart-windows:
    name: "windows: Build and test dart bindings"
    runs-on: windows-2019
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          shell-action: |
            swift build --product FishyJoesDartRuntime --configuration release --build-path ./.build/windows-build
          swift-version: "5.4.2"

      - name: Copy resource
        shell: bash
        run: |
          set -euxo pipefail

          mkdir -p dart-runtime/native/windows
          cp .build/windows-build/x86_64-unknown-windows-msvc/release/FishyJoesDartRuntime.dll dart-runtime/native/windows

      - name: Upload library
        uses: actions/upload-artifact@v2
        with:
          name: windows_lib
          path: dart-runtime/native/windows/FishyJoesDartRuntime.dll

  dart-publish:
    name: Publish dart package
    runs-on: ubuntu-latest
    needs: [build-test-dart-mac, build-test-dart-linux, build-test-dart-windows]
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      GITHUB_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Configure build environment
        run: |
          set -euxo pipefail
          sudo apt-get install zsh

      - name: Retrieve Artifacts
        uses: actions/download-artifact@v2

      - name: Install and Package Artifacts
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ls *

          rm -rf dart-runtime/native
          mkdir -p dart-runtime/native/{macos,linux,windows}
          mv mac_lib/libFishyJoesDartRuntime.dylib dart-runtime/native/macos/
          mv ubuntu_lib/libFishyJoesDartRuntime.so dart-runtime/native/linux/
          mv windows_lib/FishyJoesDartRuntime.dll dart-runtime/native/windows/

          tar -cvzf dart-binaries.tgz -C dart-runtime native

      - name: Publish
        shell: zsh {0}
        if: github.event_name == 'release'
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          set -euxo pipefail

          releaseID=$(
              gh api \
              -H "Accept: application/vnd.github.v3+json" \
              "/repos/$OWNER/$REPO/releases/tags/$GITHUB_REF_NAME" \
              -q .id
          )

          file=dart-binaries.tgz

          # https://docs.github.com/en/rest/releases/assets#upload-a-release-asset
          curl -f -u "$GITHUB_USER:$GITHUB_PUBLISH_TOKEN" \
            -X POST \
            -H 'Content-Type: application/gzip' \
            -H 'Accept: application/vnd.github.v3+json' \
            "https://uploads.github.com/repos/$OWNER/$REPO/releases/$releaseID/assets?name=$file" \
            --data-binary @$file
