---
name: "Integration Tests"

"on":
  workflow_dispatch:
  push:
    branches:
      - main
  label:
    types:
      - created
  pull_request:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  integration-tests-mac:
    name: "macOS: Integration tests"
    runs-on: [macOS, self-hosted, ARM64]
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      CONFIGURATION: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 20

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@cricut'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'

      - name: Force clear nuget cache
        run: "dotnet nuget locals all --clear"

      - uses: dart-lang/setup-dart@v1

      - name: Ensure re-generating does not change committed generated code
        shell: zsh {0}
        run: |
          set -euxo pipefail

          echo "gonna ls -lat"
          ls -lat

          echo "gonna pwd"
          pwd

          cd integration-tests

          echo "2 gonna ls -lat"
          ls -lat

          echo "2 gonna pwd"
          pwd

          cd TestAPI

          echo "3 gonna ls -lat"
          ls -lat

          echo "3 gonna pwd"
          pwd

          FISHYJOES=1 swift run -- fishy-joes generate

          if [ ! -z "$(cd integration-tests/TestAPI-bindings; git status --porcelain .)" ]; then
            echo '::error:: generation modified sources'
            echo '::error::   run `FISHYJOES=1 swift run fishy-joes generate` from integration-tests/TestAPI-bindings and re-commit'
            git status
            exit 1
          fi

      - name: Build FishyJoesNodeRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-node-runtime.sh

      - name: Test TypeScript from npm via fishy-joes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          FISHYJOES=1 swift run -- fishy-joes --nodejs build test

      - name: Build FishyJoesIotaRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-iota-runtime.sh

      - name: Test C♯ from dotnet via fishy-joes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          FISHYJOES=1 swift run -- fishy-joes --c-sharp build test

      - name: Test Dart from dart via fishy-joes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          FISHYJOES=1 swift run -- fishy-joes --dart build test

      - name: Build FishyJoesJavaRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          libdir=kotlin-runtime/src/generated/resources/mac
          rm -rf $libdir
          mkdir -p $libdir
          ./scripts/compile-kotlin-native-runtime.sh
          (cd kotlin-runtime && ./gradlew publishToMavenLocal)

      - name: Test kotlin from gradle via fishy-joes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          FISHYJOES=1 swift run -- fishy-joes --kotlin-fast build test

  integration-tests-ubuntu:
    name: "Ubuntu: Integration tests"
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      CONFIGURATION: debug

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Login to github registry
        uses: docker/login-action@v2
        with:
          username: cricut-builduser
          password:  ${{ secrets.CRICUT_GPR_TOKEN }}
          registry: ghcr.io

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 20

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@cricut'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'

      - uses: dart-lang/setup-dart@v1

      - name: Configure build environment
        run: |
          set -euxo pipefail

          sudo apt-get install zsh

          # Sadly, Ubuntu LTS doesn't have an up-to-date binaryen, so use a wasm version instead
          npm -g install binaryen@111.0.0

          SWIFT_WASM_VERSION="5.10-SNAPSHOT-2024-04-26-a"
          curl -Lo swift-wasm.tgz "https://github.com/swiftwasm/swift/releases/download/swift-wasm-$SWIFT_WASM_VERSION/swift-wasm-$SWIFT_WASM_VERSION-ubuntu20.04_x86_64.tar.gz"
          sudo mkdir -p "/Library/Developer/Toolchains/swift-wasm-$SWIFT_WASM_VERSION.xctoolchain"
          sudo tar -xf swift-wasm.tgz -C "/Library/Developer/Toolchains/swift-wasm-$SWIFT_WASM_VERSION.xctoolchain" --strip-components 1

      - name: Build FishyJoesNodeRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-node-runtime.sh

      - name: Test TypeScript from npm via FishyJoes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          FISHYJOES=1 swift run -- fishy-joes --nodejs --wasm build test

      - name: Build FishyJoesIotaRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-iota-runtime.sh

      - name: Test C♯ from dotnet via fishy-joes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          FISHYJOES=1 swift run -- fishy-joes --c-sharp build test

      - name: Test Dart from dart via fishy-joes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          FISHYJOES=1 swift run -- fishy-joes --dart build test

      - name: Build linux FishyJoesJavaRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          libdir=kotlin-runtime/src/generated/resources/linux
          rm -rf $libdir
          mkdir -p $libdir
          ./scripts/compile-kotlin-native-runtime.sh

      # Running this step messes with permissions significantly,
      # in particular causing subsequent git checkouts to fail, so testing of Kotlin / Java is being done last
      - name: Build android FishyJoesJavaRuntime
        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/cricut/android-swift-runtime:3.0.1
          options: -v ${{ github.workspace }}:/work -w /work
          run: /work/scripts/compile-android-runtime.sh

      - name: Locally publish kotlin native & android runtimes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          # Publish runtime for the native linux test and the android tests
          (cd kotlin-runtime && ./gradlew publishToMavenLocal)

      - name: Test kotlin from gradle via fishy-joes
        shell: zsh {0}
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          FISHYJOES=1 swift run -- fishy-joes --kotlin build test

          # Publish test-api for the android tests to use later
          (cd bindings/kotlin/generated && ./gradlew publishToMavenLocal)

      - name: Upload artifacts for use by Android later
        uses: actions/upload-artifact@v4
        with:
          name: maven-local
          path: ~/.m2/repository

  integration-tests-windows:
    name: "Windows: Integration tests"
    runs-on: windows-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      SWIFT: ${{ github.workspace }}\scripts\swift-shim.ps1
      SWIFT_PACKAGE_RESOLVE: 0
      EXTRA_LIBPATH: '.build\lib'
      CONFIGURATION: debug
      FISHYJOES: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.10-release
          tag: 5.10-RELEASE

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 20

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@cricut'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6'

      - uses: dart-lang/setup-dart@v1

      - name: Pre-resolve Required SwiftPM Packages
        continue-on-error: true
        shell: pwsh
        run: |
          Set-PSDebug -Trace 2
          $ErrorActionPreference = 'SilentlyContinue'
          $env:FISHYJOES_DEPENDENCY_FishyJoes = @{local=@{path=$pwd.Path}} | ConvertTo-Json -Compress

          swift package resolve
          swift package resolve
          swift package resolve

          cd integration-tests/TestAPI-bindings
          swift package resolve
          swift package resolve
          swift package resolve

          swift package resolve --scratch-path .build/bindings --package-path bindings/swift-interfaces/generated/TestAPI-bindings
          swift package resolve --scratch-path .build/bindings --package-path bindings/swift-interfaces/generated/TestAPI-bindings
          swift package resolve --scratch-path .build/bindings --package-path bindings/swift-interfaces/generated/TestAPI-bindings

          cd ../../node-runtime/register-module-shim
          swift package resolve
          swift package resolve
          swift package resolve

      - name: Build FishyJoesNodeRuntime
        shell: bash
        run: |
          set -euxo pipefail

          ./scripts/compile-node-runtime.sh

      - name: Test TypeScript from npm via fishy-joes
        shell: bash
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          "$SWIFT" run -- fishy-joes --nodejs build test

      - name: Build FishyJoesIotaRuntime
        shell: bash
        run: |
          set -euxo pipefail

          ./scripts/compile-iota-runtime.sh

      - name: Test C♯ from dotnet via fishy-joes
        shell: bash
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          "$SWIFT" run -- fishy-joes --c-sharp build test

      - name: Test Dart from dart via fishy-joes
        shell: bash
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings

          # Add dart DLLs to path
          # Someone who understands windows better than I do is welcome to fix this in a better way
          PATH="$PWD/bindings/dart/generated/windows/native:$PATH"

          "$SWIFT" run -- fishy-joes --dart build test

      - name: Build FishyJoesJavaRuntime
        shell: bash
        run: |
          set -euxo pipefail

          ./scripts/compile-kotlin-native-runtime.sh
          (cd kotlin-runtime && ./gradlew publishToMavenLocal)

      - name: Test kotlin from gradle via fishy-joes
        shell: bash
        run: |
          set -euxo pipefail

          cd integration-tests/TestAPI-bindings
          "$SWIFT" run -- fishy-joes --kotlin-fast build test

  integration-tests-android:
    name: "Android: Integration Tests"
    needs: [integration-tests-ubuntu]
    runs-on: macOS-13
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      CONFIGURATION: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      # Must use Java 17 instead of Java 11 because Gradle requires it to build the Android sample app
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Retrieve artifacts
        uses: actions/download-artifact@v4

      - name: Build android test app
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ls -la maven-local

          rm -rf ~/.m2/repository
          mkdir -p ~/.m2
          mv maven-local ~/.m2/repository

          cd integration-tests/android-test-app
          ./gradlew assembleAndroidTest

      - name: Test android test app
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          # NOTE: each line of this script is executed in its own shell
          script: |
            cd integration-tests/android-test-app && ./gradlew connectedAndroidTest
