---
name: "Iota Runtime"

"on":
  workflow_dispatch:
  label:
    types:
      - created
  pull_request:
  release:
    types: [published]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
  GITHUB_USER: cricut-builduser

jobs:
  build-iota-mac:
    name: "macOS: Build Iota Runtime"
    runs-on: sojo-macos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Build FishyJoesIotaRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-iota-runtime.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac_generated
          path: .build/apple/release/libFishyJoesIotaRuntime.dylib
          if-no-files-found: error

  build-iota-ubuntu:
    name: "Ubuntu: Build Iota Runtime"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cricut/android-swift-runtime:4.0.0-alpha2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      LIB_DIR: .build/linux-iota-libs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Configure build environment
        run: |
          set -eux

          apt-get -y update
          apt-get -y install patchelf
          git config --global --add safe.directory '*'

      - name: Build FishyJoesIotaRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-iota-runtime.sh

      - name: Collect libFishyJoesIotaRuntime and its dependencies
        shell: zsh {0}
        run: |
          set -euxo pipefail

          mkdir -p $LIB_DIR

          binPath="$(swift build --configuration release --show-bin-path)"
          cp -dv $binPath/libFishyJoesIotaRuntime.so $LIB_DIR

          cp -dv /usr/lib/swift/linux/*.so $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libxml2.so* $LIB_DIR

      - name: Patch libraries to use relative dependencies
        shell: zsh {0}
        run: |
          cd $LIB_DIR

          SWIFT_RUN_PATH='/usr/lib/swift/linux:./:$ORIGIN'
          for LIB in lib*.so*; do
            patchelf --set-rpath $SWIFT_RUN_PATH $LIB
          done

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_generated
          path: .build/linux-iota-libs
          if-no-files-found: error

  build-iota-windows:
    name: "Windows: Build Iota Runtime"
    runs-on: windows-2025
    env:
      LIB_DIR: .build/windows-iota-libs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-6.1-release
          tag: 6.1-RELEASE

      - name: Pre-resolve Required SwiftPM Packages
        continue-on-error: true
        shell: pwsh
        run: |
          $ErrorActionPreference = 'SilentlyContinue'
          swift package resolve
          swift package resolve
          swift package resolve

      - name: Build FishyJoesIotaRuntime
        shell: bash
        run: |
          set -euxo pipefail

          ./scripts/compile-iota-runtime.sh

      - name: Collect libFishyJoesIotaRuntime and its dependencies
        shell: bash
        run: |
          set -euxo pipefail

          mkdir -p "$LIB_DIR"
          SWIFT_RUNTIME_DIR="$(realpath "$SDKROOT/../../../.." | sed s#Platforms#Runtimes#g)"
          cp -R "$SWIFT_RUNTIME_DIR/usr/bin/"*.dll "$LIB_DIR"

          binPath="$(swift build --configuration release --show-bin-path)"
          cp -R "$binPath/FishyJoesIotaRuntime.dll" "$LIB_DIR"

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: windows_generated
          path: .build/windows-iota-libs
          if-no-files-found: error

  iota-publish:
    name: "Publish C# Package and Dart Binaries"
    runs-on: ubuntu-latest
    needs:
      - build-iota-mac
      - build-iota-ubuntu
      - build-iota-windows
    env:
      GITHUB_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '6.0.x'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@cricut'

      - name: Configure build environment
        run: |
          set -euxo pipefail
          sudo apt-get install zsh

      - name: Retrieve Artifacts
        uses: actions/download-artifact@v4

      - name: Install Artifacts
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ls *

          rm -rf c-sharp-runtime/runtimes
          mkdir -p c-sharp-runtime/runtimes/{osx,linux,win}/native
          cp -dv mac_generated/* c-sharp-runtime/runtimes/osx/native/
          cp -dv ubuntu_generated/* c-sharp-runtime/runtimes/linux/native/
          cp -dv windows_generated/* c-sharp-runtime/runtimes/win/native/

          ls -R c-sharp-runtime/

          rm -rf dart-runtime/{macos,linux,windows}/native
          mkdir -p dart-runtime/{macos,linux,windows}/native
          cp -dv mac_generated/* dart-runtime/macos/native/
          cp -dv ubuntu_generated/* dart-runtime/linux/native/
          cp -dv windows_generated/* dart-runtime/windows/native/

          ls -R dart-runtime

      - name: Determine version
        shell: zsh {0}
        run: |
          set -euxo pipefail

          VERSION=${GITHUB_REF#refs/*/}
          if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)*$ ]]; then
              VERSION="0.0.1-$(git rev-parse --short HEAD)"
          fi
          echo "Detected Version is '$VERSION'"
          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Pack
        shell: zsh {0}
        run: |
          set -euxo pipefail

          dotnet pack \
              -c Release \
              c-sharp-runtime/Cricut.FishyJoesRuntime.csproj \
              "/p:Version=$VERSION" \
              --output c-sharp-runtime/nupkgs

          tar -cvzf FishyJoes-dart-binaries.tgz -C dart-runtime {macos,linux,windows}/native

          (
            cd dart-runtime

            rm -rf flutter-package
            mkdir -p flutter-package
            yq '.version = strenv(VERSION)' \
                < npm_flutter_pubspec.yaml \
                > flutter-package/pubspec.yaml

            jq '.version = env.VERSION' < npm_flutter_package.json > flutter-package/package.json
            cp -r lib macos linux windows flutter-package/
          )

          npm pack ./dart-runtime/flutter-package
          ls
          tar -tf cricut-flutter-fishyjoes-runtime-*.tgz

      - name: Upload Nuget Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: c-sharp-runtime/nupkgs/*.*nupkg
          if-no-files-found: error

      - name: Upload Dart Tarball
        uses: actions/upload-artifact@v4
        with:
          name: FishyJoes-dart-binaries
          path: FishyJoes-dart-binaries.tgz
          if-no-files-found: error

      - name: Publish
        shell: zsh {0}
        if: github.event_name == 'release'
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euxo pipefail

          # publish C#

          dotnet nuget push ./c-sharp-runtime/nupkgs/*.*nupkg \
            --source https://nuget.pkg.github.com/cricut \
            --api-key ${{ github.token }} \
            --skip-duplicate

          # publish dart

          releaseID=$(
              gh api \
              -H "Accept: application/vnd.github.v3+json" \
              "/repos/$OWNER/$REPO/releases/tags/$TAG_NAME" \
              -q .id
          )

          file=FishyJoes-dart-binaries.tgz

          # https://docs.github.com/en/rest/releases/assets#upload-a-release-asset
          curl -f -u "$GITHUB_USER:$GITHUB_PUBLISH_TOKEN" \
            -X POST \
            -H 'Content-Type: application/gzip' \
            -H 'Accept: application/vnd.github.v3+json' \
            "https://uploads.github.com/repos/$OWNER/$REPO/releases/$releaseID/assets?name=$file" \
            --data-binary @$file

          # publish flutter NPM package
          npm publish cricut-flutter-fishyjoes-runtime-*.tgz
