---
name: "Iota Runtime"

"on":
  workflow_dispatch:
  push:
    branches:
      - main
  label:
    types:
      - created
  pull_request:
  release:
    types: [published]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-iota-mac:
    name: "macOS: Build Iota Runtime"
    runs-on: macOS-12
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Build FishyJoesIotaRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-iota-runtime.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac_generated
          path: .build/apple/release/libFishyJoesIotaRuntime.dylib

  build-iota-ubuntu:
    name: "Ubuntu: Build Iota Runtime"
    runs-on: ubuntu-latest
    container:
      image: swift
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      LIB_DIR: .build/linux-iota-libs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Configure build environment
        run: |
          set -eux

          apt-get -y update
          apt-get -y install zsh patchelf

      - name: Build FishyJoesIotaRuntime
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ./scripts/compile-iota-runtime.sh

      - name: Copy swift runtime SOs
        shell: zsh {0}
        run: |
          set -euxo pipefail

          mkdir -p $LIB_DIR

          binPath="$(swift build --configuration release --show-bin-path)"
          cp -dv $binPath/libFishyJoesIotaRuntime.so $LIB_DIR

          cp -dv /usr/lib/swift/linux/libswift*.so* $LIB_DIR
          cp -dv /usr/lib/swift/linux/libicu*.so* $LIB_DIR
          cp -dv /usr/lib/swift/linux/libFoundation*.so $LIB_DIR
          cp -dv /usr/lib/swift/linux/libBlocksRuntime.so $LIB_DIR
          cp -dv /usr/lib/swift/linux/libdispatch.so $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libicui18n.so* $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libicuuc.so* $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libicudata.so* $LIB_DIR
          cp -dv /usr/lib/x86_64-linux-gnu/libxml2.so* $LIB_DIR

      - name: Patch system swift runtime SOs to use relative libraries
        shell: zsh {0}
        run: |
          cd $LIB_DIR

          SWIFT_RUN_PATH='/usr/lib/swift/linux:./:$ORIGIN'
          for LIB in lib*.so*; do
            patchelf --set-rpath $SWIFT_RUN_PATH $LIB
          done

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu_generated
          path: .build/linux-iota-libs

  build-iota-windows:
    name: "Windows: Build Iota Runtime"
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      LIB_DIR: .build/windows-iota-libs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.6.2-release
          tag: 5.6.2-RELEASE

      - name: Build FishyJoesIotaRuntime
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"

          # Should perform the same actions as scripts/compile-iota-runtime.sh, but must be done in powershell for swift-build to work
          swift build --product FishyJoesIotaRuntime --configuration release --build-path ./.build/windows-build
          New-Item -ItemType Directory -Force -Path $env:LIB_DIR
          Copy-Item .build\windows-build\x86_64-unknown-windows-msvc\release\FishyJoesIotaRuntime.dll -Destination $env:LIB_DIR

      - name: Copy swift runtime DLLs
        shell: bash
        run: |
          set -euxo pipefail

          cp -R /c/Library/icu-*/usr/bin/*.dll $LIB_DIR
          cp -R /c/Library/Swift-development/bin/*.dll $LIB_DIR

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: windows_generated
          path: .build/windows-iota-libs

  iota-publish:
    name: "Publish C# Package and Dart Binaries"
    runs-on: ubuntu-latest
    needs: [build-iota-mac, build-iota-ubuntu, build-iota-windows]
    env:
      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
      GITHUB_USER: cricut-builduser
      GITHUB_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git Credentials
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Configure build environment
        run: |
          set -euxo pipefail
          sudo apt-get install zsh

      - name: Retrieve Artifacts
        uses: actions/download-artifact@v4

      - name: Install Artifacts
        shell: zsh {0}
        run: |
          set -euxo pipefail

          ls *

          rm -rf c-sharp-runtime/runtimes
          mkdir -p c-sharp-runtime/runtimes/{osx,linux,win}/native
          cp -dv mac_generated/* c-sharp-runtime/runtimes/osx/native/
          cp -dv ubuntu_generated/* c-sharp-runtime/runtimes/linux/native/
          cp -dv windows_generated/* c-sharp-runtime/runtimes/win/native/

          ls -R c-sharp-runtime/

          rm -rf dart-runtime/native
          mkdir -p dart-runtime/native/{macos,linux,windows}
          cp -dv mac_generated/* dart-runtime/native/macos/
          cp -dv ubuntu_generated/* dart-runtime/native/linux/
          cp -dv windows_generated/* dart-runtime/native/windows/

          ls -R dart-runtime

      - name: Determine version
        shell: zsh {0}
        run: |
          set -euxo pipefail

          VERSION=${GITHUB_REF#refs/*/}
          if [[ ! $VERSION =~ [0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)* ]]; then
              VERSION="0.0.1-$(git rev-parse --short HEAD)"
          fi
          echo "Detected Version is '$VERSION'"
          echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Pack
        shell: zsh {0}
        run: |
          set -euxo pipefail

          (
            cd c-sharp-runtime
            dotnet pack -c Release -o out /p:PackageVersion="${{ env.VERSION }}"
          )

          tar -cvzf FishyJoes-dart-binaries.tgz -C dart-runtime native

      - name: Upload Nuget Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: c-sharp-runtime/out/*.*nupkg

      - name: Upload Dart Tarball
        uses: actions/upload-artifact@v4
        with:
          name: FishyJoes-dart-binaries
          path: FishyJoes-dart-binaries.tgz

      - name: Publish
        shell: zsh {0}
        if: github.event_name == 'release'
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          set -euxo pipefail

          # publish C#

          dotnet nuget push ./c-sharp-runtime/out/*.*nupkg \
            --source https://nuget.pkg.github.com/cricut \
            --api-key ${{ github.token }} \
            --skip-duplicate

          # publish dart

          releaseID=$(
              gh api \
              -H "Accept: application/vnd.github.v3+json" \
              "/repos/$OWNER/$REPO/releases/tags/$TAG_NAME" \
              -q .id
          )

          file=FishyJoes-dart-binaries.tgz

          # https://docs.github.com/en/rest/releases/assets#upload-a-release-asset
          curl -f -u "$GITHUB_USER:$GITHUB_PUBLISH_TOKEN" \
            -X POST \
            -H 'Content-Type: application/gzip' \
            -H 'Accept: application/vnd.github.v3+json' \
            "https://uploads.github.com/repos/$OWNER/$REPO/releases/$releaseID/assets?name=$file" \
            --data-binary @$file
