name: Build & test

on:
  workflow_dispatch:
  label:
    types:
      - created
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  test:
    name: Build & test
    env:
      SWIFT_WASM_URL: |-
        https://github.com/swiftwasm/swift/releases/download/swift-wasm-5.6.0-RELEASE/swift-wasm-5.6.0-RELEASE-macos_x86_64.pkg
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git Credentials
        uses: fusion-engineering/setup-git-credentials@v2.0.1
        with:
          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/

      - name: swiftlint
        run: |
          swiftlint lint --reporter github-actions-logging

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@cricut'

      - name: Configure build environment
        shell: zsh {0}
        run: |
          set -euxo pipefail

          curl -Lo swift-wasm.pkg $SWIFT_WASM_URL
          sudo installer -pkg swift-wasm.pkg -target /

          brew install binaryen

          (cd Tests/NAPITests/node-tests; npm install)

      - name: Build
        shell: zsh {0}
        run: |
          set -euxo pipefail

          swift build

      - name: Test
        shell: zsh {0}
        run: |
          set -euxo pipefail
          npm install

          swift test
