---
name: "SwiftLint"

"on":
  workflow_dispatch:
  label:
    types:
      - created
  pull_request:

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.53.0
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: SwiftLint
        run: |
          swiftlint --version
          swiftlint --reporter github-actions-logging --strict ||
              swiftlint --reporter emoji --strict --quiet
