public enum CommonStrings {
    // Common string for various generation processes to warn that an output source file is generated.
    public static let autogenWarning = "THIS FILE IS AUTOMATICALLY GENERATED, AND WILL BE OVERWRITTEN. DO NOT EDIT."
}
